// Redistributable web-asset allowlist (neutralization N1a, LICENSE-AUDIT R-1.2 / H4).
//
// `apps/web/public/assets/manifest.json` lists the 3D models the product may load, render as catalog thumbnails or hand to end
// users in export zips. Only entries that are (a) generated by the AIDC asset pipeline itself (`generated: true`) and (b) carry a
// non-empty `license` field qualify; anything else in `models/` (e.g. a locally converted third-party model) is ignored by the
// viewer, the catalog thumbnails and the export zip. File names must be plain `*.glb` basenames (no paths).
export interface AssetManifestModel {
  name?: string;
  file?: string;
  lod1?: string;
  generated?: boolean;
  license?: string;
  [key: string]: unknown;
}

export interface AssetManifest {
  models?: AssetManifestModel[];
  /** `{ "<model>.glb": "thumbs/<model>.png" }` written by tools/asset-pipeline/render_thumbs.py */
  thumbs?: Record<string, string>;
  [key: string]: unknown;
}

const SAFE_GLB = /^[A-Za-z0-9][A-Za-z0-9._-]*\.glb$/;
const SAFE_THUMB = /^thumbs\/[A-Za-z0-9][A-Za-z0-9._-]*\.(png|webp|jpg)$/;

/** True for a manifest model entry that may be shipped: generated by the pipeline, licence stated, safe file name. */
export function isRedistributableModel(m: unknown): m is AssetManifestModel & { file: string; license: string } {
  if (!m || typeof m !== 'object') return false;
  const e = m as AssetManifestModel;
  return e.generated === true && typeof e.license === 'string' && e.license.trim() !== '' && typeof e.file === 'string' && SAFE_GLB.test(e.file);
}

/** GLB file names (LOD0 and, when listed, LOD1) of every redistributable manifest model. */
export function allowedModelFiles(manifest: AssetManifest | null | undefined, opts: { lod1?: boolean } = {}): Set<string> {
  const out = new Set<string>();
  const models = Array.isArray(manifest?.models) ? manifest!.models : [];
  for (const m of models) {
    if (!isRedistributableModel(m)) continue;
    out.add(m.file);
    if (opts.lod1 !== false && typeof m.lod1 === 'string' && SAFE_GLB.test(m.lod1)) out.add(m.lod1);
  }
  return out;
}

/** The manifest `thumbs` map restricted to redistributable models (a stale entry for a removed model is dropped). */
export function allowedThumbnails(manifest: AssetManifest | null | undefined): Record<string, string> {
  const models = allowedModelFiles(manifest, { lod1: false });
  const out: Record<string, string> = {};
  const thumbs = manifest?.thumbs && typeof manifest.thumbs === 'object' ? manifest.thumbs : {};
  for (const [glb, rel] of Object.entries(thumbs)) if (models.has(glb) && typeof rel === 'string' && SAFE_THUMB.test(rel)) out[glb] = rel;
  return out;
}
