import type { GlossaryTerm } from '../model/types.ts';

/**
 * AIDC Studio terminology glossary (stream S4, PROPOSAL-v2 §3.8, DECISIONS-v2 #16).
 *
 * Every entry carries an English and a Korean term + one-line explanation; `long` adds the worked examples that the
 * help drawer / design document reuse. Definitions are AIDC Studio's own wording; `sources` name the public documents the
 * facts were checked against (vendor data-center design guides from NVIDIA and AMD, AMD–DriveNets RA, ASHRAE TC 9.9, TIA-942,
 * Uptime Institute, IEEE 802.1Qbb/RFC 3168/RFC 8391, Open Compute Project). Definitions are pure data — no numbers
 * here feed the engines; numeric examples are illustrative and tagged in the text itself. Vendor and product names are
 * nominative references only (no affiliation or endorsement).
 */

type Opts = {
  long?: { en: string; ko: string };
  related?: string[];
  sources?: string[];
  aliases?: string[];
  domain?: GlossaryTerm['domain'];
};

const S = {
  refDesign: 'Public AI-factory reference designs (NVIDIA reference design / DGX SuperPOD, AMD Helios / Instinct DC design documentation)',
  superpod: 'NVIDIA DGX SuperPOD Data Center Design Guide DG-11301-001',
  facilities: 'NVIDIA Facilities Infrastructure Reference Design v2.0 (2026-08-19)',
  amdDc: 'AMD Instinct Data Center Design Guide (instinct.docs.amd.com/projects/dc-design)',
  amdRd: 'AMD Instinct MI3XX Reference Design — Cluster Networking Guide',
  drivenets: 'AMD–DriveNets Reference Architecture (Fabric Scheduled Ethernet)',
  ashrae: 'ASHRAE TC 9.9 Thermal Guidelines for Data Processing Environments (5th ed.)',
  tia: 'TIA-942-C Telecommunications Infrastructure Standard for Data Centers',
  uptime: 'Uptime Institute Tier Standard: Topology',
  ocp: 'Open Compute Project — Open Rack V3 / ORW / OAM specifications',
  ieee: 'IEEE 802.1Qbb (PFC), RFC 3168 (ECN), RFC 8391 / DCQCN (Zhu et al., SIGCOMM 2015)',
  nccl: 'NVIDIA NCCL documentation & nccl-tests README (busbw / algbw definitions)',
  mlperf: 'MLPerf Training / PaLM paper (MFU definition), Meta "Goodput" (Llama 3 training report)',
  ueC: 'Ultra Ethernet Consortium specification 1.0 (2025)',
  ualink: 'UALink Consortium 1.0 specification (2025)',
  ieeeEth: 'IEEE 802.3df/dj 800G/1.6T Ethernet, MSA datasheets (OSFP, QSFP-DD, LPO MSA)',
  green: 'The Green Grid — PUE / WUE / CUE white papers',
  bipa: 'Uptime / BICSI-002 data center design best practices',
};

function t(id: string, en: string, ko: string, shortEn: string, shortKo: string, o: Opts = {}): GlossaryTerm {
  return {
    id,
    term: { en, ko },
    short: { en: shortEn, ko: shortKo },
    ...(o.long ? { long: o.long } : {}),
    ...(o.related ? { related: o.related } : {}),
    ...(o.sources ? { sources: o.sources } : {}),
    ...(o.aliases ? { aliases: o.aliases } : {}),
    domain: o.domain ?? 'general',
  };
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ───────────── Layout units ─────────────
  t('su', 'Scalable Unit (SU)', '스케일러블 유닛 (SU)',
    'A repeatable network and deployment block defined by a specific vendor reference architecture. Its boundary is architecture-specific and is not the accelerator scale-up domain or an AIDC Studio hall DU.',
    '특정 vendor 레퍼런스 아키텍처가 정의한 반복 가능한 네트워크·배포 블록. 경계는 아키텍처마다 다르며 가속기 scale-up 도메인이나 AIDC Studio 홀 DU와 같지 않다.',
    { long: { en: 'There is no universal NVIDIA SU size. The GB300 enterprise reference architecture uses one NVL72 rack per SU, while the DGX SuperPOD GB300 reference architecture uses eight racks per SU. NVIDIA’s facilities reference design instead defines one SU as one compute HAC plus one support HAC; its 250 MW / 96-SU example implies 16 GPU racks per SU (1,536 ÷ 96). NVIDIA’s Rubin launch article groups 14 NVL72 systems in a SuperPOD but does not label that group an SU. Always record the cited architecture and its switch, rail and facility assumptions.', ko: 'NVIDIA SU에 보편적인 크기는 없다. GB300 enterprise 레퍼런스 아키텍처는 NVL72 랙 1대를 SU 1개로, DGX SuperPOD GB300 레퍼런스는 랙 8대를 SU 1개로 정의한다. 반면 NVIDIA 시설 레퍼런스는 Compute HAC 1개 + Support HAC 1개를 SU로 정의하며, 250 MW / 96 SU 예시는 SU당 GPU 랙 16대(1,536 ÷ 96)를 뜻한다. NVIDIA Rubin 발표의 NVL72 14대 묶음은 SuperPOD 구성이지 SU라고 명시되지 않았다. 따라서 인용 아키텍처와 스위치·레일·시설 가정을 함께 기록해야 한다.' }, related: ['du', 'hac', 'cin'], sources: [S.refDesign, S.superpod, S.facilities], aliases: ['scalable unit'], domain: 'layout' }),
  t('du', 'Deployment Unit (DU) / pod', '배포 단위 (DU) / 포드',
    'AIDC Studio grouping of racks that is placed, powered, cooled and scheduled together (rows of GPU racks + in-row CDUs + leaf racks). One DU maps to one deployment wave entry.',
    'AIDC Studio에서 배치·전력·냉각·일정의 단위가 되는 랙 묶음(GPU 랙 열 + 인로우 CDU + 리프 랙). 하나의 DU가 배포 웨이브 항목 하나에 대응한다.',
    { related: ['su', 'rcu', 'wave'], aliases: ['pod', 'deployment unit'], domain: 'layout' }),
  t('rcu', 'Rack Compute Unit (RCU)', '랙 컴퓨트 유닛 (RCU)',
    'A single rack-scale compute system (e.g. GB300 NVL72, Helios ORW) treated as one unit of compute, power and liquid cooling.',
    '랙 단위 컴퓨트 시스템 1대(예: GB300 NVL72, Helios ORW)를 연산·전력·액랭의 단위로 보는 개념.',
    { related: ['du', 'nvl72'], domain: 'layout' }),
  t('hac', 'Hot-Aisle Containment (HAC)', '핫에일 컨테인먼트 (HAC)',
    'Enclosing the hot aisle between two rack rows so exhaust air returns to the CRAH / ceiling plenum without mixing with supply air. A common default in liquid-cooled AI halls; allows a higher supply temperature and lower fan energy.',
    '두 랙 열 사이의 열복도를 밀폐해 배기가 급기와 섞이지 않고 CRAH·천장 플레넘으로 돌아가게 하는 방식. 액체 냉각 AI 홀에서 흔한 기본값이며 급기 온도를 높이고 팬 에너지를 줄인다.',
    { related: ['cac', 'crah', 'rti'], sources: [S.refDesign, S.amdDc], aliases: ['hot aisle containment'], domain: 'cooling' }),
  t('cac', 'Cold-Aisle Containment (CAC)', '콜드에일 컨테인먼트 (CAC)',
    'Enclosing the cold aisle so supply air is delivered only to rack intakes; the rest of the room runs at return temperature. Common with raised-floor supply.',
    '냉복도를 밀폐해 급기가 랙 흡기구에만 공급되도록 하는 방식. 나머지 실내는 환기 온도로 운전. 이중마루 급기 구조에서 흔하다.',
    { related: ['hac', 'raised-floor'], sources: [S.amdDc], aliases: ['cold aisle containment'], domain: 'cooling' }),
  t('cin', 'Compute Interconnect Network (CIN)', '컴퓨트 인터커넥트 네트워크 (CIN)',
    'Compute interconnect network: the name some reference designs (e.g. the NVIDIA reference design) give the GPU scale-out (east-west) fabric. Its spine is usually placed between compute halls, within a single-mode fibre reach of about 500 m.',
    '컴퓨트 인터커넥트 네트워크. 일부 레퍼런스 설계(예: NVIDIA 레퍼런스 설계)가 GPU 스케일아웃(동서) 패브릭에 붙인 이름. 스파인은 보통 컴퓨트 홀 사이, 단일모드 광 도달 거리 약 500 m 이내에 둔다.',
    { related: ['spine', 'su', 'scale-out'], sources: [S.refDesign], domain: 'network' }),
  t('cub', 'Central Utility Building (CUB)', '중앙 유틸리티 동 (CUB)',
    'Building that houses chillers, dry coolers, pumps and facility-water plant serving several data halls; campus plans often place one CUB at each end.',
    '여러 데이터 홀에 냉수·시설수를 공급하는 칠러·드라이쿨러·펌프 설비 동. 캠퍼스 계획에서는 흔히 양 끝에 CUB를 하나씩 둔다.',
    { related: ['fws', 'chiller', 'dry-cooler'], sources: [S.refDesign], domain: 'cooling' }),
  t('tcs', 'Technology Cooling System (TCS)', '기술 냉각 계통 (TCS)',
    'Secondary liquid loop between the CDU and the IT equipment cold plates (treated water / PG25). Warm-water designs run supply temperatures up to about 45 °C (ASHRAE W45) at roughly 1.5 LPM per kW or more.',
    'CDU와 IT 장비 콜드플레이트 사이의 2차측 액체 루프(처리수/PG25). 온수 설계는 공급 온도 최대 약 45 °C(ASHRAE W45), kW당 약 1.5 LPM 이상으로 운전한다.',
    { related: ['fws', 'cdu', 'ashrae-w'], sources: [S.refDesign, S.amdDc], aliases: ['secondary loop', 'technology cooling system'], domain: 'cooling' }),
  t('fws', 'Facility Water System (FWS)', '시설수 계통 (FWS)',
    'Primary loop from the plant (chillers, dry coolers, towers) to the CDU heat exchangers and CRAH coils.',
    '플랜트(칠러·드라이쿨러·냉각탑)에서 CDU 열교환기와 CRAH 코일까지의 1차측 루프.',
    { related: ['tcs', 'cdu', 'cub'], sources: [S.refDesign, S.amdDc], aliases: ['primary loop', 'facility water'], domain: 'cooling' }),
  t('atd', 'Approach Temperature Difference (ATD)', '접근 온도차 (ATD)',
    'Temperature difference across a heat exchanger between the two fluids (e.g. FWS supply vs TCS supply at the CDU). Smaller ATD needs more exchanger area or flow.',
    '열교환기에서 두 유체의 온도차(예: CDU에서 FWS 공급 온도와 TCS 공급 온도의 차). ATD가 작을수록 더 큰 열교환 면적이나 유량이 필요하다.',
    { related: ['cdu', 'tcs', 'fws'], sources: [S.amdDc], domain: 'cooling' }),
  t('rpp', 'Remote Power Panel (RPP)', '원격 분전반 (RPP)',
    'Floor-standing panelboard fed from a PDU/UPS that distributes branch circuits to racks; the alternative to overhead busway.',
    'PDU/UPS에서 급전받아 랙까지 분기 회로를 배분하는 바닥 설치 분전반. 오버헤드 버스웨이의 대안.',
    { related: ['busway', 'pdu'], sources: [S.bipa], domain: 'power' }),
  t('edp', 'Electrical Design Point (EDP)', '전기 설계점 (EDP)',
    'The rack power value the electrical distribution is sized to. Designers apply factors such as 1.2–1.5 × TDP to cover failure and transient cases.',
    '배전 설비를 설계하는 기준 랙 전력. 장애·과도 상황을 반영해 1.2–1.5 × TDP 같은 계수를 적용한다.',
    { related: ['edpp', 'maxp', 'tdp'], sources: [S.refDesign], domain: 'power' }),
  t('edpp', 'EDPP1 / EDPP2 (Extended Duration Peak Power)', 'EDPP1 / EDPP2 (지속 피크 전력)',
    'NVIDIA rack power tiers above TDP: EDPP1 sustained for seconds (GB300 NVL72 DC 204 kW), EDPP2 the short-burst maximum (240 kW) — the level the busbar and breakers must survive.',
    'TDP 이상의 NVIDIA 랙 전력 단계. EDPP1은 수 초 지속 피크(GB300 NVL72 DC 204 kW), EDPP2는 순간 최대치(240 kW)로 버스바·차단기가 견뎌야 하는 값.',
    { long: { en: 'Illustrative planning values (AIDC Studio catalog estimates for an NVL72-class rack): nameplate 136 kW, peak 204 kW, ramp 20 kW/s. Design rule: size breakers and busway to the peak value, size UPS / generators to TDP × diversity with smoothing.', ko: '예시 계획 값(NVL72급 랙에 대한 AIDC Studio 카탈로그 추정치): 명판 136 kW, 피크 204 kW, 램프 20 kW/s. 설계 규칙: 차단기·버스웨이는 피크 값, UPS·발전기는 TDP × 다양성(스무딩 포함) 기준.' }, related: ['edp', 'tdp', 'power-smoothing'], sources: [S.refDesign], aliases: ['edpp1', 'edpp2'], domain: 'power' }),
  t('tdp', 'TDP (Thermal Design Power)', 'TDP (열 설계 전력)',
    'Sustained power the cooling system must remove; for racks it is the nameplate continuous value, below EDPP peaks.',
    '냉각 계통이 지속적으로 제거해야 하는 전력. 랙에서는 명판 연속값이며 EDPP 피크보다 낮다.',
    { related: ['edpp', 'maxp'], domain: 'power' }),
  t('maxp', 'MaxP / MaxQ', 'MaxP / MaxQ',
    'NVIDIA GPU power policies: MaxP = maximum performance at full power; MaxQ = best performance per watt at a reduced power cap. Vendor power-provisioning frameworks (e.g. NVIDIA MaxLPS) combine them with dynamic power allocation.',
    'NVIDIA GPU 전력 정책. MaxP = 최대 성능(최대 전력), MaxQ = 낮춘 전력 캡에서 와트당 최고 성능. 벤더 전력 운용 프레임워크(예: NVIDIA MaxLPS)는 이를 동적 전력 배분과 결합한다.',
    { related: ['maxlps', 'edpp'], sources: [S.refDesign], aliases: ['maxq', 'max-q', 'max-p'], domain: 'power' }),
  t('maxlps', 'MaxLPS (NVIDIA power provisioning)', 'MaxLPS (NVIDIA 전력 운용)',
    'NVIDIA name for a design and operations approach that combines warm-water cooling, dynamic rack-to-rack power allocation, in-rack smoothing and MaxP/MaxQ policies so that more GPUs fit in the same power envelope.',
    '온수 냉각, 랙 간 동적 전력 배분, 랙 내 스무딩, MaxP/MaxQ 정책을 결합해 같은 전력 범위에 더 많은 GPU를 넣는 설계·운영 방식에 NVIDIA가 붙인 이름.',
    { related: ['maxp', 'su', 'power-smoothing'], sources: [S.refDesign], domain: 'power' }),
  t('bess', 'Battery Energy Storage System (BESS)', '배터리 에너지 저장장치 (BESS)',
    'Grid-scale battery (often on the MV bus) that buffers training-load swings, provides ride-through and demand response; large campuses often connect it to the medium-voltage bus.',
    '학습 부하 변동 완충, 순간정전 극복, 수요 반응에 쓰이는 대용량 배터리(대개 중전압 모선). 대형 캠퍼스는 흔히 중전압 모선에 연결한다.',
    { related: ['power-smoothing', 'ups', 'lvrt'], sources: [S.refDesign], domain: 'power' }),
  t('power-smoothing', 'Power smoothing', '전력 평활화',
    'Limiting the rate and size of IT load swings seen by the utility: rack-level energy storage (GB300 power shelves), GPU ramp limits, or a facility BESS.',
    '수전 측에서 보이는 IT 부하 변동의 크기·속도를 제한하는 것. 랙 레벨 에너지 저장(GB300 파워셸프), GPU 램프 제한, 시설 BESS 등.',
    { related: ['bess', 'edpp', 'maxlps'], sources: [S.refDesign], domain: 'power' }),
  t('lvrt', 'Low-Voltage Ride-Through (LVRT)', '저전압 극복 (LVRT)',
    'Ability of the site (with BESS / UPS) to stay connected and keep load through a short grid voltage dip instead of tripping.',
    '짧은 계통 전압 강하 동안 트립하지 않고 부하를 유지하며 연결을 지속하는 능력(BESS/UPS 활용).',
    { related: ['bess', 'ups'], sources: [S.refDesign], domain: 'power' }),

  // ───────────── Network sizing ─────────────
  t('oversubscription', 'Oversubscription', '오버서브스크립션',
    'At one switch tier: total bandwidth toward servers/leaves ÷ total bandwidth toward spines/cores. 1:1 = non-blocking capacity; 3:1 = only a third gets through when every server bursts at once.',
    '한 스위치 계층에서 아래(서버·리프)로 향하는 대역폭 합 ÷ 위(스파인·코어)로 향하는 대역폭 합. 1:1 = 용량 기준 논블로킹, 3:1 = 모든 서버가 동시에 쏘면 1/3만 통과.',
    { long: {
      en: '64-port × 800G leaf: 32 server ports (25.6 Tb/s) / 32 spine ports (25.6 Tb/s) → 1:1 (rearrangeably non-blocking by capacity; effective throughput still depends on load-balancing efficiency η ≈ 60–95 %). Same switch with 48 server / 16 spine ports (38.4 / 12.8 Tb/s) → 3:1.\n\nNotation: AIDC Studio writes down:up as N:1. NVIDIA documents say "1:3 blocking" for the same 3:1 case. AMD writes "1:1.16", meaning down 1 : up 1.16 — an undersubscription (uplink capacity = 1.16 × downlink demand); the UI shows it as "1:1.16" only.\n\nWhere: GPU back-end (E/W) 1:1. Converged storage/in-band leaves by generation: H100 4:3 → GB200 5:3 → GB300 3:1 ("1:3 blocking", SN5600/BF3) → Vera Rubin N/S 2:1 (12 GB/s per GPU). The invariant across generations is 9–17 GB/s of storage bandwidth per GPU.',
      ko: '64포트 × 800G 리프: 서버 32포트(25.6 Tb/s) / 스파인 32포트(25.6 Tb/s) → 1:1(용량 기준 논블로킹, 실효 처리량은 로드밸런싱 효율 η ≈ 60–95 %에 좌우). 같은 스위치에서 서버 48포트 / 스파인 16포트(38.4 / 12.8 Tb/s) → 3:1.\n\n표기: AIDC Studio는 다운:업 = N:1. NVIDIA 문서의 "1:3 blocking"은 같은 3:1. AMD의 "1:1.16"은 다운 1 : 업 1.16, 즉 언더서브스크립션(업링크 용량 = 다운 수요 × 1.16)이며 UI에는 "1:1.16"으로만 표기한다.\n\n적용: GPU 백엔드(E/W) 1:1. 스토리지/인밴드 컨버지드 리프는 세대별 H100 4:3 → GB200 5:3 → GB300 3:1("1:3 blocking", SN5600/BF3) → Vera Rubin N/S 2:1(GPU당 12 GB/s). 세대를 관통하는 불변량은 GPU당 스토리지 대역 9–17 GB/s.',
    }, related: ['undersubscription', 'leaf', 'spine', 'radix', 'bisection'], sources: [S.refDesign, S.amdRd, S.superpod], aliases: ['over-subscription', 'blocking ratio', 'subscription ratio'], domain: 'network' }),
  t('undersubscription', 'Undersubscription', '언더서브스크립션',
    'Uplink capacity larger than downlink demand (e.g. AMD "1:1.16"). Buys headroom against imperfect ECMP hashing at the cost of more spine ports.',
    '업링크 용량이 다운링크 수요보다 큰 상태(예: AMD "1:1.16"). ECMP 해시 불균형에 대한 여유를 스파인 포트 추가 비용으로 산다.',
    { related: ['oversubscription', 'ecmp'], sources: [S.amdRd], domain: 'network' }),
  t('non-blocking', 'Non-blocking (1:1)', '논블로킹 (1:1)',
    'Fabric whose uplink capacity equals downlink capacity at every tier; by capacity any permutation can be routed, though hashing collisions still cost throughput.',
    '모든 계층에서 업링크 용량 = 다운링크 용량인 패브릭. 용량상 어떤 순열도 라우팅 가능하지만 해시 충돌은 여전히 처리량을 깎는다.',
    { related: ['oversubscription', 'ecmp', 'bisection'], domain: 'network' }),
  t('bisection', 'Bisection bandwidth', '이분 대역폭',
    'Minimum bandwidth crossing any cut that splits the endpoints into two equal halves; the headline capacity number for all-to-all traffic.',
    '엔드포인트를 절반으로 나누는 임의의 절단면을 가로지르는 최소 대역폭. all-to-all 트래픽의 대표 용량 지표.',
    { related: ['oversubscription', 'all-reduce'], domain: 'network' }),
  t('rail-optimized', 'Rail-optimized topology', '레일 최적화 토폴로지',
    'Each GPU\'s NIC k of every node in a pod connects to leaf k ("rail"), so GPU-k ↔ GPU-k traffic stays one hop away; NCCL PXN keeps most collectives inside the NVLink domain + one rail.',
    '포드 내 모든 노드의 k번째 NIC를 k번째 리프("레일")에 연결해 GPU-k ↔ GPU-k 트래픽이 1홉으로 끝나는 구조. NCCL PXN이 집합 통신 대부분을 NVLink 도메인 + 레일 하나 안에 가둔다.',
    { long: { en: 'SuperPOD H100: 1 SU = 8 leaves (one per rail) + 4 spines; 4 SU = 32 leaves + 16 spines. AIDC Studio sizes leaves per pod as rails × ⌈ports/rails/downlinks⌉. GB300 NVL72 uses 4 rails per node (railsPerNode) with 18 nodes per rack.', ko: 'SuperPOD H100: 1 SU = 리프 8(레일당 1) + 스파인 4, 4 SU = 리프 32 + 스파인 16. AIDC Studio는 포드별 리프 수를 레일 × ⌈포트/레일/다운링크⌉로 산정. GB300 NVL72는 노드당 4 레일(railsPerNode), 랙당 18 노드.' }, related: ['pxn', 'leaf', 'fat-tree', 'su'], sources: [S.superpod, S.nccl], aliases: ['rail optimized', 'rail'], domain: 'network' }),
  t('fat-tree', 'Fat tree / Clos', '팻 트리 / Clos',
    'Multi-stage topology where link capacity grows toward the root (or is kept constant with more parallel switches) so bisection bandwidth is preserved; leaf-spine is a 2-stage folded Clos.',
    '루트로 갈수록 링크 용량을 키우거나(또는 병렬 스위치를 늘려) 이분 대역폭을 유지하는 다단 토폴로지. 리프-스파인은 2단 접힌 Clos.',
    { related: ['leaf-spine', 'rail-optimized', 'tiers'], sources: [S.amdDc], aliases: ['clos', 'fat tree'], domain: 'network' }),
  t('leaf', 'Leaf switch', '리프 스위치',
    'First-tier switch that endpoints (GPU NICs, storage, servers) plug into; its downlink:uplink split sets the oversubscription.',
    '엔드포인트(GPU NIC·스토리지·서버)가 직접 연결되는 1계층 스위치. 다운링크:업링크 분할이 오버서브스크립션을 결정한다.',
    { related: ['spine', 'core', 'oversubscription', 'tor'], domain: 'network' }),
  t('spine', 'Spine switch', '스파인 스위치',
    'Second-tier switch interconnecting leaves; every leaf connects to every spine in a pod (full bipartite). In a 3-tier design spines connect up to cores.',
    '리프들을 서로 잇는 2계층 스위치. 포드 안에서 모든 리프가 모든 스파인에 연결(완전 이분 그래프). 3계층에서는 스파인이 코어로 올라간다.',
    { related: ['leaf', 'core', 'spine-placement'], domain: 'network' }),
  t('core', 'Core / super-spine switch', '코어 / 슈퍼스파인 스위치',
    'Third tier that joins several pods\' spines when a 2-tier fabric runs out of radix (endpoints > k²/2 for k-port switches).',
    '2계층 패브릭의 radix가 부족할 때(k포트 스위치에서 엔드포인트 > k²/2) 여러 포드의 스파인을 묶는 3계층.',
    { related: ['spine', 'tiers', 'radix'], aliases: ['super-spine', 'superspine'], domain: 'network' }),
  t('tor', 'Top-of-Rack (ToR)', '톱오브랙 (ToR)',
    'Leaf placed inside each rack, cabled with short DAC/AEC to that rack\'s nodes; contrasts with end-of-row / middle-of-row leaves.',
    '각 랙 안에 리프를 두고 짧은 DAC/AEC로 그 랙의 노드에 연결하는 방식. 엔드오브로우·미들오브로우 리프와 대비된다.',
    { related: ['leaf', 'eor', 'dac'], aliases: ['top of rack'], domain: 'network' }),
  t('eor', 'End-of-Row / Middle-of-Row (EoR / MoR)', '엔드오브로우 / 미들오브로우 (EoR / MoR)',
    'Leaf switches concentrated in one network rack at the end (or middle) of a row; longer node cables (MMF/AOC) but fewer switches and easier rail cabling.',
    '리프를 열 끝(또는 중간)의 네트워크 랙에 모으는 방식. 노드 케이블(MMF/AOC)은 길어지지만 스위치 수가 줄고 레일 케이블링이 쉽다.',
    { related: ['tor', 'leaf', 'rail-optimized'], aliases: ['mor', 'end-of-row', 'middle-of-row', 'mid-row'], domain: 'network' }),
  t('spine-placement', 'Spine placement (distributed / central-end / central-center / separate room)', '스파인 배치 (분산 / 홀 끝 / 홀 중앙 / 별도 실)',
    'Where spines and cores live: distributed per pod, in a central row at the end of the hall (phased growth), in the centre (single build, shortest worst-case fibre), or in a separate MMR.',
    '스파인·코어의 위치: 포드마다 분산, 홀 끝 중앙열(단계별 증설), 홀 중앙(일괄 구축, 최악 광 경로 최소), 별도 MMR.',
    { long: { en: 'A common pattern puts leaves, management and storage in a support row next to each SU (30–50 m links) and centralises spine/core between compute halls within single-mode reach (about 500 m). For a single hall the centre minimises the maximum fibre length; the end keeps containment runs uninterrupted and suits phased growth.', ko: '흔한 배치는 리프·관리·스토리지를 각 SU 옆 지원 열(30–50 m 링크)에 두고 스파인·코어를 컴퓨트 홀 사이 단일모드 도달 거리(약 500 m) 안에 모으는 것이다. 단일 홀에서는 중앙이 최대 광 경로를 최소화하고, 홀 끝은 컨테인먼트 열을 끊지 않아 단계별 증설에 유리하다.' }, related: ['spine', 'mmr', 'cin', 'growth'], sources: [S.refDesign, S.superpod], domain: 'layout' }),
  t('growth', 'Growth pattern (phased / single-build)', '증설 방식 (단계별 / 일괄 구축)',
    'Phased = capacity added wave by wave (spine row at the hall end); single-build = the whole hall is commissioned at once (spine row in the centre).',
    '단계별 = 웨이브마다 용량 추가(스파인 열은 홀 끝), 일괄 구축 = 홀 전체를 한 번에 커미셔닝(스파인 열은 홀 중앙).',
    { related: ['spine-placement', 'wave'], domain: 'layout' }),
  t('tiers', '2-tier vs 3-tier fabric', '2계층 vs 3계층 패브릭',
    'Leaf-spine (2-tier) scales to k²/2 endpoints with k-port switches (e.g. 2,048 at k = 64); beyond that a core tier gives k³/4 (65,536) at the cost of one more hop and more optics.',
    '리프-스파인(2계층)은 k포트 스위치로 k²/2 엔드포인트까지(k = 64면 2,048). 그 이상은 코어 계층을 더해 k³/4(65,536)까지, 대신 홉 1개와 광모듈이 늘어난다.',
    { related: ['radix', 'core', 'leaf-spine'], aliases: ['2-tier', '3-tier', 'two-tier', 'three-tier'], domain: 'network' }),
  t('leaf-spine', 'Leaf-spine', '리프-스파인',
    'Two-tier folded Clos: every leaf connects to every spine; any two endpoints are at most 3 switch hops apart.',
    '2계층 접힌 Clos. 모든 리프가 모든 스파인에 연결되며 임의의 두 엔드포인트는 최대 3 스위치 홉.',
    { related: ['fat-tree', 'tiers'], aliases: ['leaf spine', 'spine-leaf'], domain: 'network' }),
  t('radix', 'Switch radix', '스위치 radix',
    'Number of usable ports per switch at the fabric speed (e.g. 64 × 800G, or 128 × 400G with breakout). Radix sets how many endpoints each tier can reach.',
    '패브릭 속도에서 스위치당 사용 가능한 포트 수(예: 64 × 800G, 브레이크아웃 시 128 × 400G). radix가 계층별 도달 가능한 엔드포인트 수를 결정한다.',
    { related: ['tiers', 'breakout', 'oversubscription'], domain: 'network' }),
  t('breakout', 'Port breakout', '포트 브레이크아웃',
    'Splitting one high-speed switch port into several lower-speed logical ports (800G OSFP → 2 × 400G) with a breakout cable or transceiver.',
    '고속 스위치 포트 하나를 브레이크아웃 케이블·광모듈로 저속 논리 포트 여러 개(800G OSFP → 2 × 400G)로 나누는 것.',
    { related: ['radix', 'osfp', 'dr8'], domain: 'network' }),
  t('ecmp', 'ECMP (Equal-Cost Multi-Path)', 'ECMP (등가 다중 경로)',
    'Spreading flows across all equal-cost uplinks by hashing packet headers. Elephant flows hash-collide, which is why effective fabric throughput is 60–95 % of capacity unless adaptive routing or packet spraying is used.',
    '패킷 헤더 해시로 흐름을 등가 업링크들에 분산하는 방식. 큰 흐름끼리 해시 충돌이 나서 적응 라우팅·패킷 스프레이 없이는 실효 처리량이 용량의 60–95 %에 머문다.',
    { related: ['adaptive-routing', 'oversubscription', 'ebgp'], sources: [S.amdRd, S.drivenets], domain: 'network' }),
  t('adaptive-routing', 'Adaptive routing / packet spraying', '적응 라우팅 / 패킷 스프레이',
    'Per-packet (not per-flow) load balancing across uplinks with reordering handled at the NIC (Spectrum-X, UEC) — recovers most of the ECMP loss.',
    '흐름 단위가 아닌 패킷 단위로 업링크를 분산하고 NIC에서 순서를 복원하는 방식(Spectrum-X, UEC). ECMP 손실 대부분을 회복한다.',
    { related: ['ecmp', 'spectrum-x', 'uec'], domain: 'network' }),
  t('ebgp', 'eBGP unnumbered', 'eBGP unnumbered',
    'Leaf-spine routing with one BGP session per link using IPv6 link-local next hops (RFC 5549) — no /31 addressing on fabric links; each switch is its own AS.',
    '링크마다 BGP 세션을 두되 IPv6 링크로컬 넥스트홉(RFC 5549)을 쓰는 리프-스파인 라우팅. 패브릭 링크에 /31 주소가 필요 없고 스위치마다 AS를 갖는다.',
    { related: ['l3-fabric', 'ecmp', 'evpn'], sources: [S.amdRd], aliases: ['bgp unnumbered', 'ebgp'], domain: 'network' }),
  t('l3-fabric', 'L2 vs L3 fabric', 'L2 vs L3 패브릭',
    'L2 (VLAN / MLAG) keeps one broadcast domain and simple addressing but does not scale past a few thousand ports; L3 (eBGP per link, ECMP) scales to any size and is the default beyond one pod or for multi-tenant sites.',
    'L2(VLAN/MLAG)는 하나의 브로드캐스트 도메인과 단순 주소 체계지만 수천 포트 이상으로 확장되지 않는다. L3(링크별 eBGP, ECMP)는 규모 제한이 없고 포드 1개 초과·멀티테넌트 환경의 기본.',
    { related: ['ebgp', 'evpn', 'ecmp'], aliases: ['l2', 'l3', 'l2 vs l3'], domain: 'network' }),
  t('evpn', 'EVPN-VXLAN', 'EVPN-VXLAN',
    'Overlay that carries L2 segments over an L3 fabric using VXLAN encapsulation and BGP EVPN for MAC/IP advertisement; used on front-end/tenant networks, not on the GPU back-end.',
    'VXLAN 캡슐화와 BGP EVPN(MAC/IP 광고)로 L3 패브릭 위에 L2 세그먼트를 얹는 오버레이. 프런트엔드/테넌트 망에 쓰고 GPU 백엔드에는 쓰지 않는다.',
    { related: ['l3-fabric', 'ebgp'], aliases: ['vxlan', 'evpn'], domain: 'network' }),
  t('ddc', 'DDC / NCP / NCF (Distributed Disaggregated Chassis)', 'DDC / NCP / NCF (분산 분해형 섀시)',
    'DriveNets-style scheduled fabric: NCP (Network Cloud Packet forwarder) = leaf with network + fabric ports, NCF (Network Cloud Fabric) = spine that only joins NCPs; cells are sprayed across all NCFs so the whole thing behaves as one big switch.',
    'DriveNets식 스케줄드 패브릭. NCP(Network Cloud Packet forwarder) = 네트워크·패브릭 포트를 가진 리프, NCF(Network Cloud Fabric) = NCP만 잇는 스파인. 셀을 모든 NCF에 뿌려 전체가 하나의 거대한 스위치처럼 동작한다.',
    { long: { en: 'AMD–DriveNets RA: 5300R NCP = Jericho3-AI, 18 × 800G network + 20 × 800G fabric ports (2 RU); 9300F NCF = 2 × Ramon3, 128 × 800G (6 RU). Ingress NCP stores packets in VOQs, requests credits from the egress NCP, fragments into cells and sprays them across every NCF; the egress NCP reassembles. For hop counting the fabric is one distributed switch.', ko: 'AMD–DriveNets RA: 5300R NCP = Jericho3-AI, 800G 네트워크 18 + 패브릭 20 포트(2 RU); 9300F NCF = Ramon3 × 2, 800G 128 포트(6 RU). 입구 NCP가 패킷을 VOQ에 저장하고 출구 NCP에 크레딧을 요청, 셀로 쪼개 모든 NCF에 뿌리며 출구 NCP가 재조립. 홉 계산에서는 패브릭 전체가 분산 스위치 1대.' }, related: ['voq', 'cell-spray', 'spine'], sources: [S.drivenets], aliases: ['ncp', 'ncf', 'nce', 'distributed disaggregated chassis', 'scheduled fabric'], domain: 'network' }),
  t('voq', 'VOQ (Virtual Output Queue)', 'VOQ (가상 출력 큐)',
    'Ingress queue per egress port (and class) so a blocked output never stalls traffic for other outputs (no head-of-line blocking); the basis of credit-scheduled fabrics.',
    '출구 포트(및 클래스)별 입구 큐. 막힌 출력이 다른 출력 트래픽을 멈추지 않게(HOL 블로킹 제거) 하며 크레딧 스케줄드 패브릭의 기반.',
    { related: ['ddc', 'cell-spray'], sources: [S.drivenets], domain: 'network' }),
  t('cell-spray', 'Cell spraying', '셀 스프레이',
    'Fragmenting packets into fixed-size cells and distributing them over all fabric links; perfect load balance without flow hashing.',
    '패킷을 고정 크기 셀로 쪼개 모든 패브릭 링크에 분산하는 것. 흐름 해시 없이 완벽한 부하 분산.',
    { related: ['ddc', 'voq', 'adaptive-routing'], sources: [S.drivenets], domain: 'network' }),
  t('pxn', 'PXN (PCI × NVLink)', 'PXN (PCI × NVLink)',
    'NCCL path that moves data over NVLink to the GPU whose NIC sits on the destination rail, so inter-node traffic stays on one rail-optimized leaf hop.',
    '목적지 레일의 NIC를 가진 GPU로 NVLink를 통해 데이터를 옮겨, 노드 간 트래픽이 레일 최적화 리프 1홉에 머물게 하는 NCCL 경로.',
    { related: ['rail-optimized', 'nvlink', 'nccl'], sources: [S.nccl], domain: 'network' }),
  t('dcqcn', 'DCQCN', 'DCQCN',
    'RoCEv2 congestion control: switches mark ECN, the receiver sends CNPs, the sender NIC reduces rate; PFC is the last-resort backstop.',
    'RoCEv2 혼잡 제어. 스위치가 ECN 표시 → 수신측이 CNP 송신 → 송신 NIC가 속도 감소. PFC는 최후의 안전장치.',
    { long: { en: 'Typical fabric config (AMD RoCE guide): ECN marking thresholds per queue, DSCP 26 for RoCE traffic and 48 for CNP, PFC on one lossless priority (3) only, MTU 4096/9000, rp_filter=2 with per-NIC routing tables for multi-rail hosts.', ko: '대표 설정(AMD RoCE 가이드): 큐별 ECN 마킹 임계값, RoCE 트래픽 DSCP 26·CNP 48, PFC는 무손실 우선순위 1개(3)에만, MTU 4096/9000, 멀티레일 호스트는 rp_filter=2 + NIC별 라우팅 테이블.' }, related: ['pfc', 'ecn', 'cnp', 'dscp', 'roce'], sources: [S.ieee, S.amdRd], domain: 'network' }),
  t('pfc', 'PFC (Priority Flow Control)', 'PFC (우선순위 흐름 제어)',
    'IEEE 802.1Qbb per-priority pause that makes a queue lossless; needed by RoCE but risks head-of-line blocking and pause storms, so it is limited to one priority.',
    'IEEE 802.1Qbb 우선순위별 일시정지로 큐를 무손실로 만드는 기능. RoCE에 필요하지만 HOL 블로킹·pause storm 위험이 있어 우선순위 1개에만 적용.',
    { related: ['dcqcn', 'ecn', 'roce'], sources: [S.ieee], domain: 'network' }),
  t('ecn', 'ECN (Explicit Congestion Notification)', 'ECN (명시적 혼잡 통지)',
    'RFC 3168 IP-header marking set by a switch whose queue exceeds a threshold; the receiver reflects it (CNP) so senders slow down before drops.',
    '큐가 임계값을 넘은 스위치가 IP 헤더에 찍는 RFC 3168 표시. 수신측이 이를 되돌려(CNP) 드롭 전에 송신 속도를 낮춘다.',
    { related: ['dcqcn', 'cnp'], sources: [S.ieee], domain: 'network' }),
  t('cnp', 'CNP (Congestion Notification Packet)', 'CNP (혼잡 통지 패킷)',
    'RoCEv2 packet sent by the receiver to the sender when ECN-marked data arrives; carried at a high-priority DSCP so it is never delayed.',
    'ECN 표시된 데이터가 도착하면 수신측이 송신측에 보내는 RoCEv2 패킷. 지연되지 않도록 높은 DSCP로 전송.',
    { related: ['dcqcn', 'ecn', 'dscp'], sources: [S.ieee], domain: 'network' }),
  t('dscp', 'DSCP (Differentiated Services Code Point)', 'DSCP (차등 서비스 코드 포인트)',
    '6-bit IP header field mapped to switch queues/priorities; RoCE designs assign one DSCP to RDMA traffic (lossless queue) and another to CNPs.',
    '스위치 큐·우선순위에 매핑되는 6비트 IP 헤더 필드. RoCE 설계는 RDMA 트래픽(무손실 큐)과 CNP에 각각 다른 DSCP를 배정.',
    { related: ['dcqcn', 'pfc'], domain: 'network' }),
  t('roce', 'RoCEv2', 'RoCEv2',
    'RDMA over Converged Ethernet v2: RDMA verbs carried in UDP/IP, routable across an L3 fabric; needs lossless (PFC) or well-tuned congestion control.',
    'RDMA over Converged Ethernet v2. RDMA 동사를 UDP/IP에 실어 L3 패브릭에서 라우팅. 무손실(PFC) 또는 잘 조정된 혼잡 제어가 필요.',
    { related: ['dcqcn', 'infiniband', 'spectrum-x'], aliases: ['roce', 'rocev2'], domain: 'network' }),
  t('infiniband', 'InfiniBand (NDR / XDR)', '인피니밴드 (NDR / XDR)',
    'Lossless, credit-based fabric with in-network computing (SHARP); NDR = 400 Gb/s per port (Quantum-2), XDR = 800 Gb/s (Quantum-X800).',
    '크레딧 기반 무손실 패브릭, 인네트워크 컴퓨팅(SHARP) 지원. NDR = 포트당 400 Gb/s(Quantum-2), XDR = 800 Gb/s(Quantum-X800).',
    { related: ['roce', 'spectrum-x', 'sharp'], aliases: ['ib', 'ndr', 'xdr'], domain: 'network' }),
  t('spectrum-x', 'Spectrum-X', 'Spectrum-X',
    'NVIDIA Ethernet AI fabric (Spectrum-4/5 switches + BlueField/ConnectX SuperNICs) adding adaptive routing, packet reordering and telemetry-based congestion control to RoCE.',
    'NVIDIA 이더넷 AI 패브릭(Spectrum-4/5 스위치 + BlueField/ConnectX SuperNIC). RoCE에 적응 라우팅·패킷 재정렬·텔레메트리 기반 혼잡 제어를 더한다.',
    { related: ['roce', 'adaptive-routing', 'infiniband'], aliases: ['spectrumx'], domain: 'network' }),
  t('uec', 'Ultra Ethernet (UEC)', '울트라 이더넷 (UEC)',
    'Consortium transport for AI/HPC over Ethernet: multipath packet spraying, selective retransmit and modern congestion control without PFC.',
    'AI/HPC용 이더넷 전송 컨소시엄 규격. 멀티패스 패킷 스프레이·선택적 재전송·PFC 없는 현대적 혼잡 제어.',
    { related: ['roce', 'adaptive-routing'], sources: [S.ueC], aliases: ['ultra ethernet'], domain: 'network' }),
  t('sharp', 'SHARP (in-network reduction)', 'SHARP (인네트워크 리덕션)',
    'InfiniBand switches perform all-reduce arithmetic in the fabric, cutting data crossing the network roughly in half for large collectives.',
    '인피니밴드 스위치가 패브릭 안에서 all-reduce 연산을 수행해 큰 집합 통신의 네트워크 통과 데이터를 절반 가까이 줄인다.',
    { related: ['infiniband', 'all-reduce'], domain: 'network' }),
  t('busbw', 'busbw / algbw', 'busbw / algbw',
    'nccl-tests metrics: algbw = data size ÷ time as seen by the application; busbw rescales it by the collective\'s traffic factor (2(n−1)/n for all-reduce) so it is comparable to link speed.',
    'nccl-tests 지표. algbw = 애플리케이션 관점 데이터 크기 ÷ 시간, busbw = 집합 통신의 트래픽 계수(all-reduce는 2(n−1)/n)로 보정해 링크 속도와 비교 가능하게 한 값.',
    { long: { en: 'Acceptance thresholds used in the AMD guides: all_reduce busbw ≥ 304–350 GB/s on a 400G × 8-rail node, all-to-all ≥ ~0.85 × NIC line rate. AIDC Studio\'s commEfficiency compares the chosen fabric against ideal non-blocking IB XDR.', ko: 'AMD 가이드의 인수 기준: 400G × 8레일 노드에서 all_reduce busbw ≥ 304–350 GB/s, all-to-all ≥ NIC 선속도의 약 0.85배. AIDC Studio의 commEfficiency는 선택 패브릭을 이상적 논블로킹 IB XDR과 비교한다.' }, related: ['all-reduce', 'nccl', 'goodput'], sources: [S.nccl, S.amdRd], aliases: ['algbw', 'bus bandwidth'], domain: 'workload' }),
  t('nccl', 'NCCL / RCCL', 'NCCL / RCCL',
    'NVIDIA / AMD collective communication libraries (all-reduce, all-gather, reduce-scatter, all-to-all) that map GPU collectives onto NVLink/xGMI and the scale-out fabric.',
    'NVIDIA/AMD 집합 통신 라이브러리(all-reduce·all-gather·reduce-scatter·all-to-all). GPU 집합 통신을 NVLink/xGMI와 스케일아웃 패브릭에 매핑.',
    { related: ['busbw', 'pxn', 'all-reduce'], aliases: ['rccl'], domain: 'workload' }),
  t('all-reduce', 'All-reduce / all-to-all', 'All-reduce / all-to-all',
    'All-reduce sums gradients across data-parallel replicas (bandwidth ∝ 2(n−1)/n × model size); all-to-all exchanges expert tokens in MoE models and stresses bisection bandwidth.',
    'All-reduce는 데이터 병렬 복제본 간 그래디언트 합산(대역 ∝ 2(n−1)/n × 모델 크기), all-to-all은 MoE 모델의 전문가 토큰 교환으로 이분 대역폭을 압박한다.',
    { related: ['busbw', 'bisection', 'moe'], aliases: ['all-to-all', 'allreduce', 'alltoall'], domain: 'workload' }),
  t('scale-out', 'Scale-out (east-west) network', '스케일아웃 (동서) 네트워크',
    'GPU-to-GPU fabric across nodes/racks (IB or RoCE), 1 NIC per GPU at 400–800G; sized non-blocking. Distinct from the front-end (north-south), storage and OOB networks.',
    '노드·랙을 넘는 GPU 간 패브릭(IB 또는 RoCE), GPU당 NIC 1개 400–800G, 논블로킹으로 설계. 프런트엔드(남북)·스토리지·OOB 망과 구분.',
    { related: ['scale-up', 'frontend', 'oob', 'cin'], aliases: ['back-end network', 'east-west', 'backend'], domain: 'network' }),
  t('scale-up', 'Scale-up domain (NVLink / UALink / xGMI)', '스케일업 도메인 (NVLink / UALink / xGMI)',
    'GPUs sharing a memory-semantic interconnect inside a node or rack (NVL72 = 72 GPUs, HGX = 8, MI355X = 8 via xGMI, Helios = 72 via UALink). Tensor/expert parallelism stays inside it.',
    '노드·랙 안에서 메모리 시맨틱 인터커넥트를 공유하는 GPU 집합(NVL72 = 72, HGX = 8, MI355X = xGMI 8, Helios = UALink 72). 텐서/전문가 병렬은 이 안에 머문다.',
    { related: ['nvlink', 'ualink', 'xgmi', 'scale-out'], aliases: ['scale up', 'nvlink domain'], domain: 'network' }),
  t('nvlink', 'NVLink / NVSwitch', 'NVLink / NVSwitch',
    'NVIDIA GPU-to-GPU link (1.8 TB/s per GPU on Blackwell) switched by NVSwitch trays into a 72-GPU rack-scale domain (NVL72).',
    'NVIDIA GPU 간 링크(Blackwell에서 GPU당 1.8 TB/s). NVSwitch 트레이가 72 GPU 랙 규모 도메인(NVL72)으로 스위칭.',
    { related: ['scale-up', 'nvl72', 'pxn'], aliases: ['nvswitch'], domain: 'network' }),
  t('ualink', 'UALink', 'UALink',
    'Open scale-up interconnect (UALink Consortium 1.0, 200 Gb/s per lane) for up to 1,024 accelerators; AMD Helios uses it for the 72-GPU rack domain.',
    '개방형 스케일업 인터커넥트(UALink 컨소시엄 1.0, 레인당 200 Gb/s), 최대 1,024 가속기. AMD Helios가 72 GPU 랙 도메인에 사용.',
    { related: ['scale-up', 'xgmi', 'helios'], sources: [S.ualink], domain: 'network' }),
  t('xgmi', 'xGMI (Infinity Fabric)', 'xGMI (Infinity Fabric)',
    'AMD inter-GPU link used inside 8-OAM MI300X/MI325X/MI355X baseboards (UBB); all-to-all within the node.',
    'AMD 8-OAM MI300X/MI325X/MI355X 베이스보드(UBB) 안의 GPU 간 링크. 노드 안 all-to-all.',
    { related: ['scale-up', 'oam'], aliases: ['infinity fabric'], domain: 'network' }),
  t('nvl72', 'GB200 / GB300 NVL72', 'GB200 / GB300 NVL72',
    'NVIDIA rack-scale system: 18 compute trays (72 GPUs, 36 Grace CPUs), 9 NVSwitch trays, 8 power shelves, direct liquid cooling; 120–142 kW nameplate (GB300).',
    'NVIDIA 랙 규모 시스템: 컴퓨트 트레이 18(GPU 72, Grace CPU 36), NVSwitch 트레이 9, 파워셸프 8, 직접 액랭. 명판 120–142 kW(GB300).',
    { related: ['rcu', 'nvlink', 'edpp'], sources: [S.refDesign], aliases: ['nvl72', 'gb300', 'gb200'], domain: 'layout' }),
  t('helios', 'AMD Helios', 'AMD Helios',
    'AMD rack-scale platform (announced 2026): double-wide ORW rack, 72 × MI455X, UALink scale-up, Pensando NICs, direct liquid cooling.',
    'AMD 랙 규모 플랫폼(2026 발표): 더블와이드 ORW 랙, MI455X 72기, UALink 스케일업, Pensando NIC, 직접 액랭.',
    { related: ['orv3', 'ualink', 'oam'], aliases: ['mi455x'], domain: 'layout' }),
  t('frontend', 'Front-end (north-south) network', '프런트엔드 (남북) 네트워크',
    'Network for user/API traffic, storage access (when converged) and orchestration; typically 2 × 200–400G per node with 2:1–4:1 oversubscription.',
    '사용자/API 트래픽, 스토리지 접근(컨버지드 시), 오케스트레이션용 망. 보통 노드당 2 × 200–400G, 오버서브 2:1–4:1.',
    { related: ['scale-out', 'storage-network', 'oob'], aliases: ['north-south', 'in-band'], domain: 'network' }),
  t('storage-network', 'Storage network', '스토리지 네트워크',
    'Dedicated or converged fabric between GPU nodes and the parallel file system; sized from 9–17 GB/s per GPU (12 GB/s default).',
    'GPU 노드와 병렬 파일시스템 사이의 전용 또는 컨버지드 패브릭. GPU당 9–17 GB/s(기본 12 GB/s)로 산정.',
    { related: ['frontend', 'oversubscription'], sources: [S.refDesign, S.superpod], domain: 'network' }),
  t('oob', 'OOB (out-of-band) / BMC network', 'OOB (대역외) / BMC 네트워크',
    '1 GbE management network reaching every BMC, switch console and PDU independently of the production fabrics.',
    '모든 BMC·스위치 콘솔·PDU에 운영 패브릭과 독립적으로 닿는 1 GbE 관리망.',
    { related: ['frontend', 'control-plane'], aliases: ['out-of-band', 'bmc'], domain: 'network' }),
  t('control-plane', 'Centralized control plane', '중앙 집중 컨트롤 플레인',
    'Management, scheduling (Slurm / Kubernetes), telemetry, provisioning and fabric managers (UFM / NetQ) run on a separate management cluster on the OOB and in-band networks.',
    '관리·스케줄링(Slurm/Kubernetes)·텔레메트리·프로비저닝·패브릭 매니저(UFM/NetQ)를 OOB·인밴드 망 위의 별도 관리 클러스터에서 운영하는 구조.',
    { related: ['oob', 'slurm'], sources: [S.amdDc], domain: 'ops' }),
  t('slurm', 'Slurm topology.conf', 'Slurm topology.conf',
    'Scheduler file describing which nodes hang off which switches so jobs are packed onto a minimal set of leaves; generated from the planned fabric.',
    '어떤 노드가 어떤 스위치 아래에 있는지 기술해 잡을 최소 리프 집합에 배치하게 하는 스케줄러 파일. 계획된 패브릭에서 생성.',
    { related: ['control-plane', 'rail-optimized'], domain: 'ops' }),

  // ───────────── Workload metrics ─────────────
  t('mfu', 'MFU (Model FLOPs Utilization)', 'MFU (모델 FLOPs 활용률)',
    'Achieved model FLOP/s ÷ theoretical peak (6·N·D FLOPs per token for a dense transformer). 35–50 % is typical for large pretraining runs.',
    '달성한 모델 FLOP/s ÷ 이론 피크(밀집 트랜스포머는 토큰당 6·N·D FLOPs). 대규모 사전학습에서 35–50 %가 일반적.',
    { related: ['goodput', 'busbw', 'tokens-per-sec'], sources: [S.mlperf], domain: 'workload' }),
  t('goodput', 'Goodput (training)', 'Goodput (학습)',
    'Useful training progress ÷ wall time after checkpoint overhead, restarts and interruptions: 1 − δ/τ − (τ/2 + δ + R)/MTBI in AIDC Studio\'s model.',
    '체크포인트 오버헤드·재시작·중단을 뺀 유효 학습 진척 ÷ 실시간. AIDC Studio 모델: 1 − δ/τ − (τ/2 + δ + R)/MTBI.',
    { related: ['mfu', 'mtbi', 'checkpoint'], sources: [S.mlperf], domain: 'workload' }),
  t('mtbi', 'MTBI / MTBF (Mean Time Between Interruptions)', 'MTBI / MTBF (평균 중단 간격)',
    'Average wall time between job-stopping failures for the whole cluster; scales inversely with GPU count and drives checkpoint interval τ.',
    '클러스터 전체에서 잡을 멈추는 장애 사이의 평균 시간. GPU 수에 반비례하며 체크포인트 간격 τ를 결정.',
    { related: ['goodput', 'checkpoint'], aliases: ['mtbf'], domain: 'workload' }),
  t('checkpoint', 'Checkpoint interval (τ) / overhead (δ)', '체크포인트 간격 (τ) / 오버헤드 (δ)',
    'How often model state is saved and how long each save stalls training; optimal τ ≈ √(2·δ·MTBI) (Young–Daly).',
    '모델 상태를 저장하는 주기와 저장 1회가 학습을 멈추는 시간. 최적 τ ≈ √(2·δ·MTBI)(Young–Daly).',
    { related: ['goodput', 'mtbi'], domain: 'workload' }),
  t('tokens-per-sec', 'Tokens/s · tokens/kWh', 'Tokens/s · tokens/kWh',
    'Throughput and energy efficiency of a training or serving deployment; tokens/kWh includes PUE so it is a facility-level KPI.',
    '학습·서빙 배치의 처리량과 에너지 효율. tokens/kWh는 PUE를 포함한 시설 수준 KPI.',
    { related: ['mfu', 'pue'], domain: 'workload' }),
  t('ttft', 'TTFT (Time To First Token)', 'TTFT (첫 토큰 시간)',
    'Latency from request arrival to the first generated token; dominated by the prefill phase (compute-bound) and queueing.',
    '요청 도착부터 첫 생성 토큰까지의 지연. prefill 단계(연산 한계)와 대기열이 지배.',
    { related: ['tpot', 'prefill-decode', 'kv-cache'], domain: 'workload' }),
  t('tpot', 'TPOT / ITL (Time Per Output Token)', 'TPOT / ITL (토큰당 출력 시간)',
    'Average time between successive output tokens during decode (also inter-token latency); memory-bandwidth-bound: batch × model bytes ÷ HBM bandwidth.',
    'decode 중 연속 출력 토큰 사이의 평균 시간(inter-token latency). 메모리 대역 한계: 배치 × 모델 바이트 ÷ HBM 대역폭.',
    { related: ['ttft', 'kv-cache', 'hbm'], aliases: ['itl', 'inter-token latency'], domain: 'workload' }),
  t('kv-cache', 'KV cache', 'KV 캐시',
    'Per-request attention key/value tensors kept in GPU memory during decode: 2 × layers × kv_heads × head_dim × bytes per token; it caps the decode batch size.',
    'decode 동안 GPU 메모리에 유지되는 요청별 어텐션 키/값 텐서. 토큰당 2 × 층 × kv_heads × head_dim × 바이트로 decode 배치 크기를 제한.',
    { related: ['tpot', 'prefill-decode', 'hbm'], domain: 'workload' }),
  t('prefill-decode', 'P/D disaggregation (prefill / decode)', 'P/D 분리 (prefill / decode)',
    'Serving pattern that runs compute-bound prefill and bandwidth-bound decode on separate GPU pools, transferring the KV cache between them over the fabric.',
    '연산 한계인 prefill과 대역 한계인 decode를 별도 GPU 풀에서 실행하고 KV 캐시를 패브릭으로 전달하는 서빙 방식.',
    { related: ['kv-cache', 'ttft', 'tpot'], aliases: ['disaggregated serving', 'prefill', 'decode'], domain: 'workload' }),
  t('hbm', 'HBM bandwidth', 'HBM 대역폭',
    'High-bandwidth memory throughput per GPU (GB300 8 TB/s HBM3e, MI355X 8 TB/s, Vera Rubin ~13 TB/s HBM4); the ceiling for decode tokens/s.',
    'GPU당 고대역폭 메모리 처리량(GB300 HBM3e 8 TB/s, MI355X 8 TB/s, Vera Rubin HBM4 약 13 TB/s). decode tokens/s의 상한.',
    { related: ['tpot', 'kv-cache'], domain: 'workload' }),
  t('moe', 'MoE (Mixture of Experts)', 'MoE (전문가 혼합)',
    'Model with many expert FFNs of which only top-k are active per token; expert parallelism turns the fabric load into all-to-all exchanges.',
    '여러 전문가 FFN 중 토큰당 top-k만 활성화되는 모델. 전문가 병렬은 패브릭 부하를 all-to-all 교환으로 바꾼다.',
    { related: ['all-reduce', 'parallelism'], domain: 'workload' }),
  t('parallelism', 'TP / PP / DP / EP / CP', 'TP / PP / DP / EP / CP',
    'Tensor, pipeline, data, expert and context parallelism — how a model is split across GPUs; TP stays inside the scale-up domain, DP/EP cross the scale-out fabric.',
    '텐서·파이프라인·데이터·전문가·컨텍스트 병렬 — 모델을 GPU에 나누는 방법. TP는 스케일업 도메인 안, DP/EP는 스케일아웃 패브릭을 건넌다.',
    { related: ['scale-up', 'scale-out', 'moe'], aliases: ['tp', 'pp', 'dp', 'ep', 'cp', 'tensor parallel', 'pipeline parallel', 'data parallel'], domain: 'workload' }),

  // ───────────── Optics & cabling ─────────────
  t('dac', 'DAC (Direct Attach Copper)', 'DAC (직결 구리 케이블)',
    'Passive twinax cable with integrated connectors, ≤ 2–3 m at 800G; lowest cost and power (0 W), used for ToR and in-rack links.',
    '커넥터 일체형 수동 트윈액스 케이블, 800G에서 2–3 m 이하. 최저 비용·전력(0 W). ToR·랙 내 링크용.',
    { related: ['acc', 'aec', 'aoc', 'tor'], domain: 'optics' }),
  t('acc', 'ACC (Active Copper Cable)', 'ACC (능동 구리 케이블)',
    'Copper cable with linear signal boosters (no retimer), reaching ~3–5 m at 800G at a fraction of an AEC\'s power.',
    '선형 신호 증폭기(리타이머 없음)를 넣은 구리 케이블. 800G에서 약 3–5 m, AEC보다 낮은 전력.',
    { related: ['dac', 'aec'], domain: 'optics' }),
  t('aec', 'AEC (Active Electrical Cable)', 'AEC (능동 전기 케이블)',
    'Copper cable with retimers in each end, ~5–7 m at 800G, a few watts per end; bridges the gap between DAC and optics for row-level links.',
    '양단에 리타이머를 넣은 구리 케이블. 800G에서 약 5–7 m, 단당 수 W. 열 단위 링크에서 DAC와 광 사이를 메운다.',
    { related: ['dac', 'acc', 'aoc'], domain: 'optics' }),
  t('aoc', 'AOC (Active Optical Cable)', 'AOC (능동 광 케이블)',
    'Fibre cable with transceivers permanently attached at both ends; ≤ 100 m, cheaper than pluggable optics + patch cords but not field-repairable.',
    '양단에 광모듈이 고정된 광 케이블. 100 m 이하, 플러그형 광모듈 + 패치코드보다 싸지만 현장 수리 불가.',
    { related: ['mmf', 'sr8', 'aec'], domain: 'optics' }),
  t('sr8', 'SR8 (800G multimode)', 'SR8 (800G 멀티모드)',
    '8 × 100G lanes over 16 OM4 fibres (MPO-16), ≤ 50 m at 800G (30 m recommended by SuperPOD for node→leaf); the standard in-pod optic.',
    'OM4 16가닥(MPO-16)에 100G × 8 레인, 800G에서 50 m 이하(SuperPOD는 노드→리프 30 m 권장). 포드 내 표준 광모듈.',
    { related: ['dr8', 'mmf', 'mpo'], aliases: ['sr4', 'sr8'], domain: 'optics' }),
  t('dr8', 'DR8 / FR8 (800G single-mode)', 'DR8 / FR8 (800G 단일모드)',
    'DR8: 8 × 100G over 16 SMF fibres (MPO-16), 500 m; FR8/FR4: WDM on duplex fibre, 2 km. Leaf↔spine and spine↔core links across the hall.',
    'DR8: SMF 16가닥(MPO-16)에 100G × 8, 500 m. FR8/FR4: 듀플렉스 광섬유 WDM, 2 km. 홀을 가로지르는 리프↔스파인·스파인↔코어 링크.',
    { related: ['sr8', 'smf', 'mpo', 'cin'], aliases: ['dr4', 'fr4', 'fr8', 'dr8'], domain: 'optics' }),
  t('mmf', 'MMF (OM4 / OM5)', 'MMF (OM4 / OM5)',
    'Multimode fibre (50 µm core) for VCSEL-based SR optics; OM4 supports 100G/lane to 100 m (SR4) and 50 m at 800G (SR8).',
    'VCSEL 기반 SR 광모듈용 멀티모드 광섬유(코어 50 µm). OM4는 레인당 100G 기준 100 m(SR4), 800G 50 m(SR8).',
    { related: ['smf', 'sr8', 'aoc'], aliases: ['om4', 'om5', 'multimode'], domain: 'optics' }),
  t('smf', 'SMF (OS2)', 'SMF (OS2)',
    'Single-mode fibre (9 µm core) for DR/FR optics; reach 500 m–2 km; used for every link that leaves the pod.',
    'DR/FR 광모듈용 단일모드 광섬유(코어 9 µm). 500 m–2 km. 포드를 벗어나는 모든 링크에 사용.',
    { related: ['mmf', 'dr8'], aliases: ['os2', 'single-mode', 'singlemode'], domain: 'optics' }),
  t('lpo', 'LPO (Linear Pluggable Optics)', 'LPO (선형 플러그형 광모듈)',
    'Pluggable optics without DSP/retimer — the switch ASIC drives the laser directly; ~50 % lower power and latency than DSP optics, short reach only.',
    'DSP/리타이머가 없는 플러그형 광모듈 — 스위치 ASIC이 레이저를 직접 구동. DSP 광모듈보다 전력·지연 약 50 % 감소, 단거리 전용.',
    { related: ['cpo', 'sr8'], sources: [S.ieeeEth], domain: 'optics' }),
  t('cpo', 'CPO (Co-Packaged Optics)', 'CPO (공동 패키지 광)',
    'Optical engines mounted on the switch ASIC package with external laser sources; removes pluggable optics power (Quantum-X / Spectrum-X Photonics).',
    '스위치 ASIC 패키지에 광 엔진을 실장하고 외부 레이저를 쓰는 방식. 플러그형 광모듈 전력을 제거(Quantum-X / Spectrum-X Photonics).',
    { related: ['lpo'], domain: 'optics' }),
  t('mpo', 'MPO / MTP connector', 'MPO / MTP 커넥터',
    'Multi-fibre push-on connector (8/12/16 fibres) used by parallel optics (SR8/DR8); polarity (Type A/B) and pinning must match end to end.',
    '병렬 광모듈(SR8/DR8)용 다심 푸시온 커넥터(8/12/16심). 극성(Type A/B)과 핀 구성이 양단에서 일치해야 한다.',
    { related: ['sr8', 'dr8', 'mmr'], aliases: ['mtp'], domain: 'optics' }),
  t('osfp', 'OSFP / QSFP112 / QSFP-DD', 'OSFP / QSFP112 / QSFP-DD',
    'Pluggable form factors for 800G (OSFP, QSFP-DD) and 400G (QSFP112); OSFP has more thermal headroom (up to ~30 W) and is used by Quantum-X800 / Spectrum-4.',
    '800G(OSFP, QSFP-DD)·400G(QSFP112) 플러그형 폼팩터. OSFP는 열 여유가 커서(최대 약 30 W) Quantum-X800 / Spectrum-4가 사용.',
    { related: ['sr8', 'dr8', 'breakout'], aliases: ['qsfp112', 'qsfp-dd', 'qsfp'], domain: 'optics' }),
  t('mmr', 'MMR / MDA / IDA / HDA / EDA', 'MMR / MDA / IDA / HDA / EDA',
    'TIA-942 spaces: Main (or Meet-Me) Distribution Area for cores/carriers, Intermediate DA, Horizontal DA (row / pod leaves), Equipment DA (racks). A separate MMR for spines is optional in AIDC Studio (default off).',
    'TIA-942 공간 구분: MDA(코어·통신사 인입)/MMR, IDA(중간), HDA(열·포드 리프), EDA(장비 랙). 스파인용 별도 MMR은 AIDC Studio에서 옵션(기본 off).',
    { related: ['spine-placement', 'tray'], sources: [S.tia], aliases: ['mda', 'ida', 'hda', 'eda', 'idf', 'mdf'], domain: 'layout' }),
  t('tray', 'Cable tray / fibre raceway / ladder', '케이블 트레이 / 광 레이스웨이 / 래더',
    'Overhead pathways for fibre (raceway, solid-bottom tray) and copper/power (ladder rack). Size from fill: N = (F/100)·A/((D/2)²·π) at 50 % fill; ≥ 7,400 mm² per SU at 3 mm cables.',
    '광(레이스웨이·바닥 있는 트레이)과 구리/전력(래더)용 오버헤드 경로. 충진율로 산정: N = (F/100)·A/((D/2)²·π), 충진 50 %. 3 mm 케이블 기준 SU당 7,400 mm² 이상.',
    { related: ['busway', 'mmr'], sources: [S.superpod], aliases: ['ladder', 'raceway', 'cable tray'], domain: 'layout' }),
  t('busway', 'Overhead busway / tap-off', '오버헤드 버스웨이 / 탭오프',
    'Enclosed busbar run above the rack row (A and B paths) with plug-in tap-off boxes feeding each rack\'s PDUs; replaces RPP whips and allows live adds.',
    '랙 열 위로 지나는 밀폐 버스바(A·B 경로)에 플러그인 탭오프 박스를 꽂아 각 랙 PDU에 급전. RPP 휩을 대체하고 활선 증설 가능.',
    { related: ['rpp', 'pdu'], sources: [S.amdDc], aliases: ['tap-off', 'tapoff', 'busbar'], domain: 'power' }),
  t('pdu', 'PDU / rPDU / power shelf', 'PDU / rPDU / 파워셸프',
    'Floor PDU (transformer + panels) feeds RPPs/busways; rack PDUs (rPDU) or 800 VDC power shelves (NVL72, Helios) feed the IT gear.',
    '바닥 PDU(변압기 + 패널)가 RPP/버스웨이에 급전, 랙 PDU(rPDU) 또는 800 VDC 파워셸프(NVL72, Helios)가 IT 장비에 급전.',
    { related: ['rpp', 'busway', '800vdc'], aliases: ['rpdu', 'power shelf'], domain: 'power' }),
  t('800vdc', '800 VDC distribution', '800 VDC 배전',
    'NVIDIA Vera Rubin-era rack power: ±400 V DC busbar fed by sidecar power racks, replacing per-rack AC PSUs; fewer conversions, thinner busbar.',
    'NVIDIA Vera Rubin 세대 랙 전력: 사이드카 파워 랙이 ±400 V DC 버스바에 급전, 랙별 AC PSU 대체. 변환 단계와 버스바 단면 감소.',
    { related: ['pdu', 'busway'], sources: [S.refDesign], domain: 'power' }),
  t('ups-topology', 'UPS redundancy (N / N+1 / 2N / DR / block)', 'UPS 이중화 (N / N+1 / 2N / DR / 블록)',
    'N = exact need; N+1 = one spare module; 2N = two independent systems each able to carry the full load (A/B); DR = distributed redundant (N+1 blocks with static switches); block-redundant = shared reserve block.',
    'N = 필요량, N+1 = 예비 1대, 2N = 각각 전체 부하를 감당하는 독립 계통 2개(A/B), DR = 분산 이중화(N+1 블록 + STS), 블록 이중화 = 공용 예비 블록.',
    { long: { en: 'Uptime Tier mapping (approx.): Tier II ≈ N+1 components, Tier III ≈ concurrently maintainable (N+1 with dual paths, one active), Tier IV ≈ fault tolerant (2N/2(N+1), both paths active). DECISIONS-v2 #5 sets Tier III / distributed redundant as the site default.', ko: 'Uptime Tier 대응(근사): Tier II ≈ N+1 구성요소, Tier III ≈ 동시 유지보수 가능(N+1 + 이중 경로 중 1개 활성), Tier IV ≈ 결함 허용(2N/2(N+1), 양 경로 활성). DECISIONS-v2 #5는 사이트 기본을 Tier III / 분산 이중화로 정함.' }, related: ['ups', 'tier', 'ats'], sources: [S.uptime], aliases: ['2n', 'n+1', 'distributed redundant', 'block redundant', 'redundancy'], domain: 'power' }),
  t('ups', 'UPS', 'UPS',
    'Uninterruptible power supply bridging the gap until generators take load (battery 5–10 min for IT; often only core network + mechanical for GPU halls with BESS).',
    '발전기가 부하를 받을 때까지의 공백을 메우는 무정전 전원(IT용 배터리 5–10분; BESS가 있는 GPU 홀에서는 코어 네트워크 + 기계 설비만 UPS인 경우가 많다).',
    { related: ['ups-topology', 'bess', 'generator'], domain: 'power' }),
  t('generator', 'Standby generator (N+1 / N+2)', '비상 발전기 (N+1 / N+2)',
    'Diesel/gas sets sized to the full facility load including mechanical; large sites commonly use N+2 with a 10-second start and ATS transfer.',
    '기계 설비를 포함한 전체 시설 부하로 산정한 디젤/가스 발전기. 대형 사이트는 흔히 N+2, 10초 기동, ATS 절체를 쓴다.',
    { related: ['ups', 'ats', 'ups-topology'], domain: 'power' }),
  t('ats', 'ATS / STS', 'ATS / STS',
    'Automatic transfer switch (utility ↔ generator, seconds) and static transfer switch (A ↔ B UPS output, < ¼ cycle) — how single-corded loads see two sources.',
    '자동 절체 스위치(수전 ↔ 발전기, 수 초)와 정적 절체 스위치(A ↔ B UPS 출력, 1/4 사이클 미만). 단일 코드 부하가 두 전원을 보는 방법.',
    { related: ['ups-topology', 'generator'], aliases: ['sts', 'static transfer switch'], domain: 'power' }),
  t('tier', 'Uptime Tier I–IV', 'Uptime Tier I–IV',
    'Topology classification: I basic, II redundant components, III concurrently maintainable, IV fault tolerant. AI factories usually target Tier III for support spaces and accept N+1 in GPU halls.',
    '토폴로지 등급: I 기본, II 이중 구성요소, III 동시 유지보수 가능, IV 결함 허용. AI 팩토리는 보통 지원 공간 Tier III, GPU 홀 N+1을 택한다.',
    { related: ['ups-topology'], sources: [S.uptime], domain: 'power' }),
  t('diversity', 'Diversity factor', '다양성 계수',
    'Ratio of expected simultaneous load to the sum of nameplates (0.8–0.95 for GPU halls); UPS/generator sizing uses nameplate × diversity, breakers use nameplate (or EDPP).',
    '명판 합계 대비 실제 동시 부하 비율(GPU 홀 0.8–0.95). UPS·발전기는 명판 × 다양성, 차단기는 명판(또는 EDPP) 기준.',
    { related: ['edpp', 'derating'], domain: 'power' }),
  t('derating', 'Continuous-load derating (80 %)', '연속 부하 디레이팅 (80 %)',
    'NEC rule that breakers and conductors carrying a continuous load are loaded to at most 80 % of rating (IEC designs use 100 % rated devices).',
    '연속 부하가 흐르는 차단기·도체를 정격의 80 %까지만 사용하는 NEC 규칙(IEC 설계는 100 % 정격 기기 사용).',
    { related: ['diversity', 'power-profile'], domain: 'power' }),
  t('power-profile', 'Power profile (IEC / NEC / KR)', '전력 프로파일 (IEC / NEC / KR)',
    'Regional distribution conventions: IEC 400/415 V 50 Hz (100 % rated breakers), NEC 480 V 60 Hz (80 % continuous rule), KR = KEPCO/KEC values (to be filled in a later release).',
    '지역별 배전 관행: IEC 400/415 V 50 Hz(100 % 정격 차단기), NEC 480 V 60 Hz(80 % 연속 규칙), KR = KEPCO/KEC 값(추후 반영).',
    { related: ['derating'], domain: 'power' }),
  t('pf', 'Power factor (PF)', '역률 (PF)',
    'Real power ÷ apparent power; IT loads with PFC supplies are ~0.95–0.99, so MVA = kW ÷ PF sizes transformers and feeds.',
    '유효 전력 ÷ 피상 전력. PFC 전원을 쓰는 IT 부하는 약 0.95–0.99. 변압기·수전은 MVA = kW ÷ PF로 산정.',
    { related: ['diversity'], aliases: ['power factor'], domain: 'power' }),
  t('n-1-feed', 'Firm (N−1) utility capacity', '확정 (N−1) 수전 용량',
    'Utility capacity that remains when the largest single substation/feed group is lost; the value a site may rely on for design load.',
    '가장 큰 변전소·피더 그룹 하나를 잃어도 남는 수전 용량. 설계 부하가 의지할 수 있는 값.',
    { related: ['pf', 'generator'], aliases: ['n-1', 'firm capacity'], domain: 'power' }),

  // ───────────── Cooling ─────────────
  t('cdu', 'CDU (Coolant Distribution Unit)', 'CDU (냉각수 분배 장치)',
    'Heat exchanger + pumps separating the facility water (FWS) from the technology loop (TCS); in-row (~1–2 MW) or facility/gallery units, N+1 groups.',
    '시설수(FWS)와 기술 루프(TCS)를 분리하는 열교환기 + 펌프. 인로우(약 1–2 MW) 또는 시설/갤러리형, N+1 그룹.',
    { related: ['tcs', 'fws', 'atd', 'sidecar'], sources: [S.refDesign], domain: 'cooling' }),
  t('crah', 'CRAH / CRAC', 'CRAH / CRAC',
    'Computer-room air handler (chilled-water coil + fans) vs air conditioner (DX compressor). Removes the air-side heat share (≈ 13 % for GB300) and conditions the room.',
    '냉수 코일 + 팬(CRAH) 또는 DX 압축기(CRAC)형 실내 공조기. 공기측 발열분(GB300 약 13 %)을 제거하고 실내를 조절.',
    { related: ['fan-wall', 'hac', 'rdhx'], aliases: ['crac'], domain: 'cooling' }),
  t('fan-wall', 'Fan wall', '팬월',
    'Array of large fans and coils in the gallery wall pushing air through the hall (no floor space in rows); gallery layouts keep CRAHs and CDUs outside the white space.',
    '갤러리 벽면의 대형 팬·코일 배열로 홀에 공기를 밀어 넣는 방식(열 안 바닥 공간 불필요). 갤러리 배치는 CRAH·CDU를 화이트 스페이스 밖에 둔다.',
    { related: ['crah', 'hac'], sources: [S.refDesign], aliases: ['fanwall'], domain: 'cooling' }),
  t('rdhx', 'RDHx (Rear-Door Heat Exchanger)', 'RDHx (후면 도어 열교환기)',
    'Water coil in the rack rear door that neutralises exhaust heat (30–75 kW per rack); allows air-cooled servers in high density without containment.',
    '랙 후면 도어의 수냉 코일로 배기열을 중화(랙당 30–75 kW). 컨테인먼트 없이 고밀도 공랭 서버 운영 가능.',
    { related: ['crah', 'sidecar'], sources: [S.amdDc], aliases: ['rear door heat exchanger'], domain: 'cooling' }),
  t('sidecar', 'Liquid-to-air sidecar', '액체-공기 사이드카',
    'Rack-sized heat exchanger next to a liquid-cooled rack that rejects TCS heat into room air (200 kW / 1 rack, 500 kW / 2 racks); for halls without facility water.',
    '액랭 랙 옆에 두고 TCS 열을 실내 공기로 버리는 랙 크기 열교환기(200 kW/1랙, 500 kW/2랙). 시설수가 없는 홀용.',
    { related: ['cdu', 'rdhx'], sources: [S.refDesign], domain: 'cooling' }),
  t('dlc', 'DLC (Direct Liquid Cooling)', 'DLC (직접 액랭)',
    'Cold plates on GPUs/CPUs/switches fed by the TCS; captures 85–95 % of rack heat (GB300 heatCaptureRatio 87 %), the rest goes to air.',
    'TCS가 공급하는 GPU/CPU/스위치 콜드플레이트. 랙 발열의 85–95 % 포집(GB300 heatCaptureRatio 87 %), 나머지는 공기로.',
    { related: ['tcs', 'cdu', 'heat-capture'], aliases: ['direct liquid cooling', 'liquid cooling', 'dtc'], domain: 'cooling' }),
  t('heat-capture', 'Heat capture ratio (liquid fraction)', '열 포집률 (액체 비율)',
    'Share of rack power removed by liquid; sets the CDU vs CRAH split (GB300: 116 kW liquid + 19.3 kW air of 136 kW).',
    '랙 전력 중 액체로 제거되는 비율. CDU와 CRAH 분담을 결정(GB300: 136 kW 중 액체 116 kW + 공기 19.3 kW).',
    { related: ['dlc', 'cdu', 'crah'], sources: [S.refDesign], aliases: ['liquid fraction'], domain: 'cooling' }),
  t('ashrae-w', 'ASHRAE W-classes (W17–W45+)', 'ASHRAE W 등급 (W17–W45+)',
    'Liquid-cooling facility water temperature classes: W17 ≤ 17 °C, W27, W32, W40, W45 ≤ 45 °C, W+ > 45 °C. Higher class = more free cooling, smaller chillers.',
    '액랭 시설수 온도 등급: W17 ≤ 17 °C, W27, W32, W40, W45 ≤ 45 °C, W+ > 45 °C. 등급이 높을수록 프리쿨링 증가·칠러 축소.',
    { related: ['tcs', 'ashrae-a', 'economizer'], sources: [S.ashrae], aliases: ['w45', 'w32', 'w-class'], domain: 'cooling' }),
  t('ashrae-a', 'ASHRAE A1–A4 (air)', 'ASHRAE A1–A4 (공기)',
    'Air-cooled inlet envelopes: recommended 18–27 °C for all classes; allowable A1 15–32 °C, A2 10–35 °C, A3 5–40 °C, A4 5–45 °C.',
    '공랭 흡기 범위: 권장 18–27 °C(전 등급). 허용 A1 15–32 °C, A2 10–35 °C, A3 5–40 °C, A4 5–45 °C.',
    { related: ['ashrae-w', 'rci'], sources: [S.ashrae], aliases: ['a1', 'a2', 'ashrae'], domain: 'cooling' }),
  t('rci', 'RCI (Rack Cooling Index)', 'RCI (랙 냉각 지수)',
    'Share of rack inlets inside the ASHRAE recommended band: RCI-HI penalises inlets above 27 °C, RCI-LO below 18 °C; 100 % = all racks compliant.',
    'ASHRAE 권장 범위 안에 있는 랙 흡기 비율. RCI-HI는 27 °C 초과, RCI-LO는 18 °C 미만을 감점. 100 % = 전 랙 적합.',
    { related: ['rti', 'shi', 'ashrae-a'], aliases: ['rci-hi', 'rci-lo'], domain: 'cooling' }),
  t('rti', 'RTI (Return Temperature Index)', 'RTI (환기 온도 지수)',
    '(T_return − T_supply) ÷ (T_exhaust − T_inlet) × 100. 100 = balanced airflow; < 100 = bypass (over-supply), > 100 = recirculation (hot air re-entering intakes).',
    '(환기 − 급기) ÷ (배기 − 흡기) × 100. 100 = 균형, < 100 = 바이패스(과급기), > 100 = 재순환(더운 공기가 흡기로 유입).',
    { related: ['rci', 'shi', 'hac'], domain: 'cooling' }),
  t('shi', 'SHI (Supply Heat Index)', 'SHI (급기 열 지수)',
    'Fraction of heat picked up by supply air before it reaches the rack inlet (recirculation measure): (T_inlet − T_supply) ÷ (T_exhaust − T_supply). Lower is better.',
    '급기가 랙 흡기에 닿기 전에 흡수한 열의 비율(재순환 지표): (흡기 − 급기) ÷ (배기 − 급기). 낮을수록 좋다.',
    { related: ['rti', 'rci'], domain: 'cooling' }),
  t('pue', 'PUE (Power Usage Effectiveness)', 'PUE (전력 사용 효율)',
    'Total facility energy ÷ IT energy (annual). AIDC Studio reports annualised PUE and design-condition PUE; liquid-cooled halls with warm water reach 1.1–1.2.',
    '시설 총 에너지 ÷ IT 에너지(연간). AIDC Studio는 연평균 PUE와 설계 조건 PUE를 함께 보고. 온수 액랭 홀은 1.1–1.2 수준.',
    { related: ['ppue', 'wue', 'cue'], sources: [S.green], domain: 'cooling' }),
  t('ppue', 'pPUE (partial PUE)', 'pPUE (부분 PUE)',
    'PUE of one subsystem (e.g. cooling): (IT + that subsystem\'s energy) ÷ IT. Lets cooling options be compared independently of electrical losses.',
    '한 하위 계통(예: 냉각)의 PUE: (IT + 해당 계통 에너지) ÷ IT. 전기 손실과 무관하게 냉각 방식을 비교할 수 있다.',
    { related: ['pue'], sources: [S.green], domain: 'cooling' }),
  t('wue', 'WUE (Water Usage Effectiveness)', 'WUE (물 사용 효율)',
    'Litres of water consumed per kWh of IT energy; evaporative towers ≈ 1.8 L/kWh, dry coolers ≈ 0.',
    'IT 에너지 kWh당 소비 물의 리터. 증발식 냉각탑 약 1.8 L/kWh, 드라이쿨러 약 0.',
    { related: ['pue', 'cue', 'dry-cooler'], sources: [S.green], domain: 'cooling' }),
  t('cue', 'CUE (Carbon Usage Effectiveness)', 'CUE (탄소 사용 효율)',
    'kg CO₂ per kWh of IT energy = grid carbon intensity × PUE.',
    'IT 에너지 kWh당 kg CO₂ = 계통 탄소 계수 × PUE.',
    { related: ['pue', 'wue'], sources: [S.green], domain: 'cooling' }),
  t('economizer', 'Economizer / free cooling', '이코노마이저 / 프리쿨링',
    'Hours per year the outdoor wet-bulb (or dry-bulb) is low enough to reject heat without compressors; warmer TCS/FWS design points extend those hours.',
    '압축기 없이 외기(습구 또는 건구)로 열을 버릴 수 있는 연간 시간. TCS/FWS 설계 온도가 높을수록 시간이 늘어난다.',
    { related: ['ashrae-w', 'dry-cooler', 'chiller'], aliases: ['free cooling'], domain: 'cooling' }),
  t('chiller', 'Chiller (air-cooled / water-cooled)', '칠러 (공랭 / 수랭)',
    'Vapour-compression plant producing chilled water (COP 3–6); water-cooled chillers pair with cooling towers, air-cooled with fans. Sized N+1 on the FWS.',
    '냉수를 만드는 증기압축 플랜트(COP 3–6). 수랭 칠러는 냉각탑, 공랭 칠러는 팬과 결합. FWS에 N+1로 산정.',
    { related: ['dry-cooler', 'cub', 'economizer'], domain: 'cooling' }),
  t('dry-cooler', 'Dry cooler / cooling tower', '드라이쿨러 / 냉각탑',
    'Dry cooler = closed-loop fin-fan heat rejection (no water, needs warm loop ≥ ~35–45 °C); cooling tower = evaporative, colder water but ~2.6 M gal per MW-year.',
    '드라이쿨러 = 폐루프 핀팬 열 방출(물 없음, 약 35–45 °C 이상 온수 루프 필요). 냉각탑 = 증발식, 더 찬 물이지만 MW·년당 약 2.6 M gal 소비.',
    { related: ['chiller', 'wue', 'ashrae-w'], aliases: ['cooling tower'], domain: 'cooling' }),
  t('raised-floor', 'Raised floor vs concrete slab', '이중마루 vs 콘크리트 슬래브',
    'Raised floor gives an underfloor supply plenum and piping space but limits point loads (~1,200–1,700 kg/m²); slab supports 2,000+ kg/m² for NVL72-class racks with overhead air, power and pipes.',
    '이중마루는 바닥 급기 플레넘·배관 공간을 주지만 점하중 제한(약 1,200–1,700 kg/m²). 슬래브는 2,000 kg/m² 이상을 견뎌 NVL72급 랙에 적합하며 공기·전력·배관을 오버헤드로 처리.',
    { related: ['floor-load', 'tray'], sources: [S.amdDc], aliases: ['slab', 'raised floor'], domain: 'layout' }),
  t('floor-load', 'Floor loading (kg/m²)', '바닥 하중 (kg/m²)',
    'Allowable distributed load of the slab or raised floor vs a rack\'s weight spread over its footprint (+ clearance). GB300 NVL72 ≈ 1,400 kg on 0.6 × 1.2 m.',
    '슬래브·이중마루의 허용 분포 하중 대 랙 무게 ÷ 설치 면적(+ 이격). GB300 NVL72 약 1,400 kg / 0.6 × 1.2 m.',
    { related: ['raised-floor'], domain: 'layout' }),
  t('corridor', 'Aisle widths (cold / service / cross / egress)', '복도 폭 (냉복도 / 서비스 / 횡단 / 피난)',
    'Defaults from TIA-942 / SuperPOD: cold aisle 1.2 m, rear service 0.8–1.2 m, cross aisle 2.4 m, egress 1.2 m; national code values are a project profile setting.',
    'TIA-942 / SuperPOD 기본값: 냉복도 1.2 m, 후면 서비스 0.8–1.2 m, 횡단 통로 2.4 m, 피난 1.2 m. 국가별 법규 값은 프로젝트 프로파일 설정.',
    { related: ['hac', 'keepout'], sources: [S.tia, S.superpod], domain: 'layout' }),
  t('keepout', 'Keepout (column / door / egress / shaft)', '금지 구역 (기둥 / 문 / 피난 / 샤프트)',
    'Plan-view rectangles the layout engine must avoid; obstructions inside a row shift the tray front/back and leave a containment partition at the missing rack.',
    '배치 엔진이 피해야 하는 평면 사각형. 열 안의 장애물은 트레이를 앞뒤로 비키게 하고 빠진 랙 자리에 컨테인먼트 칸막이를 둔다.',
    { related: ['corridor', 'tray'], sources: [S.superpod], domain: 'layout' }),
  t('orv3', 'ORV3 / ORW (Open Rack)', 'ORV3 / ORW (오픈랙)',
    'Open Rack V3 (Base Specification Rev 1.1): 21-inch-wide rack with a 48 mm OU pitch and a rear DC busbar (48–54 V, 50 V in the high-power variant) fed by in-rack power shelves. Open Rack Wide (ORW Base Specification V1.0.0) is the wide frame of the same family. A ±400 VDC feed comes from a separate sidecar power rack (Diablo 400, draft), not from the ORv3 busbar. In AIDC Studio these appear as neutral classes such as "21-inch OU rack" and "Wide OU rack".',
    '오픈랙 V3 (Base Specification Rev 1.1): 21인치 폭, 48 mm OU 피치, 랙 내 전원 셸프가 공급하는 후면 DC 버스바(48–54 V, 고전력형은 50 V)를 가진 랙. 오픈랙 와이드(ORW Base Specification V1.0.0)는 같은 계열의 넓은 프레임이다. ±400 VDC 급전은 ORv3 버스바가 아니라 별도 사이드카 전원 랙(Diablo 400, 초안)에서 온다. AIDC Studio에서는 "21인치 OU 랙", "와이드 OU 랙" 같은 중립 클래스로 표시한다.',
    { related: ['oam', 'uqd', 'pdu'], sources: [S.ocp], aliases: ['orw', 'open rack', 'ou rack'], domain: 'layout' }),
  t('oam', 'OAM / UBB', 'OAM / UBB',
    'Open accelerator module (OAI-OAM Base Specification r2.0 v1.0): a mezzanine accelerator form factor with a 1000 W module power envelope. The universal baseboard (OAI-UBB r2.0 v1.0) hosts 8 modules within a 12,000 W board budget; module-to-module links are vendor links or UALink. Vendor 8-module systems implement this form factor; the generic DLC node class caps modules at the envelope.',
    '개방형 가속기 모듈(OAI-OAM Base Specification r2.0 v1.0): 모듈 전력 한도 1000 W인 메자닌 가속기 폼팩터. 유니버설 베이스보드(OAI-UBB r2.0 v1.0)는 보드 전력 12,000 W 안에서 모듈 8개를 싣고, 모듈 간 링크는 벤더 링크나 UALink다. 벤더 8모듈 시스템이 이 폼팩터를 구현하며, 제네릭 DLC 노드 클래스는 모듈 전력을 이 한도로 둔다.',
    { related: ['orv3', 'ualink', 'scale-up'], sources: [S.ocp], aliases: ['ubb'], domain: 'layout' }),
  t('uqd', 'UQD / BMQC (liquid quick connectors)', 'UQD / BMQC (액체 퀵 커넥터)',
    'Dripless quick connectors of liquid-cooled racks: UQD (Universal Quick Disconnect Rev 1.0) for hand-mated manifold hoses, UQDB for blind mating, and BMQC (ORv3 Blind Mate Quick Connector Rev 1.0, up to 9 L/min per mated pair, about 6 kW at 10 K with PG25) for 21-inch blind-mate rack manifolds. The pair count per node follows from the liquid load.',
    '액체냉각 랙의 무적하 퀵 커넥터: 손으로 체결하는 매니폴드 호스용 UQD(Universal Quick Disconnect Rev 1.0), 블라인드메이트용 UQDB, 21인치 블라인드메이트 랙 매니폴드용 BMQC(ORv3 Blind Mate Quick Connector Rev 1.0, 체결 쌍당 최대 9 L/min, PG25·10 K에서 약 6 kW). 노드당 쌍 수는 액체 부하에서 정한다.',
    { related: ['tcs', 'cdu', 'orv3'], sources: [S.ocp], aliases: ['uqdb', 'bmqc', 'quick disconnect', 'blind-mate connector'], domain: 'cooling' }),
  t('opg', 'OPG / XOC (open cluster network blocks)', 'OPG / XOC (개방 클러스터 네트워크 블록)',
    'Published cluster network building blocks (OPG-M / XOC-N v1.0): an OPG-128 pod groups 128 accelerators with rail-optimised leaves, and XOC-1k joins 8 OPG-128 pods. Larger sizes are only in the companion reference-architecture repository, so a hall spine layer above about 1,024 accelerators is an estimate.',
    '발행된 클러스터 네트워크 구성 블록(OPG-M / XOC-N v1.0): OPG-128 포드는 레일 최적화 리프로 가속기 128개를 묶고, XOC-1k는 OPG-128 포드 8개를 잇는다. 더 큰 크기는 참조 아키텍처 저장소에만 있으므로, 가속기 약 1,024개를 넘는 홀 스파인 계층은 추정이다.',
    { related: ['rail-optimized', 'scale-up'], sources: [S.ocp], aliases: ['opg-128', 'xoc-1k', 'xoc'], domain: 'network' }),
  t('hgx', 'HGX baseboard', 'HGX 베이스보드',
    'NVIDIA 8-GPU SXM baseboard (H100/H200/B200/B300) in a 4–10 U air- or liquid-cooled server; 4 servers per rack is a common air-cooled density (~40–60 kW).',
    'NVIDIA 8-GPU SXM 베이스보드(H100/H200/B200/B300), 4–10 U 공랭·액랭 서버. 랙당 4대가 흔한 공랭 밀도(약 40–60 kW).',
    { related: ['nvl72', 'oam'], domain: 'layout' }),
  t('wave', 'Deployment wave', '배포 웨이브',
    'A set of DUs commissioned together with a target ready date; the BOM, rack plan and schedule are cut by wave.',
    '목표 가동일과 함께 같이 커미셔닝하는 DU 집합. BOM·랙 플랜·일정은 웨이브 단위로 나뉜다.',
    { related: ['du', 'growth', 'rfs'], domain: 'ops' }),
  t('rfs', 'Ready For Service (RFS)', '서비스 개시 (RFS)',
    'Date a wave (or the site) has passed commissioning and acceptance and can take production load.',
    '웨이브(또는 사이트)가 커미셔닝·인수를 통과해 운영 부하를 받을 수 있는 날짜.',
    { related: ['wave', 'acceptance', 'critical-path'], domain: 'ops' }),
  t('critical-path', 'Critical path (CPM)', '크리티컬 패스 (CPM)',
    'Chain of tasks with zero slack that sets the project end date; long-lead procurement (≥ 26 weeks) and utility energisation usually sit on it.',
    '여유(slack)가 0인 작업 사슬로 프로젝트 종료일을 결정. 장납기 조달(26주 이상)과 수전 에너자이징이 보통 여기에 놓인다.',
    { related: ['rfs', 'lead-time'], domain: 'ops' }),
  t('lead-time', 'Lead time', '리드타임',
    'Weeks from purchase order to delivery; transformers and switchgear (40–60 wk), generators (50+ wk) and GPU racks (20–30 wk) dominate the schedule.',
    '발주부터 납품까지의 주 수. 변압기·배전반(40–60주), 발전기(50주 이상), GPU 랙(20–30주)이 일정을 지배.',
    { related: ['critical-path'], domain: 'ops' }),
  t('acceptance', 'Acceptance levels L1–L5', '인수 단계 L1–L5',
    'Commissioning ladder: L1 factory, L2 site component, L3 system, L4 integrated system (failure scenarios), L5 integrated operations; cluster validation (RCCL/NCCL, ib_write_bw, IOR) sits at L4/L5.',
    '커미셔닝 단계: L1 공장, L2 현장 부품, L3 시스템, L4 통합 시스템(장애 시나리오), L5 통합 운영. 클러스터 검증(RCCL/NCCL, ib_write_bw, IOR)은 L4/L5.',
    { related: ['rfs', 'busbw', 'cvs'], sources: [S.amdDc], domain: 'ops' }),
  t('cvs', 'Cluster Validation Suite (CVS) / DCGM diag', '클러스터 검증 스위트 (CVS) / DCGM diag',
    'Vendor bring-up suites: AMD CVS / AGFHC (GPU, xGMI, NIC, storage sweeps with thresholds), NVIDIA DCGM diagnostics and nccl-tests.',
    '벤더 브링업 스위트: AMD CVS / AGFHC(GPU·xGMI·NIC·스토리지 스윕 + 임계값), NVIDIA DCGM 진단 및 nccl-tests.',
    { related: ['acceptance', 'busbw'], sources: [S.amdDc], aliases: ['agfhc', 'dcgm'], domain: 'ops' }),
  t('ip-plan', 'IP plan (/31 p2p, VLAN-per-rail)', 'IP 플랜 (/31 p2p, 레일별 VLAN)',
    'Addressing scheme for the fabrics: /31 point-to-point links with eBGP unnumbered on the back-end, per-rail /24 VLANs on L2 designs, OOB and in-band VLANs, loopbacks, IB PKeys. Planned for a later release.',
    '패브릭 주소 체계: 백엔드 /31 p2p + eBGP unnumbered, L2 설계는 레일별 /24 VLAN, OOB·인밴드 VLAN, 루프백, IB PKey. 이후 릴리스 예정.',
    { related: ['ebgp', 'oob'], sources: [S.amdRd], domain: 'network' }),
  t('cable-schedule', 'Cable schedule', '케이블 스케줄',
    'Port-level from/to list (rack-U-port ↔ rack-U-port) with cable type, length and label; generated from the network engine\'s switch/node/link model.',
    '포트 단위 from/to 목록(랙-U-포트 ↔ 랙-U-포트) + 케이블 종류·길이·라벨. 네트워크 엔진의 스위치/노드/링크 모델에서 생성.',
    { related: ['bom', 'rack-plan', 'tray'], domain: 'ops' }),
  t('bom', 'BOM (Bill of Materials)', 'BOM (자재 명세)',
    'Quantity list of racks, switches, cables, optics, trays, busway, CDUs, CRAHs and PDUs — per wave in the deployment bundle, with prices and lead times in the cost view.',
    '랙·스위치·케이블·광모듈·트레이·버스웨이·CDU·CRAH·PDU 수량 목록. 배포 번들에서는 웨이브별, 비용 화면에서는 단가·리드타임 포함.',
    { related: ['rack-plan', 'wave', 'lead-time'], domain: 'ops' }),
  t('rack-plan', 'Rack plan / U-map', '랙 플랜 / U-맵',
    'Rack schedule (hall · row · position · tag · type · wave · kW · weight) plus a per-rack-type elevation showing which RU each switch, power shelf or tray occupies.',
    '랙 일람(홀·열·위치·태그·유형·웨이브·kW·무게)과 랙 유형별 입면도(스위치·파워셸프·트레이가 차지하는 RU).',
    { related: ['bom', 'ru'], domain: 'ops' }),
  t('ru', 'Rack unit (RU / U)', '랙 유닛 (RU / U)',
    '44.45 mm of vertical rack space; a 42–48 U 19-inch rack or 21-inch ORV3 rack. Network racks are planned by RU and kW.',
    '수직 랙 공간 44.45 mm. 19인치 42–48 U 랙 또는 21인치 ORV3 랙. 네트워크 랙은 RU와 kW로 계획.',
    { related: ['rack-plan'], aliases: ['u', 'rack unit'], domain: 'layout' }),
  t('capex-opex', 'CAPEX / OPEX / TCO', 'CAPEX / OPEX / TCO',
    'Capital cost (equipment + facility + labour + contingency), yearly operating cost (energy at average load + maintenance ≈ 2 % of CAPEX) and total cost over 5 years.',
    '자본 비용(장비 + 시설 + 인건비 + 예비비), 연간 운영 비용(평균 부하 에너지 + 유지보수 ≈ CAPEX의 2 %), 5년 총 소유 비용.',
    { related: ['bom', 'pue'], aliases: ['capex', 'opex', 'tco'], domain: 'ops' }),
  t('nameplate', 'Nameplate power', '명판 전력',
    'Manufacturer-rated maximum continuous input of a rack or unit; the basis for breaker sizing and the value multiplied by diversity for design load.',
    '제조사가 표기한 랙·장비의 최대 연속 입력. 차단기 산정 기준이며 다양성 계수를 곱해 설계 부하를 얻는다.',
    { related: ['tdp', 'diversity', 'edpp'], domain: 'power' }),
  t('one-line', 'One-line (single-line) diagram', '단선 결선도',
    'Schematic of the power path — utility → transformer → switchgear → UPS → PDU/RPP/busway → load — drawn with one line per circuit regardless of phases.',
    '수전 → 변압기 → 배전반 → UPS → PDU/RPP/버스웨이 → 부하의 전력 경로를 상(phase)과 무관하게 회로당 한 선으로 그린 도면.',
    { related: ['ups-topology', 'busway'], aliases: ['single-line'], domain: 'power' }),
  t('digital-twin', 'Digital twin (OpenUSD)', '디지털 트윈 (OpenUSD)',
    'Physically based model of the facility (layout, power, cooling, network) used to validate design, test changes and later operate the site; AIDC Studio exports OpenUSD stages with equipment attributes.',
    '설계 검증·변경 시험·운영에 쓰는 시설(배치·전력·냉각·네트워크)의 물리 기반 모델. AIDC Studio는 장비 속성을 포함한 OpenUSD 스테이지로 내보낸다.',
    { related: ['simready'], sources: [S.refDesign], domain: 'general' }),
  t('simready', 'Simulation-ready asset (USD)', '시뮬레이션용 에셋 (USD)',
    'A USD model that carries engineering metadata besides geometry — manufacturer, dimensions, weight, clearances and class-specific specs such as nameplate power or flow curves. AIDC Studio keeps this metadata in its own catalog and ships no third-party assets.',
    '형상 외에 제조사·치수·무게·이격, 명판 전력이나 유량 곡선 같은 클래스별 사양 메타데이터를 담은 USD 모델. AIDC Studio는 이 메타데이터를 자체 카탈로그에 두며 제3자 에셋을 포함하지 않는다.',
    { related: ['digital-twin', 'edpp'], sources: [S.refDesign], domain: 'general' }),
  t('spec-source', 'Spec source tag (announced / estimate / datasheet …)', '출처 태그 (발표 / 추정 / 데이터시트 …)',
    'Every number in AIDC Studio carries where it came from: vendor-datasheet, public-spec, announced (pre-release), estimate, or user. A legacy tag from earlier versions is still read for stored items and shown as unverified.',
    'AIDC Studio의 모든 수치는 출처를 가진다: vendor-datasheet, public-spec, announced(출시 전), estimate, user. 이전 버전의 레거시 태그는 저장된 항목을 위해 계속 읽으며 미검증으로 표시한다.',
    { domain: 'general' }),
  t('gpu-rack-density', 'Rack density (kW/rack, kW/m²)', '랙 밀도 (kW/랙, kW/m²)',
    'Power per rack and per square metre of white space; AI halls run 100–250 kW per rack and 5–15 kW/m² including aisles, versus 5–15 kW per rack in enterprise halls.',
    '랙당·상면 m²당 전력. AI 홀은 랙당 100–250 kW, 통로 포함 5–15 kW/m²(엔터프라이즈 홀은 랙당 5–15 kW).',
    { related: ['floor-load', 'edpp'], domain: 'layout' }),
  t('white-space', 'White space / grey space', '화이트 스페이스 / 그레이 스페이스',
    'White space = the IT hall floor (racks, aisles, in-row cooling); grey space = electrical and mechanical rooms, galleries and the CUB that support it.',
    '화이트 스페이스 = IT 홀 바닥(랙·통로·인로우 냉각), 그레이 스페이스 = 이를 지원하는 전기실·기계실·갤러리·CUB.',
    { related: ['cub', 'mmr'], aliases: ['grey space', 'gray space', 'data hall'], domain: 'layout' }),
  t('mechanical-gallery', 'Mechanical gallery', '기계 갤러리',
    'Strip along the hall edge (outside the containment rows) that holds CDUs, CRAHs/fan walls and piping headers so they consume no row space.',
    '컨테인먼트 열 밖 홀 가장자리 띠. CDU·CRAH/팬월·배관 헤더를 두어 열 공간을 차지하지 않게 한다.',
    { related: ['fan-wall', 'cdu', 'white-space'], sources: [S.refDesign], domain: 'layout' }),
  t('containment-partition', 'Containment partition / blanking', '컨테인먼트 칸막이 / 블랭킹',
    'Panels closing gaps in a contained aisle (missing racks, empty RU) so hot and cold air do not short-circuit; the thermal solver models blanking on/off.',
    '컨테인먼트 통로의 빈 곳(빠진 랙, 빈 RU)을 막는 패널. 열·냉기가 단락되지 않게 하며 열 솔버가 블랭킹 유무를 모델링.',
    { related: ['hac', 'rti'], aliases: ['blanking panel'], domain: 'cooling' }),
  t('lpm-per-kw', 'LPM per kW (TCS flow)', 'kW당 LPM (TCS 유량)',
    'Liquid flow needed per kW of captured heat; warm-water designs typically plan at least about 1.5 LPM/kW, i.e. ΔT ≈ 10 K (Q = ṁ·cp·ΔT).',
    '포집 열 kW당 필요한 액체 유량. 온수 설계는 보통 최소 약 1.5 LPM/kW, 즉 ΔT ≈ 10 K로 계획한다(Q = ṁ·cp·ΔT).',
    { related: ['tcs', 'cdu'], sources: [S.refDesign], aliases: ['lpm'], domain: 'cooling' }),
  t('pq-curve', 'Pump P-Q curve', '펌프 P-Q 곡선',
    'Pressure (head) vs flow characteristic of a CDU pump set; intersected with the TCS loop resistance to find operating flow. Taken per CDU from the catalog item (vendor datasheet or estimate).',
    'CDU 펌프의 압력(양정) 대 유량 특성. TCS 루프 저항과의 교점이 운전 유량. CDU별 카탈로그 항목(제조사 데이터시트 또는 추정치)에서 가져온다.',
    { related: ['cdu', 'lpm-per-kw'], domain: 'cooling' }),
  t('ib-pkey', 'IB partition key (PKey)', 'IB 파티션 키 (PKey)',
    'InfiniBand tenant isolation key (16-bit) assigned per partition by the subnet manager; the IB analogue of a VLAN.',
    '서브넷 매니저가 파티션마다 부여하는 인피니밴드 테넌트 격리 키(16비트). VLAN의 IB 대응물.',
    { related: ['infiniband', 'ip-plan'], aliases: ['pkey'], domain: 'network' }),
  t('nos', 'NOS (SONiC / Cumulus / EOS / NX-OS / OS10 / JunOS)', 'NOS (SONiC / Cumulus / EOS / NX-OS / OS10 / JunOS)',
    'Network operating systems the config generator targets; AIDC Studio plans SONiC first, then Cumulus/NVOS, Arista EOS, Cisco NX-OS, Dell OS10 and Juniper JunOS.',
    '설정 생성기가 대상으로 하는 네트워크 OS. AIDC Studio는 SONiC → Cumulus/NVOS → Arista EOS → Cisco NX-OS, Dell OS10, Juniper JunOS 순으로 계획.',
    { related: ['ebgp', 'ip-plan'], aliases: ['sonic', 'cumulus', 'nvos'], domain: 'network' }),
  t('supernic', 'SuperNIC / DPU (ConnectX / BlueField / Pensando)', 'SuperNIC / DPU (ConnectX / BlueField / Pensando)',
    'GPU-attached network adapters (400–800G per GPU) with RDMA, adaptive-routing reorder buffers and, for DPUs, offloaded storage/security; one per GPU on the scale-out fabric.',
    'GPU에 붙는 네트워크 어댑터(GPU당 400–800G). RDMA·적응 라우팅 재정렬 버퍼, DPU는 스토리지/보안 오프로드. 스케일아웃 패브릭에 GPU당 1개.',
    { related: ['scale-out', 'spectrum-x'], aliases: ['dpu', 'connectx', 'bluefield', 'nic'], domain: 'network' }),
  t('link-budget', 'Cable length budget (30 / 50 / 500 m)', '케이블 길이 예산 (30 / 50 / 500 m)',
    'Common reference-design rules (e.g. NVIDIA DGX SuperPOD): node→leaf MMF ≤ 50 m total path (≤ 30 m preferred); switch↔switch SMF ≤ 500 m without repeaters; route length = Manhattan × route factor + tray rise/fall + slack.',
    '흔한 레퍼런스 설계 규칙(예: NVIDIA DGX SuperPOD): 노드→리프 MMF 총 경로 50 m 이하(30 m 권장), 스위치↔스위치 SMF 500 m 이하(리피터 없이). 경로 길이 = 맨해튼 거리 × 경로계수 + 트레이 상하강 + 여유.',
    { related: ['sr8', 'dr8', 'spine-placement', 'tray'], sources: [S.superpod, S.refDesign], domain: 'optics' }),
  t('hops', 'Hop count / latency', '홉 수 / 지연',
    'Number of switch traversals between two endpoints (1 on a rail, 3 across leaf-spine, 5 with a core tier); each hop adds ~0.3–1 µs plus fibre delay (~5 ns/m).',
    '두 엔드포인트 사이의 스위치 통과 횟수(레일 내 1, 리프-스파인 3, 코어 포함 5). 홉당 약 0.3–1 µs + 광섬유 지연(약 5 ns/m).',
    { related: ['tiers', 'rail-optimized'], domain: 'network' }),
  t('mlag', 'MLAG / MC-LAG', 'MLAG / MC-LAG',
    'Two switches presenting one logical LAG to a dual-homed host; an L2 redundancy technique used on front-end/storage leaves, not on the GPU back-end.',
    '이중 연결 호스트에 두 스위치가 하나의 논리 LAG로 보이게 하는 L2 이중화 기법. 프런트엔드/스토리지 리프에 쓰고 GPU 백엔드에는 쓰지 않는다.',
    { related: ['l3-fabric', 'frontend'], aliases: ['mc-lag', 'lag'], domain: 'network' }),
  t('cfd-lite', 'CFD-lite (AIDC thermal solver)', 'CFD-lite (AIDC 열 솔버)',
    'Coarse-grid (0.2–0.5 m) potential-flow + energy solver that estimates rack inlet temperatures, RCI/RTI and hotspots in seconds; results can be compared with imported reference CFD cases.',
    '초 단위로 랙 흡기 온도·RCI/RTI·핫스팟을 추정하는 성긴 격자(0.2–0.5 m) 퍼텐셜 유동 + 에너지 솔버. 가져온 레퍼런스 CFD 케이스와 비교할 수 있다.',
    { related: ['rci', 'rti', 'shi'], domain: 'cooling' }),
  t('load-case', 'CFD load case (40 / 60 / 80 / 100 %)', 'CFD 부하 케이스 (40 / 60 / 80 / 100 %)',
    'IT utilisation levels of the NVIDIA reference CFD dataset; used to compare the CFD-lite solver and to size cooling for partial-load operation.',
    'NVIDIA 레퍼런스 CFD 데이터셋의 IT 사용률 단계. CFD-lite 비교와 부분 부하 냉각 산정에 사용.',
    { related: ['cfd-lite'], domain: 'cooling' }),
  t('thermal-inertia', 'Thermal ride-through', '열 관성 / 냉각 지속',
    'Time the TCS/FWS loops keep inlet temperatures within limits after a pump or chiller loss (buffer tanks, loop volume); drives whether CDU pumps sit on UPS.',
    '펌프·칠러 상실 후 TCS/FWS 루프가 흡기 온도를 한계 안에 유지하는 시간(버퍼 탱크·루프 용적). CDU 펌프를 UPS에 둘지 결정.',
    { related: ['cdu', 'ups'], domain: 'cooling' }),
  t('hac-door', 'End doors / roof panels', '엔드 도어 / 지붕 패널',
    'Components of a containment: sliding end doors and roof panels (or ceiling chimneys for ducted HAC). Missing roof = partial containment with measurable bypass.',
    '컨테인먼트 구성품: 미닫이 엔드 도어와 지붕 패널(덕트형 HAC는 천장 침니). 지붕이 없으면 부분 컨테인먼트로 바이패스가 생긴다.',
    { related: ['hac', 'rti'], domain: 'cooling' }),
  t('cooling-budget', 'Liquid / air cooling budget (kW)', '액랭 / 공랭 예산 (kW)',
    'Facility water and air-handling capacity allocated to a hall; the layout engine stops placing racks when the liquid-cooled share exceeds the liquid budget.',
    '홀에 배정된 시설수·공조 용량. 액랭 분담이 액랭 예산을 넘으면 배치 엔진이 랙 배치를 멈춘다.',
    { related: ['heat-capture', 'fws'], domain: 'cooling' }),
  t('it-power-budget', 'IT power budget (kW)', 'IT 전력 예산 (kW)',
    'Utility capacity allocated to one hall for IT load (the "power envelope"); AI halls are usually planned to the envelope first and floor area second.',
    '홀 하나의 IT 부하에 배정된 수전 용량("전력 범위"). AI 홀은 보통 바닥 면적보다 전력 범위를 먼저 기준으로 계획한다.',
    { related: ['n-1-feed', 'maxlps'], domain: 'power' }),
];

export default GLOSSARY_TERMS;
