import { describe, expect, it } from 'vitest';
import { analyzeProject, buildContext, cableLengthM, cableTypes, createNvidiaReferenceProject, evaluatePlacementCandidate, relayoutForPlacement, type CableTray, type Project } from '../src/index.ts';
import { analyzeNetworkCtx } from '../src/engines/network.ts';

const ref = () => createNvidiaReferenceProject().project;

describe('network.ts v2 — placement policies', () => {
  it('reference project (central-end, NVL72): traffic + placement reports attached, all four candidates evaluated', () => {
    const a0 = ref();
    const a = analyzeProject(a0);
    expect(a.network.traffic).toBeDefined();
    expect(a.network.traffic!.commEfficiencyEffective).toBeGreaterThan(0.5);
    expect(a.network.traffic!.stepTimeS).toBeGreaterThan(0);
    const p = a.network.placement!;
    expect(p.chosen).toBe('central-end');
    expect(p.candidates.map((c) => c.spinePlacement).sort()).toEqual(['central-center', 'central-end', 'distributed', 'separate-room']);
    // S1's relayoutForPlacement is live: the current placement keeps the project geometry ('current'), the other three
    // are regenerated by the layout engine ('relayout'). 'distributed' appends the spine racks to the pod rows (dealt
    // round-robin over the pods, QA-network-v2 #4), so the leaf→spine links inside the same row end are ≤ 3 m and use DAC
    // (no optics) — derived below, not a magic number.
    const dist = relayoutForPlacement(a0, 'hall-a', 'distributed');
    const distNet = analyzeNetworkCtx(buildContext(dist));
    const noOptics = new Set(cableTypes().filter((t) => t.transceiverUSD <= 0).map((t) => t.id));
    const soLabel = distNet.plans.find((x) => x.key === 'scale-out')!.label;
    const dacLinks = distNet.analysis.cableRuns.filter((r) => r.fabric === soLabel && (r.tier === 'leaf-spine' || r.tier === 'spine-core') && noOptics.has(r.cableTypeId)).reduce((s, r) => s + r.count, 0);
    // every pod hosts spines now, so more leaf uplinks stay inside their own row end than with the spines packed into pods 1–2 (960)
    expect(dacLinks).toBe(1056);
    const expectXcvr: Record<string, number> = { 'central-end': 2 * 96 * 72, 'central-center': 2 * 96 * 72, 'separate-room': 2 * 96 * 72, distributed: 2 * (96 * 72 - dacLinks) };
    expect(expectXcvr.distributed).toBe(2 * (6912 - 1056));
    for (const c of p.candidates) {
      expect(c.links).toBe(96 * 72); // every leaf uplink evaluated
      expect(c.overLimitLinks).toBe(0);
      expect(c.meanLinkM).toBeGreaterThan(0);
      expect(c.maxLinkM).toBeGreaterThanOrEqual(c.meanLinkM);
      expect(c.transceivers).toBe(expectXcvr[c.spinePlacement]);
      expect(c.trayPeakMm2).toBeGreaterThan(0);
      expect(c.basis).toBe(c.spinePlacement === 'central-end' ? 'current' : 'relayout');
    }
    const by = Object.fromEntries(p.candidates.map((c) => [c.spinePlacement, c]));
    expect(by['central-end'].basis).toBe('current');
    expect(by['separate-room'].meanLinkM).toBeGreaterThanOrEqual(by['central-end'].meanLinkM - 3); // +3 m room offset vs the end row
    expect(by.distributed.lostPositions).toBeGreaterThan(0);
    expect(by.distributed.fiberKm).toBeLessThan(by['central-end'].fiberKm); // spine-placement.md §5.2: mean run halves-ish
    expect(p.recommended).toBeDefined();
  });

  it('distributed: spine racks inside compute pods host the spines and every leaf spreads its uplinks over all of them', () => {
    const p = ref();
    p.network.scaleOut.spinePlacement = 'distributed';
    const pods = ['pod-01', 'pod-02', 'pod-03', 'pod-04'];
    const spineRacks = p.equipment.filter((e) => e.networkRole === 'scale-out-spine');
    expect(spineRacks.length).toBeGreaterThan(0);
    spineRacks.forEach((e, i) => {
      const pod = pods[i % pods.length];
      const anchor = p.equipment.find((x) => x.podId === pod && x.tag.endsWith('-A-12'))!;
      e.podId = pod;
      e.rowId = `${pod}-a`;
      e.position = { x: anchor.position.x + 3 + Math.floor(i / pods.length) * 0.6, y: anchor.position.y };
    });
    const ctx = buildContext(p);
    const net = analyzeNetworkCtx(ctx);
    expect(net.effectivePlacement.spine).toBe('distributed');
    expect(net.analysis.unplacedSwitches).toEqual([]);
    const so = net.plans.find((x) => x.key === 'scale-out')!;
    const spineHosts = new Set(net.analysis.rackLoads!.filter((r) => r.switches.some((s) => s.role === 'spine' && s.fabric === so.label)).map((r) => r.rackId));
    const hostPods = new Set([...spineHosts].map((id) => p.equipment.find((e) => e.id === id)!.podId));
    expect(hostPods.size).toBe(4);
    // a single leaf rack's uplinks reach spine racks in every pod (2-tier: hall-shared spine)
    const leafRack = net.analysis.rackLoads!.find((r) => r.switches.some((s) => s.role === 'leaf' && s.fabric === so.label))!;
    const targets = new Set(net.analysis.cableRuns.filter((r) => r.tier === 'leaf-spine' && r.fromId === leafRack.rackId).map((r) => p.equipment.find((e) => e.id === r.toId)!.podId));
    expect(targets.size).toBe(4);
  });

  it("'distributed' without in-pod spine racks falls back to the core row with a note", () => {
    const p = ref();
    p.network.scaleOut.spinePlacement = 'distributed';
    const net = analyzeNetworkCtx(buildContext(p));
    expect(net.effectivePlacement.spine).toBe('central-end');
    expect(net.notes.some((n) => /distributed/.test(n))).toBe(true);
    expect(net.analysis.unplacedSwitches).toEqual([]);
  });

  it("'tor' on NVL72 racks falls back to mid-row; on HGX racks leaves move into the compute racks (in-rack 2 m links)", () => {
    const nvl = ref();
    nvl.network.scaleOut.leafPlacement = 'tor';
    const n1 = analyzeNetworkCtx(buildContext(nvl));
    expect(n1.effectivePlacement.leaf).toBe('mid-row');
    expect(n1.notes.some((n) => /tor/.test(n))).toBe(true);

    const hgx = createNvidiaReferenceProject({ gpuRackCatalogId: 'hgx-b200-air-4x' }).project;
    hgx.network.scaleOut.leafPlacement = 'tor';
    const n2 = analyzeNetworkCtx(buildContext(hgx));
    expect(n2.effectivePlacement.leaf).toBe('tor');
    const so = n2.plans.find((x) => x.key === 'scale-out')!;
    const gpuRackIds = new Set(hgx.equipment.filter((e) => e.catalogId === 'hgx-b200-air-4x').map((e) => e.id));
    const torHosts = n2.analysis.rackLoads!.filter((r) => gpuRackIds.has(r.rackId) && r.switches.some((s) => s.role === 'leaf' && s.fabric === so.label));
    expect(torHosts.length).toBe(so.leaves);
    const inRack = n2.analysis.cableRuns.filter((r) => r.tier === 'endpoint-leaf' && r.fabric === so.label && r.fromId === r.toId);
    expect(inRack.reduce((s, r) => s + r.count, 0)).toBeGreaterThan(0);
    expect(inRack.every((r) => r.lengthM === 2)).toBe(true);
    expect(n2.analysis.unconnectedLinks).toBe(0);
  });
});

describe('network.ts v2 — DDC (DriveNets FSE) and single cable-length model', () => {
  it('drivenets-fse sizes NCP/NCF from the RA rule, one logical hop, NCF priced/powered separately', () => {
    const p = ref();
    p.network.scaleOut = { ...p.network.scaleOut, fabric: 'drivenets-fse', switchCatalogId: 'drivenets-5300r', topology: 'leaf-spine' };
    const a = analyzeProject(p);
    const so = a.network.fabrics.find((f) => f.name.startsWith('Scale-out'))!;
    expect(so.fabric).toBe('drivenets-fse');
    expect(so.tiers[0].name).toMatch(/NCP/);
    expect(so.tiers[0].switches).toBe(4 * Math.ceil(1728 / 18)); // 96 NCP per DU
    expect(so.tiers[1].name).toMatch(/NCF/);
    expect(so.tiers[1].switches).toBe(Math.ceil((384 * 20) / 128)); // beyond AI-4608-800 → extrapolated
    // 384 NCP / 60 NCF exceed the 2-tier FSE cap (256 × 40): flagged, not silently feasible (QA-network-v2 #2)
    expect(so.extrapolated).toBe(true);
    expect(so.feasible).toBe(false);
    expect(a.issues.some((i) => i.id.startsWith('network-infeasible-drivenets-fse') && i.severity === 'error')).toBe(true);
    expect(a.issues.some((i) => i.id.startsWith('network-extrapolated-drivenets-fse'))).toBe(true);
    expect(so.maxHops).toBe(1);
    expect(so.oversubscription).toBe(1);
    expect(a.network.traffic!.notes.some((n) => /AI-4608-800/.test(n))).toBe(true);
    expect(a.network.traffic!.eta?.class).toBe('ddc');
    expect(a.network.traffic!.minOversubscription).toBe(1);
  });

  it('cableLengthM routes along the tray graph when project.trays exists and falls back to Manhattan otherwise', () => {
    const p: Project = { ...ref(), trays: undefined }; // the layout engine may already emit trays — start from the Manhattan model
    const ctx = buildContext(p);
    const a = ctx.placed.find((x) => x.e.tag === 'DU01-A-01')!;
    const b = ctx.placed.find((x) => x.e.tag === 'DU02-B-12')!;
    const manhattanLen = cableLengthM(p, a, b);
    expect(manhattanLen).toBeGreaterThan(0);
    expect(manhattanLen % 0.5).toBe(0);
    const hall = p.halls[0];
    const z = hall.trayHeight;
    // one row tray per rack row (along X, above the row) + a main tray along Y at the east wall
    const rows = new Map<number, { minX: number; maxX: number }>();
    for (const x of ctx.placed) {
      if (x.e.hallId !== hall.id || x.item.category !== 'gpu-rack') continue;
      const y = Math.round(x.e.position.y * 100) / 100;
      const cur = rows.get(y) ?? { minX: Infinity, maxX: -Infinity };
      cur.minX = Math.min(cur.minX, x.e.position.x);
      cur.maxX = Math.max(cur.maxX, x.e.position.x);
      rows.set(y, cur);
    }
    const mainX = Math.max(...[...rows.values()].map((r) => r.maxX)) + 2;
    const trays: CableTray[] = [...rows.entries()].map(([y, r], i) => ({ id: `row-${i}`, hallId: hall.id, kind: 'row', points: [{ x: r.minX, y, z }, { x: mainX, y, z }], widthM: 0.45 }));
    const ys = [...rows.keys()];
    trays.push({ id: 'main', hallId: hall.id, kind: 'main', points: [{ x: mainX, y: Math.min(...ys), z }, { x: mainX, y: Math.max(...ys), z }], widthM: 0.6 });
    const withTrays = cableLengthM(p, a, b, trays);
    expect(withTrays % 0.5).toBe(0);
    // expected: along row A to the main tray, down the main tray, back along row B + 2 × vertical + 2 × slack
    const expected = (mainX - a.e.position.x) + Math.abs(a.e.position.y - b.e.position.y) + (mainX - b.e.position.x) + 2 * Math.max(0.5, z - 1.2) + 2 * p.network.cabling.slackPerEndM;
    expect(withTrays).toBeGreaterThanOrEqual(Math.floor(expected * 2) / 2);
    expect(withTrays).toBeLessThanOrEqual(Math.ceil(expected * 2) / 2 + 0.5);
    // the same call through project.trays
    const p2: Project = { ...p, trays };
    expect(cableLengthM(p2, a, b)).toBe(withTrays);
    // a rack far from any tray cannot attach → Manhattan fallback
    const far: Project = { ...p, trays: [{ id: 'x', hallId: hall.id, kind: 'main', points: [{ x: 0, y: 0, z }, { x: 0.1, y: 0, z }], widthM: 0.3 }] };
    expect(cableLengthM(far, a, b)).toBe(manhattanLen);
  });

  it('evaluatePlacementCandidate runs one candidate on demand', () => {
    const p = ref();
    const c = evaluatePlacementCandidate(p, 'central-center', { fillRatio: 0.4 });
    expect(c?.spinePlacement).toBe('central-center');
    expect(c?.basis).toBe('relayout'); // S1's relayoutForPlacement is live (was 'approximation' before it landed)
    expect(evaluatePlacementCandidate(p, 'central-end', { fillRatio: 0.4 })?.basis).toBe('current');
    expect(c?.trayPeakMm2).toBeGreaterThan(0);
  });
});
