// Design document as a printable single-file HTML with embedded core SVG diagrams (stream T7, DECISIONS-v2-2 F5).
// Walks the same block model as the Markdown generator (docs/index.ts) and replaces the mermaid blocks with the
// deterministic SVG generators in docs/svg/*; the 101 plan and 201 rack-elevation sheets are embedded as figures.
// Output: one self-contained file (inline CSS, no scripts, no external assets), A4 print rules, a page break per
// chapter and a table of contents. Language = opts.locale ?? project.locale ?? 'en'.
import { findCatalogItem } from '../catalog/catalog.ts';
import { generateDrawings } from '../drawings/index.ts';
import type { Locale, Project, ProjectAnalysis } from '../model/types.ts';
import { escapeHtml, htmlId, htmlPage, htmlTable, inlineMarkup, type HtmlTocEntry } from '../deploy/html.ts';
import { buildDesignDocumentBlocks, docStrings, type DesignDocOptions, type DocBlock, type DocChapter } from './index.ts';
import { scheduleGanttSvg } from './svg/gantt.ts';
import { oneLineSvg } from './svg/oneLine.ts';
import { fabricTopologySvg } from './svg/topology.ts';

export interface DesignDocHtmlOptions extends DesignDocOptions {
  /** embed the first plan (1xx) and rack-elevation (2xx) sheets as figures (default true) */
  includeDrawings?: boolean;
}

const HTML_STRINGS = {
  en: {
    contents: 'Contents', topology: 'Figure — network topology per fabric (tiers, switch counts, links)', oneLine: 'Figure — power one-line diagram (A / B / reserve paths)',
    gantt: 'Figure — deployment schedule (critical path outlined, milestones)', sheetsTitle: 'Drawing sheets', sheet: (num: string, title: string) => `Sheet ${num} — ${title}`,
    sheetsFailed: 'Drawing sheets could not be generated for this project state.', generatedBy: 'Generated by AIDC Studio',
  },
  ko: {
    contents: '목차', topology: '그림 — 패브릭별 네트워크 토폴로지 (티어 · 스위치 수 · 링크)', oneLine: '그림 — 전력 단선도 (A / B / 예비 경로)',
    gantt: '그림 — 배포 일정 (핵심 경로 강조 · 마일스톤)', sheetsTitle: '도면 시트', sheet: (num: string, title: string) => `시트 ${num} — ${title}`,
    sheetsFailed: '현재 프로젝트 상태로는 도면 시트를 생성할 수 없습니다.', generatedBy: 'AIDC Studio 생성',
  },
} satisfies Record<Locale, Record<string, unknown>>;

const NUMERIC_CELL = /^[-+]?[$₩]?\d[\d,.]*\s?(%|kW|MW|kVA|MVA|m|m²|kg\/m²|LPM|Tbps|GB\/s|Gb\/s|h|wk|주|d|days|일|°C|×10⁸)?$/;

function numericColumns(rows: (string | number)[][]): number[] {
  if (!rows.length) return [];
  const cols: number[] = [];
  for (let i = 0; i < rows[0].length; i++) {
    const vals = rows.map((r) => String(r[i] ?? '').replace(/\*\*/g, '').trim()).filter((v) => v && v !== '-' && v !== '∞');
    if (vals.length && vals.every((v) => typeof v === 'number' || NUMERIC_CELL.test(v))) cols.push(i);
  }
  return cols;
}

export function renderDesignDocumentHtml(project: Project, analysis: ProjectAnalysis, opts: DesignDocHtmlOptions = {}): string {
  const doc = buildDesignDocumentBlocks(project, analysis, opts);
  const L = doc.locale;
  const H = HTML_STRINGS[L];
  const S = docStrings(L);
  const toc: HtmlTocEntry[] = [];
  const out: string[] = [];
  const ids = new Map<string, number>();
  const uniqueId = (base: string) => {
    const k = ids.get(base) ?? 0;
    ids.set(base, k + 1);
    return k ? `${base}-${k + 1}` : base;
  };
  let chapter: DocChapter | undefined;
  let inSection = false;
  let list: string[] = [];
  let metaTable = '';
  let seenH2 = false;
  const flushList = () => {
    if (list.length) out.push(`<ul>${list.map((x) => `<li>${x}</li>`).join('')}</ul>`);
    list = [];
  };
  const figure = (svg: string, caption: string, id?: string) => `<figure${id ? ` id="${id}"` : ''}>${svg}<figcaption>${escapeHtml(caption)}</figcaption></figure>`;

  const renderBlock = (b: DocBlock) => {
    if (b.k === 'li') {
      list.push(inlineMarkup(b.text));
      return;
    }
    if (b.k === 'blank') return;
    flushList();
    switch (b.k) {
      case 'h': {
        if (b.level === 1) return; // title band
        if (b.level === 2) {
          seenH2 = true;
          if (inSection) out.push('</section>');
          chapter = b.chapter;
          const id = uniqueId(`ch-${b.chapter ?? htmlId(b.text)}`);
          toc.push({ id, label: b.text, level: 1 });
          out.push(`<section class="chapter" id="${id}-section"><h2 id="${id}">${escapeHtml(b.text)}</h2>`);
          inSection = true;
          return;
        }
        const id = uniqueId(`${chapter ?? 'doc'}-${htmlId(b.text)}`);
        if (b.level === 3) toc.push({ id, label: b.text, level: 2 });
        out.push(`<h${b.level} id="${id}">${escapeHtml(b.text)}</h${b.level}>`);
        return;
      }
      case 'p': {
        if (!b.text.trim()) return;
        if (b.text.startsWith('> ')) out.push(`<p class="note">${inlineMarkup(b.text.slice(2))}</p>`);
        else out.push(`<p>${inlineMarkup(b.text)}</p>`);
        return;
      }
      case 'user': {
        const paras = b.text.split(/\n\s*\n/).map((x) => x.trim()).filter(Boolean);
        for (const para of paras) out.push(`<p>${escapeHtml(para).replace(/\n/g, '<br>')}</p>`);
        return;
      }
      case 'table': {
        const rows = b.rows.map((r) => r.map((cell) => inlineMarkup(String(cell))));
        const html = htmlTable(b.headers, rows, { rawCols: b.headers.map((_, i) => i), numericCols: numericColumns(b.rows), className: seenH2 ? undefined : 'meta' });
        if (!seenH2) metaTable = html;
        else out.push(html);
        return;
      }
      case 'diagram': {
        if (b.kind === 'topology') {
          out.push(figure(fabricTopologySvg(analysis.network.fabrics, { locale: L, modelOf: (id) => findCatalogItem(id)?.model }), H.topology, 'fig-topology'));
        } else if (b.kind === 'one-line') {
          out.push(figure(oneLineSvg(analysis.power.oneLine, { locale: L, title: S.power.oneLine }), H.oneLine, 'fig-one-line'));
        } else {
          out.push(figure(scheduleGanttSvg(analysis.schedule, { locale: L, phaseLabel: (ph) => S.deploy.phase[ph] ?? ph }), H.gantt, 'fig-gantt'));
        }
        return;
      }
      case 'sheets': {
        if (opts.includeDrawings === false) return;
        const id = uniqueId(`${chapter ?? 'doc'}-drawings`);
        toc.push({ id, label: H.sheetsTitle, level: 2 });
        out.push(`<h3 id="${id}">${escapeHtml(H.sheetsTitle)}</h3>`);
        try {
          const sheets = generateDrawings(project, analysis, { locale: L, sheets: ['plan', 'rack-elevation'] });
          const pick = [sheets.find((x) => x.kind === 'plan'), sheets.find((x) => x.kind === 'rack-elevation')].filter((x): x is NonNullable<typeof x> => !!x);
          for (const sh of pick) {
            const svg = sh.svg.replace(/^<\?xml[^>]*>\s*/, '');
            out.push(figure(`<img alt="${escapeHtml(sh.title)}" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}">`, H.sheet(sh.number, sh.title)));
          }
          if (!pick.length) out.push(`<p class="note">${escapeHtml(H.sheetsFailed)}</p>`);
        } catch {
          out.push(`<p class="note">${escapeHtml(H.sheetsFailed)}</p>`);
        }
        return;
      }
    }
  };
  for (const b of doc.blocks) renderBlock(b);
  flushList();
  if (inSection) out.push('</section>');

  const generated = analysis.generatedAt.slice(0, 19).replace('T', ' ');
  const subtitle = [project.client, generated].filter(Boolean).join(' · ');
  const body = `${metaTable}\n${out.join('\n')}`;
  return htmlPage(doc.title, body, L, { subtitle, toc, tocTitle: H.contents, footer: `${project.name} · ${generated} · ${H.generatedBy}` });
}
