import type { DocStrings } from './strings.en.ts';

/** Korean strings for the design-document generator (DECISIONS-v2 #10: selectable, English is the default). */
export const KO: DocStrings = {
  locale: 'ko-KR',
  docTitle: (project) => `${project} — 기술 설계서`,
  meta: { item: '항목', value: '내용', client: '고객', author: '작성', generated: '생성 시각', projectId: '프로젝트 ID', na: '-' },
  chapters: {
    overview: '1. 개요·과제·목표',
    site: '2. 사이트 및 바닥 시스템',
    layout: '3. 물리 배치 및 냉각 전략',
    network: '4. 네트워크 설계',
    control: '5. 중앙 집중 컨트롤 플레인',
    storage: '6. 스토리지',
    power: '7. 전력 공급',
    resiliency: '8. 전력 회복력',
    bom: '9. BOM 및 전력 추정',
    deploy: '10. 배포 및 인수',
    sources: '11. 가정 및 데이터 출처',
  },
  overview: {
    metric: '지표', value: '값',
    halls: '데이터 홀', racks: '랙 (GPU 랙)', gpus: 'GPU', itLoad: 'IT 설계 부하', facility: '시설 전력 (설계 조건)',
    pue: 'PUE (연평균 / 설계)', capex: 'CAPEX', capexPerGpu: 'GPU당 CAPEX', rfs: '최종 서비스 개시 (RFS)', issues: '검증 이슈',
    issuesVal: (e, w) => `오류 ${e} · 경고 ${w}`,
    challengesTitle: '1.1 설계 과제',
    challengesIntro: '고밀도 AI 컴퓨트는 시설의 모든 분야를 동시에 바꾼다. 본 설계가 다루는 주요 과제:',
    chDensity: (kw, kwm2) => `**전력 공급** — 랙당 명판 최대 ${kw} kW, 상면 평균 밀도 ${kwm2} kW/m²는 버스웨이급 배전, EDPP 정격 보호, 부하 평활화를 요구한다.`,
    chCooling: (liq, air) => `**냉각** — IT 발열의 ${liq}는 직접 액랭(TCS/FWS 루프)으로 포집되고 나머지 ${air}는 공조기가 제거하므로, 핫에일 컨테인먼트와 온수 설계점이 칠러 용량과 PUE를 결정한다.`,
    chSpace: (racks, load) => `**물리 공간 및 구조** — 랙 ${racks}대, 점하중 최대 ${load} kg/m²는 슬래브 또는 보강 바닥과 전력·광·냉각수의 오버헤드 경로를 필요로 한다.`,
    chCable: (cables, longest) => `**케이블 관리** — 스케일아웃/프런트엔드 케이블 ${cables}본, 최장 경로 ${longest} m는 30/50/500 m 도달 한계와 트레이 충진율을 지켜야 한다.`,
    chOps: '**에너지·안전·운영** — PUE/WUE 목표, 누수 감지, 아크 플래시, 동시 유지보수성이 이중화 선택을 좌우한다. 아래 장에서 각 항목을 정량화한다.',
    goalsTitle: '1.2 목표 워크로드',
    goalsIntro: '시설은 다음 워크로드 블루프린트를 기준으로 산정되며, 시뮬레이션 결과가 설계의 용량·에너지 목표를 정의한다.',
    wl: {
      metric: '지표', value: '값', gpus: '할당 GPU', step: '스텝 시간 (연산 / 통신)', throughput: '처리량', mfu: 'MFU', goodput: 'Goodput', ttt: '학습 소요',
      gpusReq: '필요 GPU (목표 부하)', maxReq: '최대 처리 요청', ttft: 'TTFT / TPOT', power: '평균 / 피크 전력',
      energy: (days) => `에너지 (${days}일, PUE 포함)`, eff: '에너지 효율', days: '일', tps: 'tokens/s', rps: 'req/s', tpkwh: 'tokens/kWh',
    },
  },
  site: {
    item: '항목', value: '값', site: '사이트', elevation: '표고', designAmbient: '설계 외기 (건구 / 습구, 0.4 %)', annualMean: '연평균 기온',
    econHours: '이코노마이저 가용 시간', tariff: '전력 요금', carbon: '탄소 배출 계수', hPerYear: 'h/년', profile: '전기 프로파일', growth: '증설 방식',
    growthVal: { phased: '단계별 증설', 'single-build': '일괄 구축' },
    floorTitle: '2.1 바닥 시스템 — 이중마루 vs 콘크리트 슬래브',
    floorIntro: '랙 규모 액랭 시스템은 0.6 × 1.2 m 설치 면적에 1.2–1.6 t이다. 홀별 바닥 시스템:',
    floorSlab: '콘크리트 슬래브 (공기·전력·냉각수 오버헤드)',
    floorRaised: (h) => `이중마루 ${h} m (바닥 급기 플레넘 / 배관)`,
    hallsTitle: '2.2 상면 (데이터 홀)',
    hall: '홀', size: '크기 (W × D)', area: '면적', height: '천장고 / 플레넘', floorLoad: '허용 하중', itBudget: 'IT 전력 예산', coolingBudget: '액랭 / 공랭 예산', floorSystem: '바닥 시스템',
    spaceTitle: '2.3 상면 활용',
    rackCount: '랙', gpuCount: 'GPU', occupied: '설치 면적', utilisation: '상면 활용률 (이격 포함)', density: 'IT 밀도', maxLoad: '최대 바닥 하중', violations: '이격 위반',
    keepoutTitle: '2.4 금지 구역 (기둥·문·피난)',
    keepout: '금지 구역', kind: '유형', sizePos: '크기 / 위치',
  },
  layout: {
    patternTitle: '3.1 배치 패턴',
    patternHac: (n, roofs, ducted) => `핫에일 컨테인먼트 아일랜드형 랙 열: 컨테인먼트 ${n}개 (지붕 ${roofs}, 천장 플레넘 덕트 연결 ${ducted}). 리프·CDU·관리 랙은 열을 공유하고 스파인/코어는 서비스 열에 둔다.`,
    patternCac: (n) => `콜드에일 컨테인먼트 랙 열 (컨테인먼트 ${n}개); 환기는 실내에서 혼합.`,
    patternNone: '컨테인먼트 없는 랙 열 (개방 냉·열복도).',
    spinePlacement: (v, room) => `스파인/코어 배치: **${v}**${room ? ' (별도 네트워크실 MMR)' : ''}.`,
    placementVal: { distributed: '포드별 분산', 'central-end': '홀 끝 중앙 열', 'central-center': '홀 중앙 열', 'separate-room': '별도 실', centralized: '홀 끝 중앙 열', 'per-hall': '포드별 분산' },
    equipmentTitle: '3.2 배치 장비',
    equipment: '장비', category: '분류',
    strategyTitle: '3.3 냉각 전략',
    strategyIntro: (liq, air) => `직접 액랭 + 공랭 하이브리드: IT 발열 ${liq} kW는 CDU를 거쳐 기술 냉각 계통(TCS)으로, ${air} kW는 CRAH / 팬월을 통해 공기측으로 제거한다.`,
    designTemp: '설계 온도', fws: 'FWS 공급 / 환수', tcs: 'TCS 공급', supplyAir: '급기', rejection: '열 방출 방식', economizer: ' + 이코노마이저',
    rejectionVal: { 'air-cooled-chiller': '공랭 칠러', 'water-cooled-chiller': '수랭 칠러', 'dry-cooler': '드라이쿨러', hybrid: '하이브리드 (칠러 + 드라이쿨러)' },
    balanceTitle: '3.4 열 수지',
    liquidHeat: '액체 발열 (CDU → TCS)', airHeat: '공기 발열 (CRAH)', cdu: 'CDU', crah: 'CRAH', chiller: '칠러', dryCooler: '드라이쿨러', fwsFlow: 'FWS 유량', pumpFanComp: '펌프 / 팬 / 압축기 (설계)',
    annualMech: '연평균 기계 동력', ppue: 'pPUE (냉각)', wue: 'WUE',
    cduVal: (u, kw, red, lpm) => `${u} × ${kw} kW (${red}) · TCS 유량 ${lpm} LPM`,
    crahVal: (u, kw, red, af, req) => `${u} × ${kw} kW (${red}) · 풍량 ${af} / 필요 ${req} m³/s`,
    unitVal: (u, kw, req) => `${u} × ${kw} kW · 부하 ${req} kW`,
    pod: '포드', podLiquid: '액체 발열', podCdu: 'CDU 배치 / 필요', podCap: 'CDU 용량',
    cfdTitle: '3.5 기류·열 시뮬레이션 결과',
    maxInlet: '최대 랙 흡기 온도', rci: 'RCI (HI)', rti: 'RTI',
  },
  network: {
    typesTitle: '4.1 네트워크 종류',
    typesIntro: '물리적으로 분리된 네 종류의 네트워크를 계획한다:',
    scaleOut: (fabric, topo, os) => `**스케일아웃 (동서, GPU 백엔드)** — ${fabric}, ${topo}, 리프 오버서브스크립션 ${os}:1. GPU당 NIC 1개, NCCL/RCCL 집합 통신 전담.`,
    frontend: (fabric, os, on) => `**프런트엔드 (남북)** — ${on ? `${fabric}, 오버서브스크립션 ${os}:1. 사용자/API 트래픽, 오케스트레이션, 컨버지드 시 스토리지.` : '계획 없음 (스케일아웃 패브릭에 컨버지드).'}`,
    storage: (fabric, os, on) => `**스토리지** — ${on ? `${fabric}, 오버서브스크립션 ${os}:1. GPU당 9–17 GB/s 기준 산정.` : '프런트엔드 네트워크에 컨버지드.'}`,
    oob: (fabric, on) => `**대역외 관리 (OOB)** — ${on ? `${fabric}. 모든 BMC·스위치 콘솔·PDU.` : '계획 없음.'}`,
    topoTitle: '4.2 토폴로지 — 팻 트리와 레일 최적화',
    topoVal: { 'rail-optimized': '레일 최적화 리프-스파인', 'fat-tree': '팻 트리 (Clos)', 'leaf-spine': '리프-스파인' },
    topoRail: '레일 최적화: 포드 내 모든 노드의 k번째 NIC를 k번째 리프에 연결해 GPU-k ↔ GPU-k 트래픽이 1홉으로 끝나고, PXN이 집합 통신 대부분을 NVLink 도메인 + 레일 하나 안에 가둔다.',
    topoTree: '팻 트리 / Clos: 모든 리프가 모든 스파인에 연결되고 루트 방향 용량이 유지되어 어떤 순열도 라우팅할 수 있다.',
    suTitle: '4.3 스케일러블 유닛',
    suIntro: (pods, gpuRacks, gpus) => `배포 단위(포드) ${pods}개, GPU 랙 ${gpuRacks}대, GPU ${gpus}기. 포드마다 자체 리프를 갖고 스파인/코어는 공유한다.`,
    osTitle: '4.4 오버서브스크립션',
    osIntro: '한 계층의 오버서브스크립션 = 서버 방향 대역폭 ÷ 스파인 방향 대역폭 (다운:업 = N:1로 표기). 64 × 800G 리프에서 서버 32 / 스파인 32 포트는 1:1(용량 기준 논블로킹), 48 / 16 포트는 3:1. NVIDIA는 같은 3:1을 "1:3 blocking"으로, AMD의 "1:1.16"은 언더서브스크립션(업링크 = 다운링크 × 1.16)을 뜻한다.',
    osProject: (so, fe, st) => `본 설계: 스케일아웃 ${so}:1, 프런트엔드 ${fe}:1, 스토리지 ${st}:1.`,
    fabric: '패브릭', endpoints: '엔드포인트', tiers: '계층 (스위치 수)', switches: '총 스위치', os: '오버서브', bisection: '이분 대역폭', hops: '홉', power: '전력', racks: '랙',
    endpointLinks: (n) => `엔드포인트 링크 ${n}`,
    cableTitle: '4.5 케이블 BOM',
    cableType: '케이블 유형', qty: '수량', totalLen: '총 길이', avgLen: '평균 길이', optics: '광모듈',
    commEff: (v) => `스케일아웃 집합 통신 효율 (이상적 논블로킹 IB XDR 대비): **${v}**`,
    optPower: (kw, usd) => `광모듈 전력 (스위치 측): ${kw} kW · 네트워크 장비 + 케이블 비용: ${usd}`,
  },
  control: {
    intro: '중앙 집중 컨트롤 플레인은 GPU 패브릭과 분리된 전용 관리 랙과 대역외 네트워크에서 운영한다:',
    items: [
      '**프로비저닝 및 인벤토리** — 베어메탈 프로비저닝, 펌웨어 기준선, 모든 노드·스위치·PDU의 BMC/OOB 도달성.',
      '**스케줄링** — Slurm 및/또는 Kubernetes. 계획된 패브릭(레일/리프 소속)에서 생성한 토폴로지 파일로 잡을 최소 스위치 집합에 배치.',
      '**패브릭 관리** — 서브넷 매니저 / UFM(인피니밴드) 또는 NetQ형 텔레메트리(이더넷). 혼잡 제어(DCQCN, 단일 우선순위 PFC)와 적응 라우팅 정책을 코드로 배포.',
      '**시설 연동** — BMS/EPMS/DCIM 데이터(랙 전력, 흡기 온도, CDU 유량/ΔP, 누수 감지)를 잡 텔레메트리와 연계해 동적 전력 배분.',
    ],
    racks: (mgmt, oobOn) => `배치된 관리 랙: ${mgmt}. OOB 네트워크: ${oobOn ? '계획됨' : '계획 없음'}.`,
  },
  storage: {
    intro: '학습 체크포인트·데이터셋·추론 모델 가중치는 전용 스토리지 랙의 병렬 파일시스템에서 제공한다:',
    racks: (n, tb, gbps) => `배치된 스토리지 랙: ${n} (카탈로그 기준 가용 용량 ${tb} TB, 합산 처리량 ${gbps} GB/s).`,
    perGpu: (v) => `GPU당 스토리지 대역: ${v} GB/s (설계 지침 GPU당 9–17 GB/s; 체크포인트 쓰기 버스트가 지배).`,
    network: (on, fabric, os) => (on ? `전용 스토리지 네트워크: ${fabric}, 오버서브스크립션 ${os}:1.` : '스토리지 트래픽은 프런트엔드 네트워크에 컨버지드 (전용 패브릭 없음).'),
    federated: '중앙 집중 스토리지(사이트당 단일 네임스페이스)를 가정하며 연합형 계층(오브젝트/아카이브)은 본 설계 범위 밖이다.',
  },
  power: {
    feedTitle: '7.1 수전 회선',
    feed: '회선', voltage: '전압', capacity: '용량', substation: '변전소', available: '가용일',
    required: (v) => `필요 수전 용량 (설계 조건, PF 0.95): **${v} MVA**`,
    firm: (total, firm) => `전체 수전 용량: ${total} MVA · N−1 확정 용량: **${firm} MVA** (독립 변전소 기준, 최대 변전소 그룹 제외)`,
    loadTitle: '7.2 부하 구성',
    load: '부하 구성', kw: 'kW', nameplate: 'IT 명판 (랙 + 네트워크)', design: (d) => `IT 설계 (다양성 계수 ${d})`, peak: 'IT 순간 피크 (EDPP)', network: '네트워크 (스위치 + 광모듈)',
    mechanical: '기계 설비 (설계 조건)', losses: '손실 + 부대 설비', total: '**시설 합계**',
    hall: '홀', itLoad: 'IT 부하', budget: '공급 가능', util: '사용률',
    distTitle: '7.3 배전 및 단선결선도',
    dist: (v, kind, profile) => `분배 전압 ${v} V (${profile}), 랙까지 ${kind}.`,
    distVal: { busway: '오버헤드 A/B 버스웨이 + 탭오프', rpp: '원격 분전반(RPP) + 휩', hybrid: 'GPU 열은 버스웨이, 지원 랙은 RPP' },
    profileVal: { iec: 'IEC 프로파일', nec: 'NEC 프로파일', kr: 'KR 프로파일' },
    oneLine: '단선결선도 (One-line)',
  },
  resiliency: {
    intro: '이중화는 하위 계통별로 적용하며, 표는 설계 부하 기준 설치 용량과 필요 용량을 보여준다.',
    system: '설비', redundancy: '이중화', units: '수량', unitCap: '단위 용량', installed: '설치 용량', required: '필요 용량',
    ups: 'UPS', generator: '발전기', transformer: '변압기', rpp: 'RPP', busway: '버스웨이', maxLoading: (v) => `최대 부하율 ${v}`,
    strategiesTitle: '8.1 핵심 전략',
    battery: (min) => `UPS 배터리 ${min}분 (발전기 기동·절체 시간 확보).`,
    mechUps: (on) => `기계 부하(CDU 펌프, CRAH 팬) UPS 백업: ${on ? '예 — 절체 중 냉각 지속 보장' : '아니오 — TCS/FWS 루프의 열 관성으로 절체 구간 대응'}.`,
    smoothing: { none: '전력 평활화: 없음 — 수전 측이 학습 부하 변동 전체(위 피크까지의 EDPP 과도)를 본다.', 'rack-level': '전력 평활화: 랙 레벨 에너지 저장(파워셸프 커패시터/배터리)이 버스웨이·수전 측 램프율과 피크를 제한한다.', bess: '전력 평활화: 중전압 모선의 시설 BESS가 부하 변동을 완충하고 순간정전 극복·수요 반응을 제공한다.' },
    peak: (peak, design) => `순간 피크(EDPP) ${peak} kW 대 설계 부하 ${design} kW — 차단기·버스웨이는 피크, UPS·발전기는 설계 부하 기준.`,
    firm: '수전 확정 용량은 변전소 간 N−1로 평가하며(7.1 참조) 변전소 1개 상실이 발전기 용량을 넘어서는 안 된다.',
  },
  bom: {
    domain: '분야', amount: '금액', share: '비중',
    domainLabel: { it: 'IT', network: '네트워크', cabling: '케이블링', power: '전력', cooling: '냉각', facility: '시설', labor: '인건비', contingency: '예비비' },
    metric: '지표', value: '값', capex: 'CAPEX', opex: '연간 OPEX (에너지 + 유지보수 2 %)', energy: '연간 에너지', tco: '5년 TCO', perGpu: 'GPU당 CAPEX', perMw: 'IT MW당 CAPEX', fx: '통화 환산',
    fxVal: (krw, rate, isKrw) => (isKrw ? `₩${krw}억` : `₩${krw}억 (${rate} KRW/USD)`),
    estimateTitle: '9.1 전력 추정',
    estimateIntro: (design, facility, avg, mwh) => `IT 설계 부하 ${design} kW → 설계 조건 시설 전력 ${facility} kW; 연평균 시설 전력 ${avg} kW → IT 평균 부하율 85 % 기준 연간 ${mwh} MWh.`,
    detailTitle: '9.2 BOM 상세',
    item: '품목', qty: '수량', unit: '단위', unitPrice: '단가', total: '금액', leadTime: '리드타임', source: '출처', weeks: '주',
    deployNote: '웨이브별 자재 목록(BOM by wave)과 랙 플랜은 배포 번들의 별도 산출물로 제공된다.',
  },
  deploy: {
    milestone: '마일스톤', date: '일자',
    phase: { procurement: '조달', site: '설계·부지', power: '전력', cooling: '냉각', it: 'IT 설치', network: '네트워크', commissioning: '커미셔닝', handover: '인도' },
    ramp: '용량 램프', cumGpus: '누적 GPU', cumIt: '누적 IT',
    critical: (v) => `크리티컬 패스 작업: ${v}`,
    labor: (h, crews, size, days, hours) => `총 투입 인시: ${h} h (작업조 ${crews}, 조당 ${size}명, 주 ${days}일 × ${hours}시간)`,
    issuesTitle: '10.1 검증 이슈 및 리스크',
    noIssues: '검출된 이슈가 없습니다.',
    issuesLangNote: '_일부 엔진 메시지는 한국어로만 제공됩니다._',
    severity: '심각도', domain: '분야', message: '내용', suggestion: '권고',
    sev: { error: '오류', warning: '경고', info: '정보' },
    acceptanceTitle: '10.2 인수',
    acceptance: [
      '**L1–L3** — 공장·현장 부품 시험, UPS·발전기·CDU·CRAH·칠러의 정격 부하 시스템 커미셔닝.',
      '**L4 통합 시스템** — 설계 부하 IT 로드뱅크로 장애 시나리오(수전 상실, 발전기 고장, RPP/버스웨이 0–4구간 상실, CDU 펌프 절체) 시험.',
      '**L5 클러스터 검증** — 노드 진단(DCGM diag / AGFHC), 레일별 RDMA 대역(ib_write_bw), 임계값 기준 nccl-tests / rccl-tests 스윕(all_reduce busbw, all-to-all ≥ NIC 선속도의 약 0.85배), 스토리지 IOR/FIO, 랙 흡기 온도·CDU 유량/ΔP 점검.',
    ],
  },
  sources: {
    equipment: '장비', vendorModel: '제조사 / 모델', dataSource: '데이터 출처', notes: '비고', cable: '케이블', reach: '최대 도달', source: '출처',
    methodTitle: '계산 방법 요약',
    methods: [
      '- **전력**: IT 설계 = 랙 명판 × 다양성 계수 + 네트워크. UPS 효율 97 %, 변압기 손실 1.5 %, 배전 손실 1 %, 전기실 냉방 = (UPS + 변압기 손실) × 30 %. N−1 확정 수전 = 전체 − 최대 변전소 그룹.',
      '- **냉각**: 랙 발열을 액체 비율(liquidFraction)로 CDU/공기로 분리. 유량은 카탈로그 항목별 온도-액체 유량 / 풍량 곡선(liquidFlowCurve / airflowCurve) 보간. 칠러 COP 3.3(설계) / 5.0(연평균), 이코노마이저 시간 동안 부하의 1/25 동력.',
      '- **네트워크**: 리프 다운링크 d = ⌊k·o/(o+1)⌋, 레일 최적화 시 포드별 레일 수 배수로 리프 산정, L ≤ k이면 2계층. 케이블 길이 = 맨해튼 거리 × 경로계수 + 트레이 상하강 + 양단 여유.',
      '- **워크로드**: 학습 FLOPs = 6·N·D, 스텝 시간 = 연산(PP 버블 포함) + TP/PP/DP/EP 통신. Goodput = 1 − δ/τ − (τ/2 + δ + R)/MTBF. 추론 decode는 메모리 대역폭, prefill은 연산 한계로 모델링.',
      '- **비용**: 카탈로그 단가(추정 포함) × 수량 + 합성 항목(배터리, 배관, 시설) + 인건비 + 예비비. OPEX = 평균 IT 85 % 부하 에너지 + CAPEX 2 %.',
      '- **일정**: 장납기(≥ 26주) 품목은 착수일 발주, 작업량/작업조 역량으로 기간 산정, 웨이브 간 작업조 공유, CPM으로 크리티컬 패스 산출.',
    ],
    disclaimer: '> 본 문서의 가격·리드타임·일부 사양은 계획 단계 추정치입니다. 확정 견적 및 제조사 데이터시트로 갱신해야 합니다.',
  },
  sourceLabel: {
    'open-standard': '공개 표준 (인용 문서·개정판)',
    'vendor-datasheet': '제조사 데이터시트',
    'public-spec': '공개 사양',
    estimate: '추정치 (견적 확정 시 갱신)',
    announced: '발표 사양 (출시 전)',
    user: '사용자 정의',
  },
  units: { kw: 'kW', mw: 'MW', m: 'm', m2: 'm²', mva: 'MVA', lpm: 'LPM', kgm2: 'kg/m²', tbps: 'Tbps', days: '일' },
  yes: '예', no: '아니오',
};
