/**
 * English strings for the design-document generator (default locale — DECISIONS-v2 #10).
 * `strings.ko.ts` must provide every key of this object (typed as DocStrings).
 */
export const EN = {
  locale: 'en-US',
  docTitle: (project: string) => `${project} — Technical Design Document`,
  meta: { item: 'Item', value: 'Value', client: 'Client', author: 'Author', generated: 'Generated', projectId: 'Project ID', na: '-' },
  chapters: {
    overview: '1. Overview, challenges & goals',
    site: '2. Site & floor system',
    layout: '3. Physical layout & cooling strategy',
    network: '4. Network design',
    control: '5. Centralized control plane',
    storage: '6. Storage',
    power: '7. Power supply',
    resiliency: '8. Power resiliency',
    bom: '9. BOM & power estimate',
    deploy: '10. Deployment & acceptance',
    sources: '11. Assumptions & data sources',
  },
  // ── 1 overview ──
  overview: {
    metric: 'Metric', value: 'Value',
    halls: 'Data halls', racks: 'Racks (GPU racks)', gpus: 'GPUs', itLoad: 'IT design load', facility: 'Facility power (design conditions)',
    pue: 'PUE (annualised / design)', capex: 'CAPEX', capexPerGpu: 'CAPEX per GPU', rfs: 'Final ready-for-service (RFS)', issues: 'Validation issues',
    issuesVal: (e: number, w: number) => `${e} errors · ${w} warnings`,
    challengesTitle: '1.1 Design challenges',
    challengesIntro: 'High-density AI compute changes every discipline of the facility at once. The main challenges this design addresses:',
    chDensity: (kw: string, kwm2: string) => `**Power delivery** — rack loads of up to ${kw} kW nameplate and an average white-space density of ${kwm2} kW/m² require busway-class distribution, EDPP-rated protection and load smoothing.`,
    chCooling: (liq: string, air: string) => `**Cooling** — ${liq} of the IT heat is captured by direct liquid cooling (TCS/FWS loops); the remaining ${air} is removed by air handlers, so hot-aisle containment and warm-water design points decide chiller size and PUE.`,
    chSpace: (racks: number, load: string) => `**Physical space & structure** — ${racks} racks with point loads up to ${load} kg/m² call for slab or reinforced floor and overhead pathways for power, fibre and coolant.`,
    chCable: (cables: string, longest: string) => `**Cable management** — ${cables} scale-out/front-end cables with a longest run of ${longest} m must respect 30/50/500 m reach limits and tray fill.`,
    chOps: '**Energy, safety, operations** — PUE/WUE targets, leak detection, arc-flash and concurrent maintainability shape redundancy choices; the sections below quantify each.',
    goalsTitle: '1.2 Target workloads (goals)',
    goalsIntro: 'The facility is sized for the following workload blueprints; the simulation results define the capacity and energy goals of the design.',
    wl: {
      metric: 'Metric', value: 'Value', gpus: 'GPUs allocated', step: 'Step time (compute / comm)', throughput: 'Throughput', mfu: 'MFU', goodput: 'Goodput', ttt: 'Time to train',
      gpusReq: 'GPUs required (target load)', maxReq: 'Max request rate', ttft: 'TTFT / TPOT', power: 'Average / peak power',
      energy: (days: number | string) => `Energy (${days} days, incl. PUE)`, eff: 'Energy efficiency', days: 'days', tps: 'tokens/s', rps: 'req/s', tpkwh: 'tokens/kWh',
    },
  },
  // ── 2 site ──
  site: {
    item: 'Item', value: 'Value', site: 'Site', elevation: 'Elevation', designAmbient: 'Design ambient (dry / wet bulb, 0.4 %)', annualMean: 'Annual mean temperature',
    econHours: 'Economizer hours', tariff: 'Electricity tariff', carbon: 'Carbon intensity', hPerYear: 'h/yr', profile: 'Electrical profile', growth: 'Growth pattern',
    growthVal: { phased: 'phased (wave by wave)', 'single-build': 'single build' },
    floorTitle: '2.1 Floor system — raised floor vs concrete slab',
    floorIntro: 'Rack-scale liquid-cooled systems weigh 1.2–1.6 t on a 0.6 × 1.2 m footprint. The floor system per hall:',
    floorSlab: 'concrete slab (overhead air, power and coolant)',
    floorRaised: (h: string) => `raised floor ${h} m (underfloor supply plenum / piping)`,
    hallsTitle: '2.2 White space (data halls)',
    hall: 'Hall', size: 'Size (W × D)', area: 'Area', height: 'Clear height / plenum', floorLoad: 'Allowable floor load', itBudget: 'IT power budget', coolingBudget: 'Liquid / air cooling budget', floorSystem: 'Floor system',
    spaceTitle: '2.3 Space utilisation',
    rackCount: 'Racks', gpuCount: 'GPUs', occupied: 'Footprint', utilisation: 'White-space utilisation (incl. clearances)', density: 'IT density', maxLoad: 'Max floor load', violations: 'Clearance violations',
    keepoutTitle: '2.4 Keepouts (columns, doors, egress)',
    keepout: 'Keepout', kind: 'Kind', sizePos: 'Size / position',
  },
  // ── 3 layout & cooling ──
  layout: {
    patternTitle: '3.1 Pattern of organisation',
    patternHac: (n: number, roofs: number, ducted: number) => `Rows of racks in hot-aisle containment islands: ${n} containments (${roofs} with roof panels, ${ducted} ducted to the ceiling plenum). Leaves, CDUs and management racks share the rows; spines/cores sit in the services row.`,
    patternCac: (n: number) => `Rows of racks with cold-aisle containment (${n} containments); return air mixes in the room.`,
    patternNone: 'Rows of racks without containment (open hot/cold aisles).',
    spinePlacement: (v: string, room: boolean) => `Spine/core placement: **${v}**${room ? ' in a separate network room (MMR)' : ''}.`,
    placementVal: { distributed: 'distributed per pod', 'central-end': 'central row at the hall end', 'central-center': 'central row in the hall centre', 'separate-room': 'separate room', centralized: 'central row at the hall end', 'per-hall': 'distributed per pod' },
    equipmentTitle: '3.2 Placed equipment',
    equipment: 'Equipment', category: 'Category',
    strategyTitle: '3.3 Cooling strategy',
    strategyIntro: (liq: string, air: string) => `Hybrid direct-liquid + air: ${liq} kW of IT heat goes to the technology cooling system (TCS) through CDUs, ${air} kW to the air side through CRAHs / fan walls.`,
    designTemp: 'Design temperature', fws: 'FWS supply / return', tcs: 'TCS supply', supplyAir: 'Supply air', rejection: 'Heat rejection', economizer: ' + economizer',
    rejectionVal: { 'air-cooled-chiller': 'air-cooled chiller', 'water-cooled-chiller': 'water-cooled chiller', 'dry-cooler': 'dry cooler', hybrid: 'hybrid (chiller + dry cooler)' },
    balanceTitle: '3.4 Heat balance',
    liquidHeat: 'Liquid heat (CDU → TCS)', airHeat: 'Air heat (CRAH)', cdu: 'CDU', crah: 'CRAH', chiller: 'Chiller', dryCooler: 'Dry cooler', fwsFlow: 'FWS flow', pumpFanComp: 'Pumps / fans / compressors (design)',
    annualMech: 'Annual-average mechanical power', ppue: 'pPUE (cooling)', wue: 'WUE',
    cduVal: (u: number, kw: string, red: string, lpm: string) => `${u} × ${kw} kW (${red}) · TCS flow ${lpm} LPM`,
    crahVal: (u: number, kw: string, red: string, af: string, req: string) => `${u} × ${kw} kW (${red}) · airflow ${af} / required ${req} m³/s`,
    unitVal: (u: number, kw: string, req: string) => `${u} × ${kw} kW · load ${req} kW`,
    pod: 'Pod', podLiquid: 'Liquid heat', podCdu: 'CDUs placed / required', podCap: 'CDU capacity',
    cfdTitle: '3.5 Airflow & thermal simulation results',
    maxInlet: 'Max rack inlet temperature', rci: 'RCI (HI)', rti: 'RTI',
  },
  // ── 4 network ──
  network: {
    typesTitle: '4.1 Network types',
    typesIntro: 'Four physically separate networks are planned:',
    scaleOut: (fabric: string, topo: string, os: string) => `**Scale-out (east-west, GPU back-end)** — ${fabric}, ${topo}, leaf oversubscription ${os}:1. One NIC per GPU; carries NCCL/RCCL collectives.`,
    frontend: (fabric: string, os: string, on: boolean) => `**Front-end (north-south)** — ${on ? `${fabric}, oversubscription ${os}:1; user/API traffic, orchestration and, when converged, storage.` : 'not planned (converged on the scale-out fabric).'}`,
    storage: (fabric: string, os: string, on: boolean) => `**Storage** — ${on ? `${fabric}, oversubscription ${os}:1; sized from 9–17 GB/s per GPU.` : 'converged on the front-end network.'}`,
    oob: (fabric: string, on: boolean) => `**Out-of-band management** — ${on ? `${fabric}; every BMC, switch console and PDU.` : 'not planned.'}`,
    topoTitle: '4.2 Topology — fat tree and rail optimisation',
    topoVal: { 'rail-optimized': 'rail-optimized leaf-spine', 'fat-tree': 'fat tree (Clos)', 'leaf-spine': 'leaf-spine' },
    topoRail: 'Rail-optimized: NIC k of every node in a pod connects to leaf k, so GPU-k ↔ GPU-k traffic stays one hop away and PXN keeps most collectives inside the NVLink domain plus one rail.',
    topoTree: 'Fat tree / Clos: every leaf connects to every spine; capacity is preserved toward the root so any permutation can be routed.',
    suTitle: '4.3 Scalable units',
    suIntro: (pods: number, gpuRacks: number, gpus: number) => `${pods} deployment units (pods), ${gpuRacks} GPU racks, ${gpus} GPUs. Each pod carries its own leaves; spines/cores are shared.`,
    osTitle: '4.4 Oversubscription',
    osIntro: 'Oversubscription at a tier = bandwidth toward servers ÷ bandwidth toward spines (written down:up = N:1). A 64 × 800G leaf with 32 server / 32 spine ports is 1:1 (non-blocking by capacity); with 48 / 16 it is 3:1. NVIDIA writes the same 3:1 as "1:3 blocking"; AMD\'s "1:1.16" is an undersubscription (uplink = 1.16 × downlink).',
    osProject: (so: number, fe: number, st: number) => `This design: scale-out ${so}:1, front-end ${fe}:1, storage ${st}:1.`,
    fabric: 'Fabric', endpoints: 'Endpoints', tiers: 'Tiers (switches)', switches: 'Total switches', os: 'Oversub.', bisection: 'Bisection', hops: 'Hops', power: 'Power', racks: 'Racks',
    endpointLinks: (n: string) => `endpoint links ${n}`,
    cableTitle: '4.5 Cable BOM',
    cableType: 'Cable type', qty: 'Qty', totalLen: 'Total length', avgLen: 'Average length', optics: 'Transceivers',
    commEff: (v: string) => `Scale-out collective-communication efficiency (vs ideal non-blocking IB XDR): **${v}**`,
    optPower: (kw: string, usd: string) => `Transceiver power (switch side): ${kw} kW · network equipment + cabling cost: ${usd}`,
  },
  // ── 5 control plane ──
  control: {
    intro: 'A centralised control plane runs on dedicated management racks and the out-of-band network, separate from the GPU fabrics:',
    items: [
      '**Provisioning & inventory** — bare-metal provisioning, firmware baselines, BMC/OOB reachability for every node, switch and PDU.',
      '**Scheduling** — Slurm and/or Kubernetes with a topology file generated from the planned fabric (rail/leaf membership) so jobs are packed onto minimal switch sets.',
      '**Fabric management** — subnet manager / UFM (InfiniBand) or NetQ-style telemetry (Ethernet); congestion-control (DCQCN, PFC on one priority) and adaptive-routing policies distributed as code.',
      '**Facility integration** — BMS/EPMS/DCIM feeds (rack power, inlet temperature, CDU flow/ΔP, leak detection) correlated with job telemetry for dynamic power allocation.',
    ],
    racks: (mgmt: number, oobOn: boolean) => `Management racks placed: ${mgmt}. OOB network: ${oobOn ? 'planned' : 'not planned'}.`,
  },
  // ── 6 storage ──
  storage: {
    intro: 'Training checkpoints, datasets and inference model weights are served from a parallel file system on dedicated storage racks:',
    racks: (n: number, tb: string, gbps: string) => `Storage racks placed: ${n} (usable capacity ${tb} TB, aggregate throughput ${gbps} GB/s from the catalog).`,
    perGpu: (v: string) => `Storage bandwidth per GPU: ${v} GB/s (design guideline 9–17 GB/s per GPU; checkpoint write bursts dominate).`,
    network: (on: boolean, fabric: string, os: number) => (on ? `Dedicated storage network: ${fabric}, oversubscription ${os}:1.` : 'Storage traffic converged on the front-end network (no dedicated fabric).'),
    federated: 'Centralised storage (one namespace per site) is assumed; federated tiers (object / archive) are outside this design.',
  },
  // ── 7 power supply ──
  power: {
    feedTitle: '7.1 Utility feeds',
    feed: 'Feed', voltage: 'Voltage', capacity: 'Capacity', substation: 'Substation', available: 'Available from',
    required: (v: string) => `Required utility capacity (design conditions, PF 0.95): **${v} MVA**`,
    firm: (total: string, firm: string) => `Total feed capacity: ${total} MVA · firm N−1 capacity: **${firm} MVA** (independent substations; largest substation group excluded)`,
    loadTitle: '7.2 Load composition',
    load: 'Load', kw: 'kW', nameplate: 'IT nameplate (racks + network)', design: (d: number) => `IT design (diversity ${d})`, peak: 'IT transient peak (EDPP)', network: 'Network (switches + optics)',
    mechanical: 'Mechanical (design conditions)', losses: 'Losses + ancillary', total: '**Facility total**',
    hall: 'Hall', itLoad: 'IT load', budget: 'Budget', util: 'Utilisation',
    distTitle: '7.3 Distribution & one-line diagram',
    dist: (v: number, kind: string, profile: string) => `Distribution voltage ${v} V (${profile}), ${kind} to the racks.`,
    distVal: { busway: 'overhead A/B busway with tap-off boxes', rpp: 'remote power panels (RPP) with whips', hybrid: 'busway for GPU rows, RPPs for support racks' },
    profileVal: { iec: 'IEC profile', nec: 'NEC profile', kr: 'KR profile' },
    oneLine: 'One-line diagram',
  },
  // ── 8 resiliency ──
  resiliency: {
    intro: 'Redundancy is applied per subsystem; the table lists installed vs required capacity at the design load.',
    system: 'System', redundancy: 'Redundancy', units: 'Units', unitCap: 'Unit rating', installed: 'Installed', required: 'Required',
    ups: 'UPS', generator: 'Generators', transformer: 'Transformers', rpp: 'RPP', busway: 'Busway', maxLoading: (v: string) => `max loading ${v}`,
    strategiesTitle: '8.1 Key strategies',
    battery: (min: number) => `UPS battery autonomy ${min} min (bridging generator start and transfer).`,
    mechUps: (on: boolean) => `Mechanical loads (CDU pumps, CRAH fans) on UPS: ${on ? 'yes — cooling ride-through is guaranteed during transfer' : 'no — thermal inertia of the TCS/FWS loops covers the transfer window'}.`,
    smoothing: { none: 'Power smoothing: none — the utility sees the full training-load swing (EDPP transients up to the peak listed above).', 'rack-level': 'Power smoothing: rack-level energy storage (power-shelf capacitors/batteries) limits ramp rate and peak seen by the busway and utility.', bess: 'Power smoothing: facility BESS on the MV bus buffers load swings and provides ride-through / demand response.' },
    peak: (peak: string, design: string) => `Transient peak (EDPP) ${peak} kW vs design load ${design} kW — breakers and busway are rated to the peak, UPS/generators to the design load.`,
    firm: 'Utility firm capacity is evaluated N−1 across substations (see 7.1); a single substation loss must not exceed the generator fleet.',
  },
  // ── 9 BOM ──
  bom: {
    domain: 'Domain', amount: 'Amount', share: 'Share',
    domainLabel: { it: 'IT', network: 'Network', cabling: 'Cabling', power: 'Power', cooling: 'Cooling', facility: 'Facility', labor: 'Labour', contingency: 'Contingency' },
    metric: 'Metric', value: 'Value', capex: 'CAPEX', opex: 'Annual OPEX (energy + 2 % maintenance)', energy: 'Annual energy', tco: '5-year TCO', perGpu: 'CAPEX per GPU', perMw: 'CAPEX per MW IT', fx: 'Currency conversion',
    fxVal: (krw: string, rate: number, isKrw: boolean) => (isKrw ? `₩${krw} (×10⁸)` : `₩${krw} (×10⁸) at ${rate} KRW/USD`),
    estimateTitle: '9.1 Power estimate',
    estimateIntro: (design: string, facility: string, avg: string, mwh: string) => `IT design load ${design} kW → facility ${facility} kW at design conditions; annual-average facility draw ${avg} kW → ${mwh} MWh per year at 85 % average IT utilisation.`,
    detailTitle: '9.2 BOM detail',
    item: 'Item', qty: 'Qty', unit: 'Unit', unitPrice: 'Unit price', total: 'Total', leadTime: 'Lead time', source: 'Source', weeks: 'wk',
    deployNote: 'Per-wave materials lists (BOM by wave) and the rack plan are provided as separate deliverables in the deployment bundle.',
  },
  // ── 10 deploy ──
  deploy: {
    milestone: 'Milestone', date: 'Date',
    phase: { procurement: 'Procurement', site: 'Design & site', power: 'Power', cooling: 'Cooling', it: 'IT install', network: 'Network', commissioning: 'Commissioning', handover: 'Handover' },
    ramp: 'Capacity ramp', cumGpus: 'Cumulative GPUs', cumIt: 'Cumulative IT',
    critical: (v: string) => `Critical-path tasks: ${v}`,
    labor: (h: string, crews: string, size: number, days: number, hours: number) => `Total labour: ${h} h (crews ${crews}, ${size} per crew, ${days} days × ${hours} h per week)`,
    issuesTitle: '10.1 Validation issues & risks',
    noIssues: 'No issues detected.',
    issuesLangNote: '_Some engine messages below are shown in Korean (the UI language) — an English rendering is not available for every check yet._',
    severity: 'Severity', domain: 'Domain', message: 'Issue', suggestion: 'Recommendation',
    sev: { error: 'error', warning: 'warning', info: 'info' },
    acceptanceTitle: '10.2 Acceptance',
    acceptance: [
      '**L1–L3** — factory and site component tests, system-level commissioning of UPS, generators, CDUs, CRAHs and chillers at rated load.',
      '**L4 integrated system** — failure scenarios (loss of utility, generator failure, loss of 0–4 RPP/busway sections, CDU pump failover) with IT load banks at design load.',
      '**L5 cluster validation** — per-node diagnostics (DCGM diag / AGFHC), per-rail RDMA bandwidth (ib_write_bw), nccl-tests / rccl-tests sweeps against thresholds (all_reduce busbw, all-to-all ≥ ~0.85 × NIC line rate), storage IOR/FIO, rack inlet temperature and CDU flow/ΔP checks.',
    ],
  },
  // ── 11 sources ──
  sources: {
    equipment: 'Equipment', vendorModel: 'Vendor / model', dataSource: 'Data source', notes: 'Notes', cable: 'Cable', reach: 'Max reach', source: 'Source',
    methodTitle: 'Calculation methods',
    methods: [
      '- **Power**: IT design = rack nameplate × diversity + network. UPS efficiency 97 %, transformer losses 1.5 %, distribution losses 1 %, electrical-room cooling = (UPS + transformer losses) × 30 %. Firm N−1 utility = total − largest substation group.',
      '- **Cooling**: rack heat split into CDU / air by liquidFraction. Flow interpolated from the liquid-flow / airflow vs temperature curves of each catalog item (liquidFlowCurve / airflowCurve). Chiller COP 3.3 (design) / 5.0 (annual); 1/25 of the load as power during economizer hours.',
      '- **Network**: leaf downlinks d = ⌊k·o/(o+1)⌋; rail-optimised leaves per pod in multiples of the rail count; 2 tiers when L ≤ k. Cable length = Manhattan distance × route factor + tray rise/fall + slack per end.',
      '- **Workload**: training FLOPs = 6·N·D; step time = compute (incl. PP bubble) + TP/PP/DP/EP communication. Goodput = 1 − δ/τ − (τ/2 + δ + R)/MTBF. Inference decode is memory-bandwidth bound and prefill compute bound; TP/PP/EP/CP set replica shape, while P/D disaggregation sizes the two pools separately and adds KV transfer.',
      '- **Cost**: catalog prices (incl. estimates) × quantities + synthetic items (batteries, piping, facility) + labour + contingency. OPEX = energy at 85 % average IT load + 2 % of CAPEX.',
      '- **Schedule**: long-lead items (≥ 26 weeks) ordered at project start; durations from work quantity / crew capacity, crews shared between waves, critical path by CPM.',
    ],
    disclaimer: '> Prices, lead times and some specifications in this document are planning-stage estimates. Replace them with firm quotations and vendor datasheets.',
  },
  sourceLabel: {
    'open-standard': 'Open standard (cited document and revision)',
    'vendor-datasheet': 'Vendor datasheet',
    'public-spec': 'Public specification',
    estimate: 'Estimate (update on quotation)',
    announced: 'Announced specification (pre-release)',
    user: 'User defined',
  },
  units: { kw: 'kW', mw: 'MW', m: 'm', m2: 'm²', mva: 'MVA', lpm: 'LPM', kgm2: 'kg/m²', tbps: 'Tbps', days: 'days' },
  yes: 'yes', no: 'no',
};

export type DocStrings = typeof EN;
