import type { Locale } from '../model/types.ts';

/** Strings of the network deliverables (cable schedule · IP plan · switch inventory · bundle README). EN default, KO selectable. */
export const NET_EN = {
  bundleTitle: (p: string) => `${p} — deployment bundle`,
  bundleIntro: 'Printable HTML and spreadsheet CSV deliverables generated from the placed layout and the network / power / cooling analysis. CSV files are UTF-8 with a byte-order mark (opens correctly in Excel) and a fixed column order.',
  file: 'File', contents: 'Contents', rows: 'Rows',
  files: {
    bomCsv: 'Materials per deployment wave (racks by class, switches, cables by type and length bin, transceivers, trays, busway runs, tap-offs, CDU/CRAH, PDUs).',
    bomHtml: 'Printable BOM by wave with per-wave summary and totals.',
    rackCsv: 'Rack schedule (hall · row · position · tag · type · wave · kW · weight).',
    rackHtml: 'Printable rack plan with U-maps per rack type.',
    cableCsv: 'Port-to-port cable schedule — one row per physical cable with both-end labels.',
    cableHtml: 'Printable cable schedule grouped by fabric.',
    dot: 'Cabling plan in Cumulus PTM topology.dot syntax for LLDP verification (ptmctl).',
    ipCsv: 'Dual-stack IP / ASN plan (IPv4 and IPv6, all sections in one file with a `section` column).',
    ipSectionCsv: 'One dual-stack CSV per IP-plan section (blocks, loopbacks, ASNs, p2p, hosts, OOB).',
    ipHtml: 'Printable dual-stack IP / ASN plan with an executive summary and rail allocation matrix.',
    inventory: 'Switch inventory (hostname, role, fabric, model, rack, U, loopback, ASN, management IP).',
    nos: 'Per-switch NOS configuration files for the selected target, with a README of assumptions and sources.',
    tests: 'Acceptance test kit (inventory, links, RDMA, collectives / η measurement, node, storage, thermal & power).',
  },
  generated: (at: string) => `Generated ${at}`,
  notAvailable: (what: string) => `${what}: the network engine returned no rows for this project state — the file contains the header only.`,
  cableTitle: (p: string) => `${p} — Cable schedule`,
  cableIntro: 'One row per physical cable. Label content follows NVIDIA "Cabling Data Centers" DU-10438 §5.2.3 / §6.4.2 (source, destination, port, cable type and length, bundling sequence number). Identifiers are TIA-606-style (floor-grid rack · U · port); this is a reference format, not a claim of TIA-606 compliance. Apply labels 3–4 in. from the connector at both ends.',
  reachRule: 'Reach check: runs at or above 90 % of the media reach are flagged (DU-10438 acceptance rule "keep cable runs less than 90 % of the max distance").',
  cableCols: { id: 'Cable ID', bsn: 'BSN', fabric: 'Fabric', wave: 'Wave', aRack: 'A rack', aU: 'A U', aPort: 'A port', bRack: 'B rack', bU: 'B U', bPort: 'B port', type: 'Cable type', length: 'Length m', reach: 'Reach m', util: 'Reach %', check: 'Check', labelA: 'Label A', labelB: 'Label B' },
  reachOk: 'ok', reachOver: '≥ 90 % reach', reachUnknown: 'unknown type',
  cableSummary: (n: string, fabrics: number) => `${n} cables in ${fabrics} fabric(s).`,
  ipTitle: (p: string) => `${p} — IP / ASN plan`,
  ipIntro: 'Deterministic dual-stack addressing from the same network model used by the on-screen IP map: IPv4 /31 and IPv6 /127 per backend NIC, /64 per access segment, /128 loopbacks, and BGP unnumbered on fabric links by default (IPv6 link-local next hops). Verify the generated project ULA or replace it with the organisation-assigned /48 before deployment.',
  ipSections: { blocks: 'Address blocks', loopbacks: 'Loopbacks (router-id)', asns: 'ASNs', p2p: 'Fabric point-to-point links', hosts: 'Host NIC addresses', oob: 'Out-of-band management' },
  ipSummary: { title: 'Address-plan summary', families: 'Families', ipv4: 'IPv4 site block', ipv6: 'IPv6 site prefix', fabric: 'Fabric transit', endpoints: 'Addressed endpoints', rails: 'Backend rail allocation', notes: 'Validation notes' },
  ipMapTitle: 'Address allocation map',
  ipMapIntro: 'Bars preserve each block’s true position and share inside the site prefix. Very small IPv4 blocks remain visible as a one-pixel line; the CIDR label is authoritative.',
  ipMapV4: 'IPv4 /8 allocation',
  ipMapV6: 'IPv6 /48 role allocation',
  ipRailTitle: 'Backend rail address matrix',
  ipRailIntro: 'One row per hall · plane · rail. IPv6 shows the distinct /64 rail prefix; IPv4 may span several leaf blocks and is therefore listed as a count of distinct subnets.',
  ipSubnetCount: (n: number) => `${n} subnet${n === 1 ? '' : 's'}`,
  ipV6CapacityNote: 'IPv6 /64 capacity is not shown as a raw utilisation percentage: its address count is operationally misleading. The tables show assigned endpoints and prefix ownership instead.',
  ipCols: { family: 'Family', name: 'Name', cidr: 'CIDR', purpose: 'Purpose', device: 'Device', hostname: 'Hostname', role: 'Role', ip: 'IPv4', ipv6: 'IPv6', asn: 'ASN', link: 'Link', a: 'A end', b: 'B end', unnumbered: 'Addressing', node: 'Node', nic: 'NIC', vlan: 'VLAN', gw: 'IPv4 gateway', ipv6Gw: 'IPv6 gateway', hall: 'Hall', network: 'Network', plane: 'Plane', rail: 'Rail', switch: 'Switch', prefixes: 'Prefixes', endpoints: 'Endpoints' },
  unnumbered: 'unnumbered (IPv6 LL)', numbered: 'numbered',
  roles: { leaf: 'leaf', spine: 'spine', core: 'core', 'super-spine': 'super-spine', mgmt: 'management', unknown: '-' } as Record<string, string>,
  empty: 'No entries.',
};

export type NetStrings = typeof NET_EN;

export const NET_KO: NetStrings = {
  bundleTitle: (p) => `${p} — 배포 번들`,
  bundleIntro: '배치된 레이아웃과 네트워크·전력·냉각 분석에서 생성한 인쇄용 HTML과 스프레드시트용 CSV 산출물. CSV는 BOM이 붙은 UTF-8(엑셀에서 한글이 깨지지 않음)이며 열 순서가 고정되어 있다.',
  file: '파일', contents: '내용', rows: '행',
  files: {
    bomCsv: '배포 웨이브별 자재(랙 종류별, 스위치, 종류·길이 구간별 케이블, 광모듈, 트레이, 버스웨이 구간, 탭오프, CDU/CRAH, PDU).',
    bomHtml: '웨이브별 요약과 합계를 포함한 인쇄용 BOM.',
    rackCsv: '랙 일정표(홀 · 열 · 위치 · 태그 · 유형 · 웨이브 · kW · 무게).',
    rackHtml: '랙 유형별 U-맵을 포함한 인쇄용 랙 플랜.',
    cableCsv: '포트 단위 케이블 스케줄 — 물리 케이블 1개당 1행, 양단 라벨 포함.',
    cableHtml: '패브릭별로 묶은 인쇄용 케이블 스케줄.',
    dot: 'LLDP 검증(ptmctl)용 Cumulus PTM topology.dot 형식 케이블 계획.',
    ipCsv: '듀얼 스택 IP / ASN 계획(IPv4·IPv6, 모든 섹션을 `section` 열이 있는 한 파일에).',
    ipSectionCsv: 'IP 계획 섹션별 듀얼 스택 CSV(블록, 루프백, ASN, p2p, 호스트, OOB).',
    ipHtml: '요약과 레일 주소 매트릭스를 포함한 인쇄용 듀얼 스택 IP / ASN 계획.',
    inventory: '스위치 인벤토리(호스트명, 역할, 패브릭, 모델, 랙, U, 루프백, ASN, 관리 IP).',
    nos: '선택한 NOS 대상의 스위치별 설정 파일과 가정·출처 README.',
    tests: '인수 시험 키트(인벤토리, 링크, RDMA, 집합 통신 / η 측정, 노드, 스토리지, 열·전력).',
  },
  generated: (at) => `생성 ${at}`,
  notAvailable: (what) => `${what}: 현재 프로젝트 상태에서 네트워크 엔진이 행을 반환하지 않았다 — 파일에는 머리글만 있다.`,
  cableTitle: (p) => `${p} — 케이블 스케줄`,
  cableIntro: '물리 케이블 1개당 1행. 라벨 항목은 NVIDIA "Cabling Data Centers" DU-10438 §5.2.3 / §6.4.2(출발, 도착, 포트, 케이블 종류와 길이, 번들 순번 BSN)를 따른다. 식별자는 TIA-606 형식을 참고한 것(바닥 그리드 랙 · U · 포트)이며 TIA-606 준수를 주장하지 않는다. 라벨은 양단 커넥터에서 3–4인치 위치에 붙인다.',
  reachRule: '도달 거리 검사: 매체 최대 도달 거리의 90 % 이상인 구간을 표시한다(DU-10438 인수 규칙 "케이블 구간은 최대 거리의 90 % 미만").',
  cableCols: { id: '케이블 ID', bsn: 'BSN', fabric: '패브릭', wave: '웨이브', aRack: 'A 랙', aU: 'A U', aPort: 'A 포트', bRack: 'B 랙', bU: 'B U', bPort: 'B 포트', type: '케이블 종류', length: '길이 m', reach: '도달 m', util: '도달 %', check: '검사', labelA: 'A 라벨', labelB: 'B 라벨' },
  reachOk: '정상', reachOver: '도달 거리 90 % 이상', reachUnknown: '알 수 없는 종류',
  cableSummary: (n, fabrics) => `케이블 ${n}개 · 패브릭 ${fabrics}개.`,
  ipTitle: (p) => `${p} — IP / ASN 계획`,
  ipIntro: '화면의 IP 맵과 같은 네트워크 모델에서 생성한 결정론적 듀얼 스택 주소 계획: 백엔드 NIC마다 IPv4 /31·IPv6 /127, 액세스 구간마다 /64, 루프백 /128, 패브릭 링크는 기본적으로 BGP unnumbered(IPv6 링크 로컬 넥스트홉)를 사용합니다. 배포 전에 생성된 프로젝트 ULA를 검토하거나 조직에 할당된 /48로 바꾸세요.',
  ipSections: { blocks: '주소 블록', loopbacks: '루프백 (router-id)', asns: 'ASN', p2p: '패브릭 점대점 링크', hosts: '호스트 NIC 주소', oob: '대역 외(OOB) 관리' },
  ipSummary: { title: '주소 계획 요약', families: '주소군', ipv4: 'IPv4 사이트 블록', ipv6: 'IPv6 사이트 접두사', fabric: '패브릭 트랜짓', endpoints: '주소 할당 엔드포인트', rails: '백엔드 레일 할당', notes: '검증 노트' },
  ipMapTitle: '주소 할당 맵',
  ipMapIntro: '막대는 사이트 접두사 안에서 각 블록의 실제 위치와 비중을 유지합니다. 매우 작은 IPv4 블록은 1픽셀 선으로 표시되므로 정확한 범위는 CIDR 표기를 기준으로 하세요.',
  ipMapV4: 'IPv4 /8 할당',
  ipMapV6: 'IPv6 /48 역할 할당',
  ipRailTitle: '백엔드 레일 주소 매트릭스',
  ipRailIntro: '홀 · 플레인 · 레일마다 한 행입니다. IPv6는 레일별 고유 /64를 표시하고, IPv4는 여러 리프 블록에 걸칠 수 있으므로 서로 다른 서브넷 수로 표시합니다.',
  ipSubnetCount: (n) => `서브넷 ${n}개`,
  ipV6CapacityNote: 'IPv6 /64의 원시 주소 개수는 운영상 의미를 왜곡하므로 사용률 백분율로 표시하지 않습니다. 대신 표에서 할당된 엔드포인트 수와 접두사 소유 관계를 표시합니다.',
  ipCols: { family: '주소군', name: '이름', cidr: 'CIDR', purpose: '용도', device: '장비', hostname: '호스트명', role: '역할', ip: 'IPv4', ipv6: 'IPv6', asn: 'ASN', link: '링크', a: 'A 단', b: 'B 단', unnumbered: '주소 방식', node: '노드', nic: 'NIC', vlan: 'VLAN', gw: 'IPv4 게이트웨이', ipv6Gw: 'IPv6 게이트웨이', hall: '홀', network: '네트워크', plane: '플레인', rail: '레일', switch: '스위치', prefixes: '접두사', endpoints: '엔드포인트' },
  unnumbered: 'unnumbered (IPv6 LL)', numbered: '번호 지정',
  roles: { leaf: '리프', spine: '스파인', core: '코어', 'super-spine': '슈퍼 스파인', mgmt: '관리', unknown: '-' },
  empty: '항목 없음.',
};

export function netStrings(locale: Locale = 'en'): NetStrings {
  return locale === 'ko' ? NET_KO : NET_EN;
}
