import type { Locale } from '../model/types.ts';

/** Strings of the deployment bundle (BOM by wave · rack plan). English default, Korean selectable (DECISIONS-v2 #10). */
export const DEPLOY_EN = {
  common: 'Common / shared (not wave-specific)',
  unassigned: 'Unassigned',
  bomTitle: (project: string) => `${project} — Bill of Materials by deployment wave`,
  bomIntro: 'Quantities are taken from the placed layout and the network / power / cooling analysis. Racks, in-row CDUs, leaves and their cables belong to the wave of their deployment unit; spines, cores, hall-level CRAHs, trays and busway runs are listed under "common". Scope: IT, network, power distribution and cooling units by wave. Facility plant, labour and contingency are priced only in the cost BOM (design document, cost chapter); see "Reconciliation with the cost BOM" at the end.',
  reconTitle: 'Reconciliation with the cost BOM',
  reconIntro: 'Every cost BOM line and every wave BOM item, matched by item id. Shared items must agree in quantity. Cost-only lines have no deployment-wave quantity; wave-only lines are priced in the cost BOM through allowances (tray per rack, electrical balance of system).',
  reconCols: { scope: 'Scope', item: 'Item', domain: 'Cost domain', costQty: 'Cost BOM qty', waveQty: 'Wave BOM qty', unit: 'Unit', usd: 'Cost USD' },
  reconScope: { shared: 'Shared (both BOMs)', 'facility-plant': 'Cost only: facility plant / fit-out', 'power-plant': 'Cost only: power plant', 'cooling-plant': 'Cost only: cooling plant', labour: 'Cost only: labour', contingency: 'Cost only: contingency', allowance: 'Cost only: allowance (itemised in the wave BOM)', 'wave-only': 'Wave BOM only (priced via allowances)' } as Record<string, string>,
  reconTotals: 'Cost USD by scope',
  reconTotal: 'Total (= cost BOM total)',
  reconMismatch: (n: number) => `${n} shared item(s) differ in quantity between the two BOMs.`,
  reconNoCost: 'No cost analysis is available — the reconciliation table is omitted.',
  wave: 'Wave', group: 'Group', item: 'Item', lengthBin: 'Length bin', qty: 'Qty', unit: 'Unit', source: 'Source', totalLength: 'Total length', pods: 'Deployment units', target: 'Target ready date',
  groups: { racks: 'Racks by class', switches: 'Switches', cables: 'Cables by type and length', transceivers: 'Transceivers', trays: 'Cable trays', busways: 'Busway runs', tapoffs: 'Busway tap-offs', cooling: 'CDU / CRAH', pdus: 'PDUs / RPPs' },
  summaryTitle: 'Summary per wave',
  summaryCols: { wave: 'Wave', racks: 'Racks', gpus: 'GPUs', accelerators: 'Accelerators (slot)', switches: 'Switches', cables: 'Cables', optics: 'Transceivers', cooling: 'CDU/CRAH', kw: 'IT nameplate kW' },
  totalsTitle: 'Totals (all waves)',
  acceleratorLine: (name: string, chips: number) => `${name} — accelerator slot (${chips} ${chips === 1 ? 'chip' : 'chips'} per rack, not counted as GPUs)`,
  noTrays: 'No cable-tray polylines in the project (project.trays) — tray metres are not itemised; the cost BOM carries a per-rack tray allowance.',
  noBusways: 'No busway polylines in the project (project.busways) — busway runs and tap-offs are derived from the power analysis (runs per pod per A/B path; two tap-offs per rack).',
  busRun: (path: string) => `Busway run (path ${path})`,
  tapoff: 'Busway tap-off box (A/B per rack)',
  tray: (kind: string, w: string) => `Cable tray (${kind}, ${w} m wide)`,
  unplaced: '(not placed — additional units from the analysis)',
  rackTitle: (project: string) => `${project} — Rack plan`,
  rackIntro: 'One row per rack (GPU, CPU, storage, network and management racks). Position = 1-based slot along the row, counted from the row start. Power = nameplate × load factor; weight from the catalog.',
  rackCols: { hall: 'Hall', row: 'Row', position: 'Position', tag: 'Tag', type: 'Type', category: 'Category', wave: 'Wave', kw: 'kW', weight: 'Weight kg', pod: 'DU', role: 'Network role', x: 'X m', y: 'Y m', rot: 'Rot °' },
  umapTitle: 'U-maps per rack type',
  umapIntro: 'Elevation per distinct rack type (identical racks share one map). Network racks are populated from the placed switch assignment (rackLoads); rack-scale systems from public specifications.',
  umapCols: { ru: 'RU', content: 'Content', qty: 'Qty', source: 'Source' },
  umapRacks: (n: number, tags: string) => `${n} rack(s): ${tags}`,
  free: 'free / blanking',
  ruUsed: (used: number, cap: number, kw: string, kwCap: string) => `RU used ${used} / ${cap} · ${kw} / ${kwCap} kW`,
  categories: { 'gpu-rack': 'GPU rack', 'cpu-rack': 'CPU rack', 'storage-rack': 'Storage rack', 'network-rack': 'Network rack', 'mgmt-rack': 'Management rack' } as Record<string, string>,
  umapItems: {
    powerShelf: 'Power shelf (busbar feed)', computeTray: 'Compute tray (2 × GPU node)', nvswitch: 'NVLink switch tray', gpuServer: (gpus: number) => `${gpus}-GPU server`, cpuServer: 'CPU server', storageNode: 'Storage node (NVMe)', mgmtServer: 'Management server', torSwitch: 'ToR / management switch', pduSpace: 'rPDU / cable management',
    leaf: 'leaf', spine: 'spine', core: 'core',
  },
  sourceLabel: { 'open-standard': 'open standard', 'vendor-datasheet': 'datasheet', 'public-spec': 'public spec', estimate: 'estimate', announced: 'announced', user: 'user' } as Record<string, string>,
};

export type DeployStrings = typeof DEPLOY_EN;

export const DEPLOY_KO: DeployStrings = {
  common: '공통 / 공유 (특정 웨이브 아님)',
  unassigned: '미배정',
  bomTitle: (project) => `${project} — 배포 웨이브별 자재 명세 (BOM)`,
  bomIntro: '수량은 배치된 레이아웃과 네트워크·전력·냉각 분석에서 가져온다. 랙, 인로우 CDU, 리프와 그 케이블은 소속 배포 단위의 웨이브에, 스파인·코어·홀 단위 CRAH·트레이·버스웨이는 "공통"에 둔다. 범위: 웨이브별 IT·네트워크·전력 분배·냉각 유닛. 시설 플랜트·인건비·예비비는 비용 BOM(설계서 비용 장)에만 있다. 끝의 "비용 BOM과의 대사"를 참고한다.',
  reconTitle: '비용 BOM과의 대사',
  reconIntro: '비용 BOM의 모든 항목과 웨이브 BOM의 모든 품목을 품목 ID로 대응시켰다. 공통 품목은 수량이 같아야 한다. 비용 전용 항목은 배포 웨이브 수량이 없고, 웨이브 전용 품목은 비용 BOM에서 할당액(랙당 트레이, 전기 BOS)으로 가격이 반영된다.',
  reconCols: { scope: '범위', item: '품목', domain: '비용 도메인', costQty: '비용 BOM 수량', waveQty: '웨이브 BOM 수량', unit: '단위', usd: '비용 USD' },
  reconScope: { shared: '공통 (양쪽 BOM)', 'facility-plant': '비용 전용: 시설 플랜트·마감', 'power-plant': '비용 전용: 전력 플랜트', 'cooling-plant': '비용 전용: 냉각 플랜트', labour: '비용 전용: 인건비', contingency: '비용 전용: 예비비', allowance: '비용 전용: 할당액 (웨이브 BOM에 항목화)', 'wave-only': '웨이브 BOM 전용 (할당액으로 가격 반영)' },
  reconTotals: '범위별 비용 USD',
  reconTotal: '합계 (= 비용 BOM 합계)',
  reconMismatch: (n) => `공통 품목 ${n}개의 수량이 두 BOM 사이에서 다르다.`,
  reconNoCost: '비용 분석이 없어 대사 표를 생략했다.',
  wave: '웨이브', group: '구분', item: '품목', lengthBin: '길이 구간', qty: '수량', unit: '단위', source: '출처', totalLength: '총 길이', pods: '배포 단위', target: '목표 가동일',
  groups: { racks: '랙 (종류별)', switches: '스위치', cables: '케이블 (종류·길이별)', transceivers: '광모듈', trays: '케이블 트레이', busways: '버스웨이 구간', tapoffs: '버스웨이 탭오프', cooling: 'CDU / CRAH', pdus: 'PDU / RPP' },
  summaryTitle: '웨이브별 요약',
  summaryCols: { wave: '웨이브', racks: '랙', gpus: 'GPU', accelerators: '가속기(슬롯)', switches: '스위치', cables: '케이블', optics: '광모듈', cooling: 'CDU/CRAH', kw: 'IT 명판 kW' },
  totalsTitle: '합계 (전체 웨이브)',
  acceleratorLine: (name: string, chips: number) => `${name} — 가속기 슬롯 (랙당 칩 ${chips}개, GPU 수에 미포함)`,
  noTrays: '프로젝트에 케이블 트레이 폴리라인(project.trays)이 없어 트레이 미터를 항목화하지 않았다. 비용 BOM은 랙당 트레이 할당량을 포함한다.',
  noBusways: '프로젝트에 버스웨이 폴리라인(project.busways)이 없어 버스웨이 구간·탭오프는 전력 분석에서 도출했다(포드별 A/B 경로당 구간 수, 랙당 탭오프 2개).',
  busRun: (path) => `버스웨이 구간 (경로 ${path})`,
  tapoff: '버스웨이 탭오프 박스 (랙당 A/B)',
  tray: (kind, w) => `케이블 트레이 (${kind}, 폭 ${w} m)`,
  unplaced: '(미배치 — 분석 기준 추가 대수)',
  rackTitle: (project) => `${project} — 랙 플랜`,
  rackIntro: '랙(GPU·CPU·스토리지·네트워크·관리)당 1행. 위치 = 열 시작점부터 센 1 기반 슬롯 번호. 전력 = 명판 × 부하율, 무게는 카탈로그 값.',
  rackCols: { hall: '홀', row: '열', position: '위치', tag: '태그', type: '유형', category: '분류', wave: '웨이브', kw: 'kW', weight: '무게 kg', pod: 'DU', role: '네트워크 역할', x: 'X m', y: 'Y m', rot: '회전 °' },
  umapTitle: '랙 유형별 U-맵',
  umapIntro: '고유 랙 유형별 입면도(동일 랙은 하나의 맵 공유). 네트워크 랙은 배치된 스위치 할당(rackLoads), 랙 규모 시스템은 공개 사양 기준.',
  umapCols: { ru: 'RU', content: '내용', qty: '수량', source: '출처' },
  umapRacks: (n, tags) => `랙 ${n}대: ${tags}`,
  free: '여유 / 블랭킹',
  ruUsed: (used, cap, kw, kwCap) => `RU 사용 ${used} / ${cap} · ${kw} / ${kwCap} kW`,
  categories: { 'gpu-rack': 'GPU 랙', 'cpu-rack': 'CPU 랙', 'storage-rack': '스토리지 랙', 'network-rack': '네트워크 랙', 'mgmt-rack': '관리 랙' },
  umapItems: {
    powerShelf: '파워셸프 (버스바 급전)', computeTray: '컴퓨트 트레이 (GPU 노드 2개)', nvswitch: 'NVLink 스위치 트레이', gpuServer: (gpus) => `${gpus}-GPU 서버`, cpuServer: 'CPU 서버', storageNode: '스토리지 노드 (NVMe)', mgmtServer: '관리 서버', torSwitch: 'ToR / 관리 스위치', pduSpace: 'rPDU / 케이블 정리',
    leaf: '리프', spine: '스파인', core: '코어',
  },
  sourceLabel: { 'open-standard': '공개 표준', 'vendor-datasheet': '데이터시트', 'public-spec': '공개 사양', estimate: '추정치', announced: '발표 사양', user: '사용자 정의' },
};

export function deployStrings(locale: Locale = 'en'): DeployStrings {
  return locale === 'ko' ? DEPLOY_KO : DEPLOY_EN;
}
